### ISSUE TITLE
self-update: Errors after updating

### ISSUE THREAD

**Issue by pjcdawkins** [hechoendrupal/DrupalConsole#1049]
A colleague (@joshmiller83) mentioned a problem after `self-update` - errors relating to ConsoleTerminateEvent.

![upload](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/42097/298738/Bj4wvtc6BpkSbO3/upload.png)

I case it helps - I just fixed the same problem in the platform.sh CLI with a rather hacky solution:
https://github.com/platformsh/platformsh-cli/blob/7a122d3f3226d5e6ed0a0b74803158c51b31ad5e/src/Command/Self/SelfUpdateCommand.php#L72-L77

Maybe you want to borrow that.

Or, an alternative solution might be trying to re-register the new Composer autoloader - maybe just `require 'phar://console.phar/vendor/autoload.php';` would do it.

**Comment by pjcdawkins** [comment]
Another colleague (@damz) has pointed out that it's more likely to be a phar problem - PHP misreading files that have been swapped out under it - so it can be better solved by writing the new file atomically (temporary file, then rename).

**Comment by jmolivas** [comment]
@pjcdawkins: Thanks for reporting the issue and the tip, I will take a look at this.

**Comment by jmolivas** [comment]
@pjcdawkins: I did apply your hacky solution at the slef-update command.

**Comment by darol100** [comment]
This issue seem to be solve at #1118. So I'm closing it.
