### ISSUE TITLE
[generate:service] Contains statement generation lacks initial backslash.

### ISSUE THREAD

**Issue by wizonesolutions** [hechoendrupal/DrupalConsole#1074]
Example:

````
/**
 * @file
 * Contains Drupal\fillpdf\OutputHandlerInterface.
 */
````

Should be `\Drupal\fillpdf\OutputHandlerInterface`

This happens in both the class and the interface.

Reference: https://www.drupal.org/node/1354#file

**Comment by jmolivas** [comment]
@wizonesolutions thanks for notifying this we take care and have it fox on the next release.

**Comment by favrik** [comment]
@jmolivas so the fix would involve updating these files https://gist.github.com/favrik/86ef2b29af1353a77622 ?
