### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by bojanz** [hechoendrupal/DrupalConsole#1087]
When running test:debug or test:run I get
```
 [InvalidArgumentException]                                                         
  Module "simpletest" is not in your application. Try generate:module to create it. 
```
Simpletest is already enabled.

Maybe it's expecting an argument and not telling me?

**Comment by jepster** [comment]
I confirm. Having the same problem.

**Comment by jmolivas** [comment]
@bojanz @jepster This was fixed on latest release v.0.9.5

NOTE: Make sure you install simpletest module `drupal module:install simpletest`

May you confirm which version of DC are you using

**Comment by bojanz** [comment]
I was on 0.9.4, confirming that updating fixed it.
