### ISSUE TITLE
Drupal Console Analyzer

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1092]
## Problem/ Motivation
A nice feature for Drupal console can be adding the functionality to scan your Drupal 7 code an provide you a list of recommendation on how to rewrite this things with Drupal Console commands.

## Similar Project
[Drupal Module Upgrader](https://www.drupal.org/project/drupalmoduleupgrader) have an analyzer that provide already the ability of scan your D7 code and provide you documentation on how to do it on D8.

## Possible Solution
The idea of this feature is to write something similar of what [Drupal Module Upgrader](https://www.drupal.org/project/drupalmoduleupgrader) is doing but instead of provide links to a long documentation on how to fix it,  Drupal console is going to provide you a list of command on how to do it with Drupal Console.

**Comment by claymullis** [comment]
This featureset would be an outstanding way to learn how to use Drupal 8.

**Comment by darol100** [comment]
Here is some extra information to get of the Drupal 8 changes. https://www.drupal.org/list-changes/drupal

@jmolivas .

**Comment by darol100** [comment]
I will close this issue for the same reason I close https://github.com/hechoendrupal/DrupalConsole/issues/662
