### ISSUE TITLE
[generate:controller] Check if the route exist

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1093]
## Problem / Motivation

Drupal 8 Development training we was discussing Drupal console. An as right now, we do not have away to see if there is another route with the same name.

## Solution
We should add a validation once we type `Enter router` and this will check if the route exists or not.

**Comment by enzolutions** [comment]
@darol100 this validator must be included in what command?

**Comment by darol100** [comment]
@enzolutions , In the perfect world in any place where the route is been generate it.

However, If I'm not wrong when I open this it was for `drupal generate:controller`

![screen shot 2015-11-26 at 4 53 07 pm](https://cloud.githubusercontent.com/assets/6808460/11432242/80c1afac-945e-11e5-83c7-91d9326091d6.png)

**Comment by edutrul** [comment]
Working on this to create a patch asap

**Comment by edutrul** [comment]
Added PR https://github.com/hechoendrupal/DrupalConsole/pull/2345 @jmolivas

**Comment by enzolutions** [comment]
Issues closed after merged solution
