### ISSUE TITLE
Aliases Discussion

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1095]
## Problem / Motivation
We should provide aliases (shortcuts) to simplify the Drupal Console commands.

## Solution
We should provide a list of recommend aliases and discuss them.

**Comment by dmouse** [comment]
You can execute each command only with the initial(s) letters, for example

console g:c
console gen:cont

**Comment by darol100** [comment]
@dmouse but we should provide a list of different types commands that we can improve. g:c is a good start but we can create more aliases.

**Comment by jmolivas** [comment]
The idea of this issue, is to specify the aliases instead of letting the component suggest.

**Comment by jmolivas** [comment]
I sent a PR https://github.com/hechoendrupal/DrupalConsole/pull/1128 to add command alias via user configuration file `~/.console/config.yml` 

* Configuration of command alias: https://github.com/jmolivas/DrupalAppConsole/blob/1095-console-command-alias-implementation/config/dist/config.yml#L26-L29

* Discovery of aliases: https://github.com/jmolivas/DrupalAppConsole/blob/1095-console-command-alias-implementation/src/Application.php#L246

* Setting alias to command: https://github.com/jmolivas/DrupalAppConsole/blob/1095-console-command-alias-implementation/src/Application.php#L259-L267

I know this issue is about defining the aliases to be assigned to commands, but I wanted to make this feature based on a configuration file to avoid changing code and make easy to override by the user.

**Comment by jmolivas** [comment]
After a reviewing the PR https://github.com/hechoendrupal/DrupalConsole/pull/1128 the following changes:
- Define aliases on a separated file `aliases.yml` instead of `config.yml`
- Use this YAML structure:
```
application:
  aliases:
    commands:
      cache:
        rebuild:
            - cr
```

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/1128 was merged 

We should start a discussion about best alias names for commands we will use,

These alias will be a recommendation and user can override by updating the copied file `~/.console/aliases.yml`

**Comment by darol100** [comment]
@jmolivas is this implementation going to have the aliases display in the drupal list  command?

For instance `drupal cache:build (cr)`. This will make user to easily learn the aliases.

**Comment by darol100** [comment]
Here are my suggestion for the new aliases.


### I do not think we need aliases for these
_completion
about
chain
complete
drush
help
init
list
self-update
              
 Cache
==========================      

  cache:rebuild                    = cr

 Config
==========================      

config:debug                     = cde
config:edit                      = cedit
config:export                    = ce
config:export:content:type       = cect
config:export:single             = ces
config:export:view               = cev
config:import                    = ci
config:import:single             = cis
config:override                  = co
      
               
 Container
==========================

  container:debug                  = cod

 Cron
==========================
  cron:debug                       = crd
  cron:execute                     = cre 
  cron:release                     = crr
        
 dblog
==========================
  dblog:clear                      = dbc
  dblog:debug                      = dbb
  
Generate     
==========================
  generate:authentication:provider = gap
  generate:command                 = gcm 
  generate:controller              = gcn
  generate:doc                     = gdc 
  generate:entity:bundle           = geb
  generate:entity:config           = gecg
  generate:entity:content          = gect 
  generate:event:subscriber        = ges 
  generate:form:alter              = gfa 
  generate:form:config             = gfc 
  generate:module                  = gm
  generate:permissions             = gp 
  generate:plugin:block            = gpb 
  generate:plugin:condition        = gpc 
  generate:plugin:field            = gpf 
  generate:plugin:fieldformatter   = gpff 
  generate:plugin:fieldtype        = gpft 
  generate:plugin:fieldwidget      = gpfw 
  generate:plugin:imageeffect      = gpie 
  generate:plugin:imageformatter   = gpif 
  generate:plugin:rest:resource    = gprr 
  generate:plugin:rulesaction      = gpra 
  generate:plugin:type:annotation  = gpta 
  generate:plugin:type:yaml        = gpty 
  generate:plugin:views:field      = gpvf 
  generate:service                 = gs 
  generate:theme                   = gt 

 Migrate
==========================
  migrate:debug                    = mid
  migrate:execute                  = mie 
  migrate:load                     = mil
  
 Module
==========================
  module:debug                     = mod
  module:download                  = modo 
  module:install                   = moi 
  module:uninstall                 = mou

 Rest
==========================
  rest:debug                       = rede
  rest:disable                     = redi
  rest:enable                      = ree

 Router
==========================
  router:debug                    = rod
  router:rebuild                  = ror

 Site
==========================
site:debug                      = sd
site:install                    = si
site:maintenance                = sma
site:mode                       = smo
site:new                        = sn
site:status                     = ss

 Test
==========================
  test:debug                      = td
  test:run                        = tr  

 Update
==========================
  update:debug                    = upd
  update:execute                  = upe  

 User
==========================
user:login:clear:attempts       = uslca
user:login:url                  = uslu
user:password:hash              = usph
user:password:reset             = uspr

 Views
==========================
  views:debug                     = vde
  views:disable                   = vdi
  views:enable                    = ve

Yaml
==========================
yaml:diff                       = yd
yaml:merge                      = ym
yaml:split                      = ys
yaml:update:key                 = yu
yaml:update:value               = yuv

**Comment by cburschka** [comment]
This might be beyond the scope of this issue, but could aliases maybe support arguments as well? It'd be nice to be able to specify those as part of a shortcut.

**Comment by jmolivas** [comment]
@cburschka: can mean like: 
```
cr = cr all
```
We should probably needs to make some adjustments to the yaml definition or maybe use the chain feature to create those.

https://hechoendrupal.gitbooks.io/drupal-console/content/en/using/how-to-download-install-and-serve-drupal8.html

**Comment by darol100** [comment]
I will take care of this.

**Comment by darol100** [comment]
@jmolivas I started working with this and for some reason sometimes the console is trying to get check for the command before it checks the aliases. For instance if I set this as an alias.

      config:
        override:
          - co

This is what happens...

![screen shot 2015-12-13 at 8 50 47 pm](https://cloud.githubusercontent.com/assets/6808460/11773212/61b42740-a1db-11e5-9ee6-6700328a6103.png)


I will keep working into this issue, but we might have to somehow to set the aliases as priority than the actual command maybe ?
