### ISSUE TITLE
[generate:form:config] Renaming "Update routing file [yes] ?" to a better description.

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1096]
## Problem / Motivation
When the user type `drupal generate:form:config` at some point is going to be ask  **Update routing file [yes] ?** I feel like "Update route file [yes] ?" does not provide enough information of what is going to happen next.

## Propose solution
I think is going to be better if we said something like .. 

**Would you like to create a route ?**  - This will give you the assumption that is going to update the routing file and is also telling that is going to generate a route.

**Comment by enzolutions** [comment]
Fixed in PR https://github.com/hechoendrupal/DrupalConsole/pull/2437
