### ISSUE TITLE
[generate:plugin:block] - Place block into region

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1097]
## Problem / Motivation
While we creating a block we usually want to adding directly into a block regions.

## Solution
After entering all the data from the block fields, we should add the functionality of placing a block into a region.

**Comment by enzolutions** [comment]
Thanks @darol100 for recommend us this idea, this was implemtente at https://github.com/hechoendrupal/DrupalConsole/pull/1312
