### ISSUE TITLE
[generate:service] - Adding Path of your service

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1098]
## Problem / Motivation:
`drupal generate:service` Does not provide you path where you are going to store the services.

## Solution
- We should add the ability of moving our services into a custom directory.
- The console should ask your if you want to generating a new path for the services.

**Comment by miguel303** [comment]
Fixed in #2429

**Comment by enzolutions** [comment]
Close this issue after PR solution was merged
