### ISSUE TITLE
Mac Yosemite Bash: Autocompletion does not work

### ISSUE THREAD

**Issue by jepster** [hechoendrupal/DrupalConsole#1100]
Hi,

if I follow your instructions and type "drupal TABULATOR-KEY" I get the following output:

drupal -bash: _get_comp_words_by_ref: command not found
-bash: __ltrim_colon_completions: command not found

How I can fix that?

**Comment by omero** [comment]
You need to have `bash-completion` installed, is needed for the dependency used (https://github.com/stecman/symfony-console-completion/issues/36) , i promise make the update in the README file ... or you can send a PR with the information :smile:

**Comment by kepford** [comment]
Thanks@omero. I just updated the README in this PR. https://github.com/hechoendrupal/DrupalConsole/pull/1102

**Comment by omero** [comment]
Thank you @kepford :smile:

**Comment by jepster** [comment]
Thanks
