### ISSUE TITLE
[console] Use your Drush @aliases to call Drupal Console

### ISSUE THREAD

**Issue by greg-1-anderson** [hechoendrupal/DrupalConsole#1104]
If you source something like the script below in a .bashrc or .bash_profile, then you can use `drupal @drushalias console:command` to run Drupal Console commands using Drush aliases.  Also works for remote site aliases.

```
#!/bin/bash

#
# Cool bash functions to integrate Drupal Console with Drush remote alias execution
#

# Allow `drupal @site consolecommand` as a shortcut for `cd @site; drupal consolecommand`.
# Also works on remote sites, though.
function drupal() {
  s="$1"
  if [ -n "$s" ] && [ ${s:0:1} == "@" ]
  then
    d="$(drush drupal-directory $s 2>/dev/null)"
    rh="$(drush sa ${s%%:*} --fields=remote-host --format=list)"
    if [ -n "$rh" ]
    then
      drush ${s%%:*} ssh "console '$d' ; git ${@:2}"
    else
      echo cd "$d" \; drupal "${@:2}"
      (
        cd "$d"
        "$(which drupal)" "${@:2}"
      )
    fi
  else
    "$(which drupal)" "$@"
  fi
}
```

**Comment by darol100** [comment]
This issue does not longer apply because Drush is not part of Drupal Console anymore (#1520). For this reason I'm closing this issue.

**Comment by greg-1-anderson** [comment]
The script here does not depend on the function removed in #1520.  Closing is fine, though; this example does not need to be part of Drupal Console; it would work for folks who want to use it independent of whether or not it is distributed as part of this project.

**Comment by jmolivas** [comment]
I think we can

**Comment by darol100** [comment]
Using this code as inspiration, we have merge this functionality into DrupalConsole core. You can use either `--target` or `@`.

Here is the implementation - https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Application.php#L115

**Comment by greg-1-anderson** [comment]
Very nice.
