### ISSUE TITLE
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]

### ISSUE THREAD

**Issue by enzolutions** [hechoendrupal/DrupalConsole#1129]
Sometimes when a Drupal Core function is called I got the following error

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
```

Specifically stating in Drupal 8 RC2 in command *migrate:execute* when I tried to create EntityQuery for migration entity storage I got the following error

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  The service definition "entity.query.config" does not exist.
```

The reason internally the core load services using a static method for instance in **\Drupal\Core\Entity\EntityStorageBase**

```
 /**
   * {@inheritdoc}
   */
  public function getQuery($conjunction = 'AND') {
    // Access the service directly rather than entity.query factory so the
    // storage's current entity type is used.
    return \Drupal::service($this->getQueryServiceName())->get($this->entityType, $conjunction);
  }
```

To avoid this problem I assign the DrupalConsole container to Drupal static function using this code

```
        // Set static container to static Drupal method to get services available
        \Drupal::setContainer($this->getContainer());
```

**Comment by darol100** [comment]
@enzolutions This seem to be a RC2 issue. Does this still apply ?

**Comment by darol100** [comment]
I could not replicate this issue and this seem pretty old. For this reason, I'm closing this issue.
