### ISSUE TITLE
Separation of the project and the language

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1133]
## Problem / Motivation

At Drupal Badcamp @jmolivas , @phenaproxima and myself we were discussing on how we are going to implement the Samuel Jack Language (#1106) into this project without been committed in the main project because does not look professional. This brings some interesting point because as today this project ships with all languages, which it should not it IMO because I'm not going to be using other languages that are not English. I think this project should be ship with English and if the user needs another language they can download it and integrated it to the project. Ships with all languages make the project a lot bigger instead of having it separate from the project.
## Solution
- We need to open new repositories called `console_[languagecode]` for instance for Spanish `console_es` in Github and Drupal.org.
  - We should provide admin rights to the people that contribute to languages often. So they can take care of the languages.
- We should have a command that can easily download the language if is under _hechoendrupal_ GitHub organization.
- We should try to have a travis job that creates a PR in all languages every time a new command get added to the project English.

**Note:** English is the only language that we are going to shipping with the Drupal Console because English is used for development purpose and not for translation purpose.
## Benefits
- Separates the development work with the translation work.
- Project get smaller.
- We can provide git access to translator without the need of getting access to the entire project.

**Comment by darol100** [comment]
Asking one more time about this issue. Since is been tag as "must-have".

@jmolivas 
>My understating was that you was going to talk with one of the composer maintainer about how to implement this. Did you get any response about this ?

**Comment by jmolivas** [comment]
Fixed
