### ISSUE TITLE
Unable to create fieldable bundles on config entities

### ISSUE THREAD

**Issue by kevinquillen** [hechoendrupal/DrupalConsole#1139]
Cross post: http://drupal.stackexchange.com/questions/179525/create-fieldable-bundle-types-for-an-entity-with-drupal-console

Basically I want to go beyond the generic object creation and spawn custom data structures that can have fielded bundle types, the same way nodes work in that regard.

**Comment by jmolivas** [comment]
@kevinquillen: I will take a look at

**Comment by kevinquillen** [comment]
Just posting some follow ups... I am learning btw so apologies if this has been covered.

So, out of the box DC generates a config and content entity. I followed the blog post here to begin learning how to enable types to be fieldable: http://www.agoradesign.at/blog/how-create-custom-entities-bundle-support-drupal-8

But it also seems to require this change in the Foo entity, which I did not see mentioned:

field_ui_base_route = "entity.foo_type.edit_form"

Instead of the generated "foo.settings". Along with that, I deleted my settings entries in the menu YML files, as it does not seem that Node uses anything like that.

Now, I can add fields to types... the next question is, modifying the admin/foo/add route to give you a list of types to add from (like node). Theming this addPage with node_add_list will result in a fatal error "undefined method getDescription()".

**Comment by kevinquillen** [comment]
Continuing that... if you implement your own theme for foo_add_list, where Foo is your entity, and add the callback with hook_theme (just like node) the entity type page takes shape.

You also need to add $description property to your FooType schema, and FooType form, and getDescription() method to your FooTypeInterface and FooType implementation.

Also, altering your routing so that admin/foo points to addPage in your Controller, and add an entry for entity.foo.add, which has a route parameter for {foo_type}. Now this is very close to the barebones node/node_type functionality.

Note that my goal isn't to replicate the node system... but get to where I was in D7 with Entity API. Custom data structures with bundles and fields per bundle.

**Comment by kevinquillen** [comment]
I *think* that out of the box, the console should generate a config/content entity (or prompt you) that acts like this, even if you only plan on having one entity type ever, or not adding fields on it. Would save a super amount of time.

**Comment by darol100** [comment]
Closing this issue because this was been solve at #1261
