### ISSUE TITLE
Create a generate:form command that will generate scaffolding for basic forms extending the FormBase class

### ISSUE THREAD

**Issue by sgtsaughter** [hechoendrupal/DrupalConsole#1146]
I've noticed there's a generate:form:config which will generate an admin config form, but there isn't a way to generate a basic form extending the FormBase class.  I've been following this documentation https://www.drupal.org/node/2117411 and have successfully built a basic form using it.  It could be used to help with generating the scaffolding.  It would also be nice if this command can function similarly to the generate:form:config command where you're able to generate the form structure.

**Comment by jmolivas** [comment]
@sgtsaughter: There is a PR for that https://github.com/hechoendrupal/DrupalConsole/pull/1122

You may want to help testing the PR and adding some comments.

**Comment by darol100** [comment]
This have been solve already at #1122 so I'm closing this issue.
