### ISSUE TITLE
Enable theme_debug with Drupal Console

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1148]
## Problem/ Motivation
Drupal 8 ships with a twig debugger out-the-box that allows you to see the suggestion templates into html. It will be nice if we can have a command in Drupal Console that will enable that quickly instead of manually editing that file.

## Solution
According to the twig/drupal8 documentation in order to enable the debug...

How to enable debugging
 - Locate your site's services.yml file, likely located in sites/default/services.yml
 - If services.yml does not yet exist; copy default.services.yml and rename it to services.yml.
 - Edit the services.yml file and enable one or more of the debugging options defined below.

Locate the twig.config parameters in your services.yml and make changes there. Example:

````
parameters:
  twig.config:
    debug: true
`````

For more information about enabling the theme_debug - https://www.drupal.org/node/2358785

For more information about twig/drupal 8 debugging tools - https://www.drupal.org/node/1903374

**Comment by jmolivas** [comment]
You can enable/disable Twig debug by using `site:mode` command
```
drupal site:mode dev
drupal site:mode prod
```
![site-mode-twig](https://cloud.githubusercontent.com/assets/366275/10930862/46bd3e78-8277-11e5-96a5-56080022d4e1.png)

**Comment by darol100** [comment]
I'm closing this issue since this have been already implemented.
