### ISSUE TITLE
Adding Drupal Console as Development Tool in D.O

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1149]
## Problem / Motivation
D.o have really good information about Drupal tools. A informative page is the "Development Tool" page in D.o https://www.drupal.org/node/147789. 

## Solution
I think we should write a descriptive paragraph about Drupal Console and edit this page in D.o.

**Comment by jmolivas** [comment]
Love the idea, we can probably use text from the documentation https://hechoendrupal.gitbooks.io/drupal-console/content/

**Comment by darol100** [comment]
@jmolivas , the text from the link that you provide me does not have a lot good informative information about Drupal Console. The target of this text is not for developer, is mainly for people that are starting into Drupal and they are looking into new tools.

Here are two good examples of command line tools descriptions:

**Drush**
>Drush is one of the most popular, if not the most popular, Drupal development tool out there. Drush is the command line and scripting interface for Drupal. You can use it to speed up installing, developing and maintaining Drupal sites. It takes some getting used to, and there are a lot of commands to remember but, once you do, it is a real time saver. Rather than clicking through the admin interface to achieve something, you simply type in one command. When building Drupal sites and developing custom modules and themes, this can really help.

**Git**
>Git is the modern version control system, and has become the defacto standard for open source projects. You can use it to track changes made to files within your entire Drupal installation, or just the module or theme that you are working on. Git makes it easy to try out changes, and if necessary, revert to a previous version of your files if there is a problem.

**Comment by darol100** [comment]
@jmolivas , I think you mean this https://hechoendrupal.gitbooks.io/drupal-console/content/en/about/what-is-the-drupal-console.html

I like this description. I do not know what I was reading that day.


> The Drupal Console is a suite of tools run from a command line interface (CLI) to generate boilerplate code and interact with a Drupal 8 installation. From the ground up, it has been built to utilize the same modern PHP practices which were introduced in Drupal 8.+

>The Drupal Console makes use of the Symfony Console and other third party components which allows you to automatically generate most of the code needed for a Drupal 8 module. In addition, Drupal Console helps you interact with your Drupal installation.

**Comment by darol100** [comment]
@jmolivas nevermind... seem like you already did. LOL. I will close this issue.
