### ISSUE TITLE
"drupal generate:form:alter" asks for form id, but isn't using it.

### ISSUE THREAD

**Issue by jepster** [hechoendrupal/DrupalConsole#1154]
After "drupal generate:form:alter" asks for the form id. After execution there's no code with this form ID generated.

**Comment by jmolivas** [comment]
@jepster: The form-id is used on at
https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/GeneratorFormAlterCommand.php#L93

**Comment by darol100** [comment]
@jepster , Should we close this issue sine this been solve already ?

**Comment by jmolivas** [comment]
:+1: on close this one

**Comment by jepster** [comment]
Yep, found out how it works.

Jesus Manuel Olivas <notifications@github.com> schrieb am Di., 10. Nov.
2015 22:36:
