### ISSUE TITLE
[module:install] Installing rest modules via DrupalConsole is missing something

### ISSUE THREAD

**Issue by LightGuard** [hechoendrupal/DrupalConsole#1155]
When I enable all the rest modules via drupalconsole then try to post to it use DHC I get a 404 on /entity/node.

I'm using docker, which I don't think is causing the problem, but I'll give you the setup files: https://github.com/LightGuard/drupal8-docker-test

**Comment by LightGuard** [comment]
Looks like rebuilding the routes fixes it.

**Comment by LightGuard** [comment]
I'm not sure if there's any way to determine if routes need to be rebuilt or not on a module install, but it's probably something worth doing every time, just like rebuilding the cache.

**Comment by enzolutions** [comment]
Hi @LightGuard 

Thanks for your report, cache rebuild was included in PR https://github.com/hechoendrupal/DrupalConsole/pull/1163 and will be part of release 0.9.7
