### ISSUE TITLE
ContainerAwareCommand needs a getEntityTypeManager() method

### ISSUE THREAD

**Issue by bojanz** [hechoendrupal/DrupalConsole#1167]
The entity manager has been deprecated and split into 11 different services: https://www.drupal.org/node/2549139
The class that holds the getStorage() method is now the EntityTypeManager.

ContainerAwareCommand should have a getEntityTypeManager() method (core is introducing the same change to ControllerBase, forms, etc) and it should use it instead of getEntityManager().
getEntityManager() should be marked as deprecated.

**Comment by darol100** [comment]
@bojanz , Closing this issue because we have another issue where we have done some of this work. https://github.com/hechoendrupal/DrupalConsole/issues/1875


Also, I have send a PR to fix this issue - https://github.com/hechoendrupal/DrupalConsole/pull/2175

**Comment by darol100** [comment]
Reopening this because this issue was for the Drupal Core and the another one generate code.
