### ISSUE TITLE
Drupal Console doesn't work if the ioncube extension is enabled

### ISSUE THREAD

**Issue by viteksafronov** [hechoendrupal/DrupalConsole#1168]
There is the php extension named ionCube Loader, which is needed to run encoded php files. This extension prevents normal working of any phar files with require/include calls. So you can't run drupal console because it is requiring 'console.php' (you'll get 'not found' error).
ioncube team already knows about the problem and even (maybe) will try to fix it.
The issue is left here to make the problem "googleable".

**Comment by darol100** [comment]
:+1:  Even thought we cant do anything about it because this is an ionCube issue.

**Comment by darol100** [comment]
Closing this issue is been solve at https://github.com/hechoendrupal/drupal-console-book/pull/153

**Comment by RangerGH** [comment]
This is a crying shame.  I know that ionCube has to fix it but unfortunately I need ionCube to run another application so Drupal Console is out of my toolbox.  I'll file a report with ionCube (if I can) and my other application.  Not that it will do much good.  Well, back to drush.
