### ISSUE TITLE
Generated checkAccess() method in MyEntityControlHandler throw error

### ISSUE THREAD

**Issue by twang4turner** [hechoendrupal/DrupalConsole#1176]
I use drupal generate:entity:content to create a Video entity, and one generated class is MyEntityControlHandler with two methods: checkAccess and checkCreateAccess. Without modifying any code, I am able to create and save a video. However, when I tried to access to the video list, it keeps throwing following error:

Fatal error: Call to a member function hasPermission() on a non-object in /Users/twang/Projects/Drupal/dev/local/drupal-8.0.0-rc2/core/lib/Drupal/Core/Access/AccessResult.php on line 108

After I commented out the generated checkAccess method, the error went away and the list was displayed. The problem is that the $account argument is null.

**Comment by smalot** [comment]
Hi,
Di you tried again with Drupal 8.0.0 ?
BR

**Comment by darol100** [comment]
I'm closing this issue due to the lack of active and because I could not replicate this issue. I try this out on 8.0.2 and I did not see that error.

@twang4turner , If you can replicate this issue on a stable Drupal core release please let use know and re-open this issue.
