### ISSUE TITLE
Generation of Install Files

### ISSUE THREAD

**Issue by claymullis** [hechoendrupal/DrupalConsole#1180]
Looking for a way to generate a skeleton module.install file, perhaps even as an option in the initial generation of a module using 'drupal generate:module'. 

For example, I am trying to convert a module from drupal 7 to drupal 8.  The module.install looks like this - https://gist.github.com/claymullis/bfbedebfcccc16799f4e. 

Using drupalmoduleupgrader, I can get that converted pretty quickly to a proper drupal 8 .install file. It would be nice, however, if I could have the base function names generated in a new .install file using drupal console, it would be preferable; as I'm now attempting a rewrite of the module instead of using drupalmoduleupgrader.

**Comment by darol100** [comment]
@claymullis , Couple weeks ago, I open an similar issue to use Drupal Console as an analyzer. Similar to what drupalmoduleupgrader  does. You can check it out at - https://github.com/hechoendrupal/DrupalConsole/issues/1092

**Comment by claymullis** [comment]
Closed as issue #1092 sufficiently covers this use case.
