### ISSUE TITLE
[template] generate:plugin:field - using deprecated classes

### ISSUE THREAD

**Issue by charginghawk** [hechoendrupal/DrupalConsole#1182]
When you use generate:plugin:field, the "use" sections have some deprecated classes.

Drupal v8.0.0-rc3
Drupal Console version 0.9.6

`use Drupal\Component\Utility\SafeMarkup;`
[Deprecation notice](https://api.drupal.org/api/drupal/core!lib!Drupal!Component!Utility!SafeMarkup.php/class/SafeMarkup/8)
[Location in repo](https://github.com/hechoendrupal/DrupalConsole/blob/139912eb3c453af30403e6c68b2d8de621a2cd5f/templates/module/src/Plugin/Field/FieldType/fieldtype.php.twig#L17)

`use Drupal\Core\StringTranslation\TranslationWrapper;`
[Deprecation notice](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!StringTranslation!TranslationWrapper.php/class/TranslationWrapper/8)
[Location in repo](https://github.com/hechoendrupal/DrupalConsole/blob/139912eb3c453af30403e6c68b2d8de621a2cd5f/templates/module/src/Plugin/Field/FieldFormatter/fieldformatter.php.twig#L12)

**Comment by darol100** [comment]
@charginghawk, Pull request are always welcome.

**Comment by enzolutions** [comment]
@charginghawk Thanks for your report , clases were replaced at PR https://github.com/hechoendrupal/DrupalConsole/pull/1311
