### ISSUE TITLE
Error while executing yaml:merge command

### ISSUE THREAD

**Issue by subhojit777** [hechoendrupal/DrupalConsole#1185]
I was syncing translation with the latest commands using `yaml:merge` command, and I was getting this error:

> PHP Fatal error:  Class 'Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand' not found in /Users/subhojit/DrupalConsole/src/Application.php on line 369

I discussed this with @enzolutions, he asked me execute `composer update`, on doing that the error got fixed. Looks like the composer packages are out of date with the new Drupal console code.

**Comment by enzolutions** [comment]
@subhojit777 did you got that problem with latest version 0.9.7?

**Comment by subhojit777** [comment]
No 😄

**Comment by subhojit777** [comment]
I have also raised a PR with the new `composer.lock` 😉

**Comment by enzolutions** [comment]
Please check with 0.9.7 it's normal to run componser update or install if you are working in  a dev version, but that is not possible with release version, please check to confirm it's a problem.

**Comment by subhojit777** [comment]
I meant "no, I am not getting that error" :) Should I try the command on a fresh Drupal Console checkout?

**Comment by enzolutions** [comment]
If running 0.9.7 error is gone, just close this ticket.

Checkout is dev version again is normal among Drupal Console develoepr, if something fail just run componser install to update your dependencies.

**Comment by subhojit777** [comment]
yeah it seems the error is gone :)
