### ISSUE TITLE
attempting to pass drush commands through drupal console removes underscores

### ISSUE THREAD

**Issue by frob** [hechoendrupal/DrupalConsole#1243]
I generated a module with drupal console and everything went well. I then attempted to install that module by running ```drupal drush en module_name``` however drush thought that I was attempting to enable ```modulename`` and not ```module_name```. I then ran the same command and didn't wrap the drush command in drupal console and it ran just fine. Below is the console i/o.

```bash
vagrant@visual-strategies:/var/www/drupal$ drupal drush en visual_strategies_chapter_outline
visualstrategieschapteroutline was not found.                                                                                                                                                                                    [warning]
No release history was found for the requested project (visualstrategieschapteroutline).                                                                                                                                         [error]
vagrant@visual-strategies:/var/www/drupal$ drush en visual_strategies_chapter_outline
The following extensions will be enabled: visual_strategies_chapter_outline
Do you really want to continue? (y/n): y
visual_strategies_chapter_outline was enabled successfully. 
```

**Comment by jmolivas** [comment]
@frob: Thanks for reporting, I will be looking at the issue.

In the meantime you can try installing the module by using drupal console `module:install `
 `drupal module:install module_name`

**Comment by darol100** [comment]
@frob , now with the new aliases you can run ...

`drupal md module_name`

I vote for closing this issue. Does not seem to make sense to support a functionality from another command on something that DrupalConsole already support.

BTW. I was able to replicate this issue on 0.9.9.

I'm closing this issue, @jmolivas feel free to reopen if you still want to fix this issue.

**Comment by frob** [comment]
drupal console is supposed to support passing drush commands. This functionality in drupal console is broken and should be fixed or removed.

**Comment by jmolivas** [comment]
I vote :+1:  on removing the `drush` command, we can bring it back after 1.0.0 stable release if we think it will bring any value to the project.

We added the most common commands to Drupal Console already,  module/theme download and install, site install, remote command execution, database, cache rebuild etc.

For a full list of Drupal Console commands:
https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/available-commands.html

**Comment by frob** [comment]
I would agree with the removal of the drush command. It might make more sense to have a drush sub command that will run drupal console commands. 

Right now we might be able to run: ```drush @site.alias ssh 'drupal generate:something'```

So if we can use drush to create a terminal ssh session and run the drupal console commands. This would also be a separate drush module, so this wouldn't block 1.0.0

**Comment by enzolutions** [comment]
IMHO the bridge we built to provide more option to end user, is not necessary anymore and is really expensive to maintain, so I vote for remove this option in next release.

**Comment by omero** [comment]
I don't think that most of users use `drupal drush` instead `drush` because they have surely installed `drush` in their systems, so :+1:

**Comment by jmolivas** [comment]
@frob: You don't need to use drush aliases for that, you can do remote command execution using DrupalConsole.

Example using a docker container: https://github.com/wadmiraal/docker-drupal#using-drupal-console

Drupal Console docs: https://hechoendrupal.gitbooks.io/drupal-console/content/en/using/how-to-use-drupal-console-in-a-remote-installation.html

**Comment by darol100** [comment]
:+1:  for removing drush from DrupalConsole. However, we probably will need to take a look on what most popular Drush commands we have not support in Drupal Console and try to add those functionalities.

**Comment by jmolivas** [comment]
@darol100 We should add an issue and list those commands to have them identified and marked as we complete them:

- [ ] Command 1
- [ ] Command 2

**Comment by darol100** [comment]
I did few things base on this issue conversation...
- I open an issue to kill `drush` from Drupal Console at #1520 
- Also, I open an meta issue to support `drush` functionality with in side of Drupal Console #1522

BTW, my intent of this issue was to close it, not to kill drush from Drupal Console. When I read all the conversation I felt like ... =)

![anchorman](https://cloud.githubusercontent.com/assets/6808460/11905130/63f5d6a6-a579-11e5-9c31-7a5e1e0d0fc6.jpg)

Anyway, it makes sense why not support the bridge and that is why I open those to issues.

**Comment by frob** [comment]
@jmolivas awesome, thanks. I remember asking that question #1241 and found an answer there as well.

I added a link to the docs and closed that issue.
