### ISSUE TITLE
 "Unable to open /tmp/*tar.gz using mode r+: fopen(*tar.gz)" on use of "drupal site:new 8"

### ISSUE THREAD

**Issue by claymullis** [hechoendrupal/DrupalConsole#1273]
An error of style:

 Unable to open /tmp/drupal.0COilCtar.gz using mode r+: fopen(/tmp/drupal.0COilCtar.gz): failed to open stream: No such file or directory

Occurs whenever trying to install a new drupal installation on a host which doesn't have the php5-curl module enabled.  This error doesn't tell you much about the actual issue at hand (that you're missing a necessary dependency, namely php5-curl).  

A check for the php5-curl module should occur before the command "drupal site:new *" is run.  If the module is not found, it should present a friendly error message about missing php5-curl and how to download and install it.

**Comment by Saphyel** [comment]
this also affects to module:download

**Comment by enzolutions** [comment]
@claymullis did you remember how do you resolved this issue?

**Comment by pektinasen** [comment]
@enzolutions solved it by installing php5-curl:

    sudo apt-get install php5-curl

**Comment by enzolutions** [comment]
Great just installing php5-culr is a nice cathup

```
sudo apt-get install php5-curl
```
