### ISSUE TITLE
drupal:install Doesn't respect existing db connection information if present

### ISSUE THREAD

**Issue by mglaman** [hechoendrupal/DrupalConsole#1275]
I have my own local development runner which predefines connection information to my Docker containers. However, if I run drupal:install within the Drupal directory, it does not read settings.php and prompts me through the configuration process.

It would be great if Console could mimic Drush and read that file first instead of trying to recreate it.

**Comment by enzolutions** [comment]
Fixed in PR https://github.com/hechoendrupal/DrupalConsole/pull/1330

**Comment by jmolivas** [comment]
Is this what you asked for @mglaman ?

**Comment by mglaman** [comment]
Looks like it! I'll try it out tomorrow!

**Comment by enzolutions** [comment]
This is what you get and will be available in next release 0.9.8

<img width="896" alt="console_install_validator" src="https://cloud.githubusercontent.com/assets/907914/11352760/e4413f14-9203-11e5-92e4-da24326c1ab8.png">

**Comment by mglaman** [comment]
@enzolutions amazing. hopefully next time I have an idea I can actually contribute the PR :)

**Comment by jmolivas** [comment]
@mglaman You just need to ping us via an issue or the support channel at: https://gitter.im/hechoendrupal/DrupalConsole and we can guide you on how to contribute with code. 

Because testing and adding issues is a great way to contribute.
