### ISSUE TITLE
[docs] Theme debugging in Drupal.org

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1286]
## Problem/Motivation
Drupal.org have documentation about debugging twig theme at [Debugging compiled Twig templates](https://www.drupal.org/node/1903374). However, this seem like a lot steps to do manually and in theory we should be able to run `drupal site:mode dev`

## Solution

We should verify that everything on that page is supported [Debugging compiled Twig templates](https://www.drupal.org/node/1903374) by `drupal site:mode dev`. I know that debug true is been supported already, in addition @jmolivas confirm it at https://github.com/hechoendrupal/DrupalConsole/issues/1148

````````````````
parameters:
  twig.config:
    debug: true
````````````````````
We need to check if auto_reload, disable cache is also been supported. If not been supported we should open issue couple issues to support it. Here is how it should looks like.

```````
auto_reload: true
cache: false
```````

Last thing we need to check if 
[Drupal Render cache](https://www.drupal.org/node/1903374#drupal-render-cache ) is been support it by  `drupal site:mode dev`

Once we verify that all that is been supported by `drupal site:mode dev` we can added a piece a documentation that mention if you are running Drupal Console run `drupal site:mode dev` and you have debugging enable. 

## Why ? 

We need to start documenting DrupalConsole functionality, and providing solutions to developers so they can use Drupal Console as part of their workflow.

**Comment by jmolivas** [comment]
Those values are switch by `drupal site:mode dev`

```
twig.config: { debug: true, auto_reload: true, cache: false }
```
![drupal-site-mode](https://cloud.githubusercontent.com/assets/366275/11223187/89edca58-8d23-11e5-99fb-bb0a1b5aebbe.png)

Totally agree on the need to to start documenting DrupalConsole functionality

**Comment by darol100** [comment]
@jmolivas, what about the [Drupal Render cache](https://www.drupal.org/node/1903374#drupal-render-cache) ? Its that been supported as well ? If not, should we open an issue for that ?

**Comment by jmolivas** [comment]
@darol100 Drupal Render cache toggle not yet supported, and yes we should open en issue for that.

**Comment by darol100** [comment]
@jmolivas , I created a new issue for the Drupal Render Cache.  #1309

I have also update the documentation in Drupal.org on how to enable debugging with Drupal Console. You can see the [revision in here](https://www.drupal.org/node/1903374/revisions/view/9122064/9128298). 

In addition, I added a disclaimer that Drupal Console does not supported yet "Drupal Render Cache is not been supported by Drupal Console for more information about the status of this implementation please visit - https://github.com/hechoendrupal/DrupalConsole/issues/1309"

**Comment by darol100** [comment]
This issue it was mainly to solve the lack of documentation on the debugging page in Drupal.org. Drupal Render Cache is not technically part of debugging (it just make it faster). That been said, we can close this issue.

For anyone interested on the new section of the Drupal Console in the debugging page visit - https://www.drupal.org/node/1903374#enable-with-drupal-console
