### ISSUE TITLE
[docs] Drupal 8 Console - page outdate

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1288]
## Problem / Motivation
This page seem a little bit outdate, it have not been update since Feb 2015 - https://www.drupal.org/node/2361869. 

## Solution
 - We need to update the installation instructions as well as the available command. 
 - We need to add a disclaimer that said... "Drupal Console is on a very active development, meaning that this page might be outdate by the time you are reading it. For this reason we encourage you to read our [gitbook](https://hechoendrupal.gitbooks.io/drupal-console/content/), which we update more often.  "

I'm not sure but I think the "Project Goals" might have change since Feb 2015, so @jmolivas you probably will have to read those and decide if there are things that needs to be update.

**Comment by darol100** [comment]
I will take care of the first two bullet points.

**Comment by jmolivas** [comment]
Do still have plans to taking care and you need any help on this issue?

**Comment by darol100** [comment]
![screen shot 2015-11-26 at 4 46 15 pm](https://cloud.githubusercontent.com/assets/6808460/11432172/468af524-945d-11e5-96c3-1ad9dae77bec.png)

I have update with the page with the new commands, and I added the disclaimer. Since @jmolivas already edit this and he remove the project goal, I'm assuming that the goals are not longer going to be part of this page for this reason I'm closing this issue.
