### ISSUE TITLE
For contentEntity add also bundles and revisions

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1292]
## Problem/ Motivation

If you want to add bundles and revisions it required you have to do a lot of work.

## Solution 
It will be useful to have an option to add bundles and revisions to content entities.

---
This was original been report by [marcel66](https://www.drupal.org/u/marcel66) at [For contentEntity add also bundles and revisions](https://www.drupal.org/node/2562575)

**Comment by enzolutions** [comment]
Entities bundles was resolved at https://github.com/hechoendrupal/DrupalConsole/pull/1261 could you check with dev version if revision stuff was already cover

**Comment by darol100** [comment]
Closing this issue because this was been solve at #1261
