### ISSUE TITLE
validating entity machine name before generation(32 characters)

### ISSUE THREAD

**Issue by nikathone** [hechoendrupal/DrupalConsole#1303]
I was recently generating a en entity and I did use more than the 32 letters which is of course not allowed. Is there a way to add a validation for this before the generation? Keep the good work.
Thanks

**Comment by jmolivas** [comment]
We can probably add some code to truncate the machine name generation at `StringHelper` class
https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Helper/StringHelper.php#L30

**Comment by enzolutions** [comment]
@nikathone could you check the proposed solution in https://github.com/hechoendrupal/DrupalConsole/pull/1343 to validate if we can close this issue.
