### ISSUE TITLE
[config:import:single] Config importers should use the config importer service

### ISSUE THREAD

**Issue by Jaesin** [hechoendrupal/DrupalConsole#1313]
I notices when trying to import field storage and fields with the console `config:import:single` the DB tables don't get created. There must be some missing steps that aren't getting executed when config is imported so I started looking at the batch for importing config from the UI. 

Relevant code from the form based importer that uses the drupal batch API: 

```
// \Drupal\config\Form\ConfigSingleImportForm::validateForm

      $source_storage = new StorageReplaceDataWrapper($this->configStorage);
      $source_storage->replaceData($config_name, $data);
      $storage_comparer = new StorageComparer(
        $source_storage,
        $this->configStorage,
        $this->configManager
      );

        $config_importer = new ConfigImporter(
          $storage_comparer,
          $this->eventDispatcher,
          $this->configManager,
          $this->lock,
          $this->typedConfigManager,
          $this->moduleHandler,
          $this->moduleInstaller,
          $this->themeHandler,
          $this->getStringTranslation()
        );
// \Drupal\config\Form\ConfigSingleImportForm::submitForm
 $config_importer = $form_state->get('config_importer');
 $sync_steps = $config_importer->initialize();
// Batch Stuff
        foreach ($sync_steps as $sync_step) {
          $batch['operations'][] = [[ConfigSync::class, 'processBatch'], [$config_importer, $sync_step]];
        }
// \Drupal\config\Form\ConfigSync::processBatch
    $config_importer->doSyncStep($sync_step, $context);
```

Repro instructions. 

1. Create a new field on any type of entity.
1. Export config.
1. Import the field storage from the export: `cat sites/default/config/field.storage.node.field_foo.yml | console config:import:single field.storage.node.field_foo`
1. Import the field definition from the export: `cat sites/default/config/field.field.node.page.field_foo.yml | console config:import:single field.field.node.page.field_foo`
1. Try to add content and you will get an error because the field tables do not exist.

**Comment by FatherShawn** [comment]
I just tried to use the config:import:single as follows:
`drupal config:import:single views.settings <my file path>/docroot/core/modules/views/config/install/views.settings.yml` and the command just hung - never returned prompt nor seemed to execute.

**Comment by acbramley** [comment]
I believe this applies to the normal config:import command as well.

It seems like sometimes the field tables are created, but when it's very complex it doesn't. For example, adding the module scheduled_updates and importing the entity type, field, and configuration all at once fails.

**Comment by enzolutions** [comment]
Resolved in https://github.com/hechoendrupal/DrupalConsole/pull/2545
