### ISSUE TITLE
generate:entity:content generates wrong form folder structure for entities

### ISSUE THREAD

**Issue by almare** [hechoendrupal/DrupalConsole#1340]
The default form folder for entities should be modulename/src/Form and not modulename/src/Entity/Form. 

Have a look at the node module for example the class Node here https://api.drupal.org/api/drupal/core!modules!node!src!Entity!Node.php/class/Node/8

**Comment by frega** [comment]
The generator for config entities already use this folder-structure so this only applies to the content entity generator.

**Comment by jmolivas** [comment]
Related PR https://github.com/hechoendrupal/DrupalConsole/pull/1344 by @frega about to get merged.
