### ISSUE TITLE
Errors and notices with examples.settings.local.php 

### ISSUE THREAD

**Issue by krlucas** [hechoendrupal/DrupalConsole#1345]
I'm testing Drupal Console 0.9.8 with a copy of the example.settings.local.php that ships with Drupal 8.0.0.

Drupal Console is throwing fatal errors when it hits this line of settings.local.php:
``\Drupal\Component\Assertion\Handle::register();``

``PHP Fatal error:  Class 'Drupal\Component\Assertion\Handle' not found in XXXXXX/sites/default/settings.local.php on line 13``

Commenting out that line and it *mostly* works but displaying notices when it hits Drupal defined constants like:
``$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/development.services.yml';``

``PHP Notice:  Use of undefined constant DRUPAL_ROOT - assumed 'DRUPAL_ROOT' in XXXXXXXX/sites/default/settings.local.php on line 38
``

Drush and web clients work fine.

**Comment by weaverryan** [comment]
Thanks @jmolivas :)

**Comment by dsteplight** [comment]
I just ran into this and it worked for me too.
