### ISSUE TITLE
New Command: Delete Config Entity

### ISSUE THREAD

**Issue by heddn** [hechoendrupal/DrupalConsole#1366]
Similar to https://gist.github.com/heddn/20f917b49d27bb2208b5

Would definitely need to autocomplete the config entity names.

Suggested command names:
config:delete <= My preference
configuration:delete
yaml:configuration:delete
yaml:delete:configuration

**Comment by jmolivas** [comment]
I :+1: on this one.

**Comment by llwp** [comment]
:+1:  ...actually I would rate this as a little more than nice to have.  in the process of developing modules, they get enabled and uninstalled (née disabled) quite often many multiple times.  a CLI option is practically essential. (do i daresey drush?)  orphaned config needs better management, and this is just one small way to move in that direction.

**Comment by jmolivas** [comment]
@darol100 and myself work on this during SANDCamp, a PR adding this feature is close.

**Comment by darol100** [comment]
It should be ready by tonight or maybe tomorrow night.

**Comment by sshrestha-navarts** [comment]
Is `config:delete` in 0.10.12?

**Comment by jmolivas** [comment]
@sshrestha-navarts:  No is not, will be included on next release 0.10.13
