### ISSUE TITLE
[generate:form:config] Do you want to generate a form structure? - Does not end

### ISSUE THREAD

**Issue by saitanay** [hechoendrupal/DrupalConsole#1382]
On drupal generate:form:config, at "Do you want to generate a form structure?" , when "yes" is chosen, the console continues to ask for more form elements one after another. 

Ending the loop once i have keyed in all the form elements, is either not obvious, or not documented (in drupal-console-en.pdf) , or is missing.

**Comment by darol100** [comment]
@saitanay , What version of DrupalConsole are you running ? I can't replicate this bug in my computer.

<img width="845" alt="screen shot 2015-12-02 at 1 27 19 am" src="https://cloud.githubusercontent.com/assets/6808460/11527147/0d763e84-9894-11e5-8c71-8766838cdd44.png">

**Comment by saitanay** [comment]
Looks like. To stop the flow, i should just give a blank value for "type" and "input label". Couldn't figure that out earlier and it wasn't obvious. 

Thanks for your time. Closing the issue.
