### ISSUE TITLE
[docs] Add instructions on how to build locally

### ISSUE THREAD

**Issue by LightGuard** [hechoendrupal/DrupalConsole#1398]
If I want to use a pre-release version or test something I want to contribute, it would be good to have build instructions. I simply used the travis instructions in the .travis.yml file, but it would be better to have them in the README or CONTRIBUTING guides.

**Comment by darol100** [comment]
@LightGuard 
:+1:  for this feature. I think @jmolivas was working on something like that back in Badcamp. 

The [CONTRIBUTING.md](https://github.com/hechoendrupal/DrupalConsole/blob/master/CONTRIBUTING.md) it was mainly created for the issue queue not for contributing to the project.

I think the [CONTRIBUTING.md](https://github.com/hechoendrupal/DrupalConsole/blob/master/CONTRIBUTING.md)  should have an external url that takes you to a page on how to contribute back to the project.

**Comment by jmolivas** [comment]
@LightGuard We have some instructions about contribution, Project requirements, Getting the project, Running the project, Keeping your fork up to date, etc at the documentation pages: 
https://hechoendrupal.gitbooks.io/drupal-console/content/en/contributing/new-features.html

I am still working on add pages for adding custom commands on contributed modules and commands to DrupalConsole, but I found I needed to remove a dependency and this affects the interactive part of the commands hope to have it ready for 0.9.9 release.

**Comment by jmolivas** [comment]
@LightGuard This is the link you may be looking for https://hechoendrupal.gitbooks.io/drupal-console/content/en/contributing/getting-the-project.html

**Comment by LightGuard** [comment]
That's great, this link should be in the README somewhere. Those coming to the project which would like to help have to dig for that info the first time.

**Comment by darol100** [comment]
@LightGuard  I agree with you. This link should be part of README.

**Comment by fubarhouse** [comment]
Another way could be to simply change the version of Drupal Console after installing as per the default way. It would tie in well after #1408 has been completed, it would also be cleaner and friendlier to most.

**Comment by jmolivas** [comment]
I added some basic instructions o the readme file
https://github.com/hechoendrupal/DrupalConsole#getting-the-project-to-contribute

This can  be improved by adding a link to the docs, any ideas ?

**Comment by isimgt** [comment]
I review the readme document and it's done and as well I added the readme.txt
