### ISSUE TITLE
error after upgrading from 0.9.6 to 0.9.8 Class 'Drupal\Component\Assertion\Handle' not found 

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [hechoendrupal/DrupalConsole#1402]
The error below occurs after the upgrade from 0.9.6 to 0.9.8
The settings.local.php is the default one copied from the sites directory in drupal 8.0.0

$ drupal

PHP Fatal error:  Class 'Drupal\Component\Assertion\Handle' not found in /var/www/html/jhmtest/web/sites/default/settings.local.php on line 31
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/console:3
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/drupal/bin/console.php:87
PHP   5. Drupal\Console\Application->doRun() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:126
PHP   6. Drupal\Console\Helper\DrupalHelper->isValidRoot() phar:///usr/local/bin/drupal/src/Application.php:197
PHP   7. Drupal\Console\Helper\DrupalHelper->isSettingsFile() phar:///usr/local/bin/drupal/src/Helper/DrupalHelper.php:71
PHP   8. include_once() phar:///usr/local/bin/drupal/src/Helper/DrupalHelper.php:94
PHP   9. include() /var/www/html/jhmtest/web/sites/default/settings.php:720

**Comment by jmolivas** [comment]
@jhmnieuwenhuis: Thanks for reporting.

This seems to be a duplicate issue with #1345.

**Comment by jhmnieuwenhuis** [comment]
Ok, Thanks.

Is it possible to install a previous version like 0.9.6 ??

**Comment by jmolivas** [comment]
@jhmnieuwenhuis: Yes you can download the `console.phar` file from:
* Releases page:  
https://github.com/hechoendrupal/DrupalConsole/releases
* Previous release v0.9.7:   
https://github.com/hechoendrupal/DrupalConsole/releases/tag/0.9.7 
* Path to `console.phar`on latest release:  
https://github.com/hechoendrupal/DrupalConsole/releases/download/0.9.7/console.phar

**Comment by jhmnieuwenhuis** [comment]
Excellent !!

Compliments for your support and for your software !!
