### ISSUE TITLE
[generate:help] Hook_help - Stand Alone

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1416]
### Problem/Motivation
`hook_help` can only be use in DrupalConsole if the user needs to generate a new module, using the generate:module. However, we need to be able generate `hook_help` on an existing module without need of generate a module. In addition we should provide more options on writing a descriptive hook_help.

### Solution
- We need to be able to write hook_help on a exiting module.
- The hook_help will be able to add multiples pages.
- For most smaller contrib project hook_help is the same as the README.txt. So I think we should provide the ability of using the README.txt in your hook_help.

**Comment by enzolutions** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2355

Pending define ideas for README.txt and Multiple pages I don't understand the ideas behind that comments.

**Comment by enzolutions** [comment]
@darol100 if no comments, this issue will be marked as resolved
