### ISSUE TITLE
SSL issue when attempting self-update with 0.9.9

### ISSUE THREAD

**Issue by ultimike** [hechoendrupal/DrupalConsole#1443]
Here's the error I get when I try to self-update:

    ~/Sites/drupal8 [8.0.x*]$ drupal --version
    Drupal Console version 0.9.9
    ~/Sites/drupal8 [8.0.x*]$ drupal self-update
                                                                                    
      [Humbug\SelfUpdate\Exception\HttpRequestException]                                 
      file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:     
      error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed  
    
    self-update
    
    ~/Sites/drupal8 [8.0.x*]$

-mike

**Comment by jmolivas** [comment]
@ultimike: This is fixed with #1488.

**Comment by HaleFx** [comment]
I'm getting a different but related error now...

> sudo drupal self-update
> 
> [Humbug\SelfUpdate\Exception\HttpRequestException]
> file_get_contents(): Peer certificate CN=`*.s3.amazonaws.com' did not match expected CN=`github.com'

**Comment by jmolivas** [comment]
@HaleFx: This was fixed on v0.9.10 

Since `self-update` command is not working you will need to use the installer instead:

```
# Run this in your terminal to get the latest Console version:
curl http://drupalconsole.com/installer -L -o drupal.phar

# Or if you don't have curl:
php -r "readfile('http://drupalconsole.com/installer');" > drupal.phar

# Accessing from anywhere on your system:
mv drupal.phar /usr/local/bin/drupal
```

**Comment by HaleFx** [comment]
Thank you, @jmolivas !

**Comment by jmolivas** [comment]
Welcome, you may try run `self-update` after installing v0.9.10 to confirm error message is no longer appearing.

**Comment by HaleFx** [comment]
Yep, that fixed it.

> $ sudo drupal self-update
> Checking for updates from version: 0.9.10
> The latest version 0.9.10, was already installed on your system.

**Comment by ultimike** [comment]
Hmmm - I just did a reinstall using:

    curl http://drupalconsole.com/installer -L -o drupal.phar

Then I tried running the self-update again:

    ~/Sites $ drupal self-update
     Checking for updates from version: 0.9.10
                                             
      [RuntimeException]                                                   
      Failed to download manifest: http://drupalconsole.com/manifest.json  
                                                                           
    self-update [--major] [--manifest MANIFEST] [--current-version CURRENT-VERSION]

-mike

**Comment by jmolivas** [comment]
@ultimike:  We just update the site to use SSL and we are forcing all of the traffic to use `https` this maybe causing an issue.

**Comment by jmolivas** [comment]
@ultimike: we change the settings on the site, and skip forcing on redirect to `https` on URL `http://drupalconsole.com/manifest.json` may you confirm if this fix your issue with `self-update` command.

**Comment by ultimike** [comment]
Yep, that fixed it - thanks!

-mike

**Comment by jmolivas** [comment]
Yay glad to read that.
