### ISSUE TITLE
[site:install] mysql password is mandatory

### ISSUE THREAD

**Issue by nahuelthc** [hechoendrupal/DrupalConsole#1457]
When you run a $drupal site:install, MySQL password is mandatory, then if you have a localhost with no password, the install process get stuck in this step.

![console](https://cloud.githubusercontent.com/assets/9991536/11762502/977827ec-a0c7-11e5-8268-b23a5af97ce1.png)

**Comment by nahuelthc** [comment]
![prefix2](https://cloud.githubusercontent.com/assets/9991536/11762715/edc0616c-a0ce-11e5-98ce-3bb9630203df.png)
it also happens with db prefixed. Env info:
Aquia dev desktop 2 stack rev: 58529
php 5.5.27
MySQL Server version: 5.5.42-37.1-log - Source distribution

**Comment by luissanuy** [comment]
This happens in all lines with empty values.
![image](https://cloud.githubusercontent.com/assets/16269180/11762951/a5b83b80-a0d6-11e5-8250-78050f683b3a.png)

**Comment by darol100** [comment]
@jmolivas , looking at the source code [InstallCommand.php](https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Site/InstallCommand.php)

All these things are optional in the code:

<img width="500" alt="screen shot 2015-12-12 at 9 02 49 am" src="https://cloud.githubusercontent.com/assets/6808460/11763024/371964c8-a0af-11e5-99a3-ec759da363df.png">

Do you think this is affecting some place else ? Or Maybe this is the wrong file ?

**Comment by jmolivas** [comment]
@darol100 Seems like this issue is related to the interaction when asking for the value, bacause the definition of `db-pass` is set as `VALUE_OPTIONAL`.

**Comment by jmolivas** [comment]
@nahuelthc I am taking a look at this.

**Comment by jmolivas** [comment]
@luissanuy: The command you ran was the `generate:form` ?

**Comment by luissanuy** [comment]
Yep. True

**Comment by jmolivas** [comment]
@luissanuy: I will fix that command adding another issue and PR.

**Comment by jmolivas** [comment]
@nahuelthc: Same for the Database Prefix, that will be fixed on this issue https://github.com/hechoendrupal/DrupalConsole/issues/1447
