### ISSUE TITLE
[site:install] Recoverable fatal error.

### ISSUE THREAD

**Issue by ericmaster** [hechoendrupal/DrupalConsole#1458]
After attempting install the Standard profile through command line I'm getting the following error

`Recoverable fatal error: Argument 1 passed to Drupal\Core\Database\Driver\mysql\Install\Tasks::getFormOptions() must be of the type array, null given, called in .../core/lib/Drupal/Core/Installer/Form/SiteSettingsForm.php on line 112 and defined in .../core/lib/Drupal/Core/Database/Driver/mysql/Install/Tasks.php on line 136`

`php --version
PHP 5.6.7-1 (cli) (built: Mar 24 2015 13:43:55) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies`

**Comment by jmolivas** [comment]
I can not replicate this.

**Comment by jmolivas** [comment]
DO you mind to share which, Drupal, Drupal Console and OS versions are you using?

**Comment by enzolutions** [comment]
He tried Drupal 8.0.1 and Drupal Console 0.9.7 I don't remember linux version could you clarify this @ericmaster

**Comment by darol100** [comment]
Closing this issue since is been commited already. Feel free to reopen if this still applys.
