### ISSUE TITLE
[generate:entity:content]  \Drupal:l() is deprecated.

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/DrupalConsole#1465]
\Drupal:l() is deprecated. 
In code I scaffold I would like to avoid this global function call.
The generator command is good .... so I want to fix the issue at source.

I will post a patch soon.

**Comment by darol100** [comment]
See more about the deprecation at -https://api.drupal.org/api/drupal/core%21lib%21Drupal.php/function/Drupal%3A%3Al/8

**Comment by martinfrances107** [comment]
I have made the changes in the commit above ... Sorry I don't use github frequently .....would it be better  to  produce a pull request?

**Comment by darol100** [comment]
I create the PR for you - https://github.com/hechoendrupal/DrupalConsole/pull/1471. In addition, I search for `\Drupal::l` in the DrupalConsole project and here is the only part where we are using it.

**Comment by martinfrances107** [comment]
@darol100 thank you.

**Comment by jmolivas** [comment]
PR #1471 merged
