### ISSUE TITLE
help text misdirects re name of executable

### ISSUE THREAD

**Issue by simesy** [hechoendrupal/DrupalConsole#1478]
1. Install with composer
2. Type: console
3. Get examples like "drupal list"
4. Type: drupal list
5. Get "drupal: command not found"

If you want to suggest the desired fix for this I'll do a PR.

**Comment by jmolivas** [comment]
@simesy: Where is this happening ?

**Comment by simesy** [comment]
Everything is working correctly - it's just that composer results in an executable called `console` -- `console list` works, it's just that the help text suggests to use `drupal list` which I guess is the correct command if you install console the using the website instructions.

**Comment by simesy** [comment]
The help text is hardcoded in src/Command/AboutCommand.php

**Comment by jmolivas** [comment]
We have been discussing to rename the executable to avoid this issues and use one name `drupal` in this case.

**Comment by simesy** [comment]
That feels like a good solution.

**Comment by jmolivas** [comment]
We update phar file from `console.phar` to `drupal.phar` and update the installer instruction on the latest v0.9.9 release, we may update the `bin/console` to `bin/drupal` for the v0.9.10 release.

**Comment by jmolivas** [comment]
This must be fixed with https://github.com/hechoendrupal/DrupalConsole/pull/1499 since executable was updated from `console` to `drupal`

**Comment by jmolivas** [comment]
This will be reflected when using composer the next release.
