### ISSUE TITLE
[generate:content:entity] error creating form files and form files folder

### ISSUE THREAD

**Issue by yeomi** [hechoendrupal/DrupalConsole#1489]
Version 0.9.9

Hello, 
When using generate:content:entity the files architecture I am getting for an entity called "MyEntity" is like : 
```
- src/ 
  -  Entity/ ...
  -  FormMyEntityForm.php
   - FormMyEntityDeleteForm.php
   - FormMyEntitySettingsForm.php
```
when I think it should be :
```
- src/ 
  -  Entity/ 
      - Form/ 
           - MyEntityForm.php
           - MyEntityDeleteForm.php
           - MyEntitySettingsForm.php
       - ...
```
Namespaces and class usage reflect the situation above so for the moment without doing manually changes entity form handlers are not detected.

Thanks.

**Comment by proxiss** [comment]
Should be fixed now:

https://github.com/hechoendrupal/DrupalConsole/issues/1446#event-491536542

**Comment by yeomi** [comment]
Thanks !
