### ISSUE TITLE
[generate:entity:content] Error in adding a Entity

### ISSUE THREAD

**Issue by NateAGeek** [hechoendrupal/DrupalConsole#1496]
The issue seems to be after creating an entity type. Adding an entity creates this error, halting the entity creation. 

Uncaught PHP Exception Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException: "The "{entity_name}" entity type did not specify a "default" form class." at docroot/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 182

**Comment by NateAGeek** [comment]
Related To: #1495,
Missing proper namespace and file location.

**Comment by darol100** [comment]
I'm closing this issue, since is a duplicated. We can solve it at #1495
