### ISSUE TITLE
Lets kill the bridge between Drupal Console and Drush

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1520]
### Problem / Motivation

There seem to be some bugs when using Drush inside of DrupalConsole. For instance #1243 , which does not make sense to take care of this issue while Drupal Console support some of this functionality.

From @enzolutions 
> the bridge we built to provide more option to end user, is not necessary anymore and is really expensive to maintain, so I vote for remove this option in next release.

### Solution
Remove the `drush` command from Drupal Console

**Comment by jmolivas** [comment]
Fixed with #1529

**Comment by greg-1-anderson** [comment]
This is a positive move. I still hope at some point to use common libraries between Drupal Console and Drush; that would be the right way to collaborate and minimize maintenance.  I recognize that the architectures of these two projects makes that non-trivial, but I believe we can make some progress in the near future.
