### ISSUE TITLE
Add Fun Facts section to documentation

### ISSUE THREAD

**Issue by willwh** [hechoendrupal/DrupalConsole#1521]
It would be really nice if we could have a section in that documentation to allow for adding contributing user info.

Example:

```
@jmolivas: actually we can blame eojthebrave for the site:mode command
@jmolivas: https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/site-mode.html
```
We can merge whit this as well
```
Joe aka eojthebrave told us at DrupalCon Bogota 2015, about the lullabot `devify` command https://github.com/Lullabot/drupal-boilerplate/tree/master/drush#devify
and then `site:mode` was born
```

```
@jmolivas: Larry aka Crell told us (David Flores and mysel) someone should bring the `symfony/console` component at DrupalCamp Costa Rica 2013
```

It would be great to this kind of info in the documentation somewhere!

**Comment by darol100** [comment]
@willwh , Feel free to write a markdown page. I guess we can added some place at in the [Gitbook](https://hechoendrupal.gitbooks.io/drupal-console/). IMO, I think you probably need to have more "fun facts" that just only two. Otherwise does not makes sense to have an entire page for this.

**Comment by darol100** [comment]
I'm closing this issue since this is not relate to project.
