### ISSUE TITLE
Implement DrupalStyle Class

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#1542]
### Problem/Motivation
Standardize the output of commands.

The Symfony project released the Console Style Guide 
http://symfony.com/blog/new-in-symfony-2-8-console-style-guide

Drupal Console extends this class as `DrupalStyle`.

#### Add use keyword to Command Class
```
use Drupal\Console\Style\DrupalStyle;
```

#### Create new `DrupalStyle` instance.
Instantiating the `DrupalStyle` class as `$io`, passing the `$input` and `$output` of your command:
````
$io = new DrupalStyle($input, $output);
````

#### Replace `info` tags:

original | Replace 
------------ | ------------- 
`$output->writeln('<info>text</info>');` | `$io->info('text');` 

####  Replace `comment` tags:

| Original | Replace | 
| ------------ | ------------- |
| `$output->writeln('<comment>text</comment>');` | `$io->comment('text');` |

####  Replace `error` tags:

| Original | Replace | 
| ------------ | ------------- |
| `$output->writeln('<error>text</error>');` | `$io->error('text');` |

#### Update `success` messages:
```
$io->success('text');
```

#### Replace tables:
Original
```
use Symfony\Component\Console\Helper\Table;

$table = new Table($output);
$table->setStyle('compact');
$table->setHeaders([]);

foreach () {
  $table->addRow([]);
}

$table->render();
```
Replace:
```
$tableHeader = [];

$tableRows = [];
foreach () {
  $tableRows[] = [];
}

$io->table($tableHeader, $tableRows, 'compact');
```
> NOTE: Remove use  keyword `use Symfony\Component\Console\Helper\Table;`

### Command Namespaces status:
- [x] Config (@mnico)
- [x] Database (@jmolivas)
- [x] Develop (@jmolivas)
- [x] Exclude (@jmolivas)
- [x] **Generate** _If you are planning to work on this make sure to select one command at the time and add a comment on this issue with the command you are working on to avoid duplicated work._
  - [x] AuthenticationProviderCommand.php (@enzolutions)
  - [x] CommandCommand.php (@enzolutions)
  - [x] ConfigFormBaseCommand.php (@enzolutions)
  - [x] ControllerCommand.php (@enzolutions)
  - [x] EntityBundleCommand.php (@mnico)
  - [x] EntityCommand.php (@mnico)
  - [x] EntityConfigCommand.php (@mnico)
  - [x] EntityContentCommand.php (@mnico)
  - [x] EventSubscriberCommand.php  (@enzolutions)
  - [x] FormAlterCommand.php (@enzolutions)
  - [x] FormBaseCommand.php (@enzolutions)
  - [x] FormCommand.php (@enzolutions)
  - [x] ModuleCommand.php (@enzolutions)
  - [x] PermissionCommand.php (@enzolutions)
  - [x] PluginBlockCommand.php (@enzolutions)
  - [x] PluginConditionCommand.php (@enzolutions)
  - [x] PluginFieldCommand.php (@enzolutions)
  - [x] PluginFieldFormatterCommand.php (@enzolutions)
  - [x] PluginFieldTypeCommand.php (@enzolutions)
  - [x] PluginFieldWidgetCommand.php (@enzolutions)
  - [x] PluginImageEffectCommand.php (@enzolutions)
  - [x] PluginImageFormatterCommand.php (@enzolutions)
  - [x] PluginRestResourceCommand.php (@enzolutions)
  - [x] PluginRulesActionCommand.php (@enzolutions)
  - [x] PluginTypeAnnotationCommand.php (@enzolutions)
  - [x] PluginTypeYamlCommand.php (@enzolutions)
  - [x] PluginViewsFieldCommand.php (@enzolutions)
  - [x] ProfileCommand.php (@enzolutions)
  - [x] RouteSubscriberCommand.php (@enzolutions)
  - [x] ServiceCommand.php (@enzolutions)
  - [x] ThemeCommand.php (@enzolutions)
- [x] Locale (@omero)
- [x] Migrate (@omero)
- [x] Module (@omero)
- [x] Multisite (@jmolivas)
- [x] Rest (@omero)
- [x] Router (@jmolivas)
- [x] Self (@jmolivas)
- [x] Site (@jmolivas)
- [x] State (@jmolivas)
- [x] Test (@omero)
- [x] Theme (@mnico)
- [x] Update (@mnico)
- [x] User  (@mnico)
- [x] Views (@omero)
- [x] Yaml (@mnico)

Please add a comment if you are planning to work on a namespace.

### UPDATE:
The first block of namespaces is completed. Thanks @omero & @mnico for the great work and the PRs.

The missing one is the one with the most number of classes the `Generator` namespace.

If you are planning to work on this make sure to select one command at the time and add a comment on this issue with the command you are working on to avoid duplicated work.

**Comment by jmolivas** [comment]
I will take care of `State` namespace.

**Comment by mnico** [comment]
I will take care of ```Theme ``` namespace.
I have a doubt, this line:
```php
            $output->writeln(
                '[+] <info>text</info>'
            );
```
It must be replaced by
```php
            $io->write('[+]');
            $io->info('text');
```
this?

**Comment by omero** [comment]
just `$io->info('text');` @mnico

**Comment by jmolivas** [comment]
@mnico: We are removing the `-` `+` character.

**Comment by jmolivas** [comment]
@mnico & @omero if you do not want to skip to a new line like using `write` instead of `writeln` you can use: 
```
 $io->info('text', false);
 $io->comment('text', false);
```

**Comment by jmolivas** [comment]
State namespace fixed with PR #1543

**Comment by mnico** [comment]
```Theme``` done
Now i will take care of ```Update``` namespace.

**Comment by omero** [comment]
I will take `module` and `rest` namespace

**Comment by mnico** [comment]
```Update``` done
Now i will take care of ```User``` namespace.

**Comment by omero** [comment]
i will take `test` and `view` namespaces

**Comment by mnico** [comment]
I will take care of ```Yaml``` namespace.

**Comment by mnico** [comment]
I will take care of ```Config``` namespace.

**Comment by omero** [comment]
I will take `locale` and `migrate` namspaces

**Comment by mnico** [comment]
```Yaml``` and ```Config``` commands are finished

**Comment by jmolivas** [comment]
Thanks @omero & @mnico for the great help and PRs. The first block of namespace is completed.

The missing one is the one with the most number of classes the `Generator.

If planning to work on this make sure you select one command at the time and comment the command you are working on to avoid duplicated work.

**Comment by enzolutions** [comment]
Workiing in Generator/ThemeCommand.php

**Comment by mnico** [comment]
Hi, I will take ```EntityCommand```

**Comment by jmolivas** [comment]
Thanks for the great work here @mnico @omero & @enzolutions I sent a PR https://github.com/hechoendrupal/DrupalConsole/pull/1697 fixing some missing code changes.
