### ISSUE TITLE
[module:install] [feature-request] auto-install module's dependencies 

### ISSUE THREAD

**Issue by vincenzodibiaggio** [hechoendrupal/DrupalConsole#1580]

**Comment by vincenzodibiaggio** [comment]
I can work on this if other people need it

**Comment by jmolivas** [comment]
Fixing an issue I found
> Recoverable fatal error: Argument 1 passed to Drupal\Core\ProxyClass\Extension\ModuleInstaller::install() must be of the type array, null given, called in /Users/jmolivas/develop/drupal/modules/console/src/Command/Module/InstallCommand.php on line 134 and defined in Drupal\Core\ProxyClass\Extension\ModuleInstaller->install() (line 85 of /Users/jmolivas/develop/drupal/sites/drupal.dev/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php).

I realize about this as well and fixed on this PR #1592.

**Comment by vincenzodibiaggio** [comment]
:+1:

**Comment by LightGuard** [comment]
I'd love to see this too, or at the very least an option to pass to have dependencies installed

**Comment by jmolivas** [comment]
This is fixed now. if you try to install modules with dependencies it asks you to install.

What is missing is a way to download the missing dependencies, is this what you are asking for  @LightGuard @vincenzodibiaggio?

**Comment by LightGuard** [comment]
Partly. If the modules are already downloaded you don't need to download them again, obviously simply install them. 

My use case is doing this in essentially a headless install, it is actually a docker setup where drupal console runs as part of starting up or building the container. I don't have the option of answering questions. IMO any question you're asked on the console should have a flag you can specify when you run the command if you are running without interaction capabilities.

**Comment by jmolivas** [comment]
@LightGuard: You can easily create a yml file including any command plus options & arguments
- https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/chain/quick-start.yml
- https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/chain/sample.yml

And use the `chain` command to call that file definition.

More information about this feature:
- https://hechoendrupal.gitbooks.io/drupal-console/content/en/using/how-to-download-install-and-serve-drupal8.html
- http://jmolivas.com/download-install-serve-drupal8-using-one-command

If you are not sure about what option to use on the chain definition you can execute a command and pass the `--generate-chain` option.
![drupal-console-generate-chain](https://cloud.githubusercontent.com/assets/366275/12099543/05bf9bea-b2de-11e5-9679-0ad73f67afd1.png)

**Comment by jmolivas** [comment]
@LightGuard I will take a look at the download module dependencies when installing modules, since I think will be a useful feature to have.

**Comment by LightGuard** [comment]
Fair enough. I have an issue that's somewhat related to this:

    drupal module:install hal rest serialization

asks to install dependencies, but you are installing them in the same go. This used to work in 0.9.9 but changed sometime between that and current.
