### ISSUE TITLE
[server] I am getting 404 on some drupal's internal urls

### ISSUE THREAD

**Issue by AchillesKal** [hechoendrupal/DrupalConsole#1614]
I am using the command "drupal: server" everything works great except some drupal's internal urls return 404 Not Found, status code. 

For example the path: "/admin/structure/types/manage/article/fields/node.article.body"
returns 404. And I have a fresh drupal 8 installation.

I think this have something to do with the dots on the url, the paths with the dots are those who break.

I am using drupal 8.0.1
Drupal Console 0.10.1

**Comment by soncco** [comment]
I have the same problem, only occurs when I create a new field or when I want to edit the field. However if I use nginx or apache to serve, this works.
