### ISSUE TITLE
Drupal console not working. Parse error.

### ISSUE THREAD

**Issue by lovelyhomie** [hechoendrupal/DrupalConsole#1625]
Just installed Drupal Console on my mac according to your installation commands (https://github.com/hechoendrupal/DrupalConsole#installing-drupal-console) on the and it does not work. 

I am getting a Parse error:

```
Parse error: parse error, expecting ')'' in phar:///usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php on line 48
```

What is the problem here?

**Comment by eleaga** [comment]
Can you open the file "usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php" and past the line 48 here?

**Comment by henryosim** [comment]
i have this same issue but when trying to open the file 
'nano usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php ' gives me an empty file.

**Comment by lovelyhomie** [comment]
+1 on henryosim:
I have an empty file as well

**Comment by seanr** [comment]
You’re missing a leading slash - should be this:




nano /usr/local/bin/drupal/src/Command/Theme/UninstallCommand.php


—



Sean Robertson

Senior Developer

DOOR3 Business Applications, Inc.

22 Cortlandt Street, 11th Floor

New York, NY 10007

www.door3.com




212-673-1818 ext. 215

646-912-6720

757-201-4750 (Mobile)

**Comment by lovelyhomie** [comment]
Nope, still nothing.

**Comment by henryosim** [comment]
+1 on lovelyhomie:
same here.

**Comment by jmolivas** [comment]
@lovelyhomie: do you mind to share which OS are you using, PHP and DrupalConsole version ?

**Comment by lovelyhomie** [comment]
Certainly.

**OS:**
Mac OS X 10.9.5

**PHP:**
PHP 5.4.45 (cli) (built: Sep  6 2015 20:56:23)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies


**DrupalConsole version:**
Version info unavailable due to that parse error. All I know is it is the latest I was able to download thru that curl command on the install guide.

**Comment by jmolivas** [comment]
@lovelyhomie: This error is related to the PHP version:
* DrupalConsole requires php >= 5.5.9  
  https://github.com/hechoendrupal/DrupalConsole/blob/master/composer.json#L39
* Same as Drupal 8  
  https://github.com/drupal/drupal/blob/8.0.x/core/composer.json#L7

**Comment by lovelyhomie** [comment]
Ah I see. Well best if you write that requirement onto the main page: https://github.com/hechoendrupal/DrupalConsole before the next one runs into the same problem :)
