### ISSUE TITLE
Generate Controller do not show the parameters correctly

### ISSUE THREAD

**Issue by eleaga** [hechoendrupal/DrupalConsole#1626]
When using "drupal generate:controller" the result is:
Implement method: index with parameter(s): $name

And should be:
Implement method: index with parameter(s): param1

![bug dc](https://cloud.githubusercontent.com/assets/3207946/12089330/cca2ea14-b2ca-11e5-870d-7780f2e86b9b.png)

**Comment by jmolivas** [comment]
FIxed with #1627
