### ISSUE TITLE
Extending command set by modules

### ISSUE THREAD

**Issue by jurgenhaas** [hechoendrupal/DrupalConsole#1649]
Are you planning a framework to allow Drupal modules to add their own commands to DrupalConsole? Similar to the hook_drush_command for Drush it would be great if it were possible to have some sort of plugin mechanism that allowed to define extra commands that are only relevant if certain modules were installed.

**Comment by jmolivas** [comment]
@jurgenhaas: This is doe already you need to create a new command class and we provide a the `generate:command` command for that.

### How to use it:
```
$ drupal generate:command
```

**Comment by jmolivas** [comment]
@jurgenhaas: If you like to see examples about other modules implementing custom commands you can take a look to: WebProfiler, MetaTag and Commerce.

**Comment by jurgenhaas** [comment]
Thanks a lot @jmolivas and sorry that i missed that. I'm planning to deeply integrate console with Drd, a long standing dashboards top monitor and manage remote Drupal sites. Exciting times.

**Comment by jmolivas** [comment]
@jurgenhaas: make sure you ping me for any questions or help, I will be more than glad to help you on the integration.
