### ISSUE TITLE
[generate:theme:fields] Adding fields to theme settings.

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1661]
## Problem / Motivation
Themes often require some extra fields that will be use in other places like a front page image. Or a message that is not necessary the title.

## Solution
 - We need to ability of generating fields for the themes at `admin/appearance/settings/THEMENAME`
 - We should ask which type of preprocess field is going to be use so we can add the ability of picking where the field will be available (if there is an easier way that is avoiding preprocess functions let me know.)

**Resource** here is kinda an example of at [ThemeSettingsForm](https://api.drupal.org/api/drupal/core%21modules%21system%21src%21Form%21ThemeSettingsForm.php/class/ThemeSettingsForm/8), which is where the code lives for the logo and favicon.

**Comment by enzolutions** [comment]
Hello @darol100 

Your request is too specific, that is something dont' not everybody will use or require. If you want to this I recommend an article I wrote that explain to you how you can accompllish that using a convination of Drupal Console commands http://enzolutions.com/articles/2016/02/01/form-altering-will-not-be-the-same-in-drupal-8-after-using-webprofiler/

Please check and close this issue, please/

**Comment by darol100** [comment]
> Your request is too specific, that is something dont' not everybody will use or require.

Maybe not everybody but I think a lot people will be doing something similar. I have work on many themes that require specify files from the front page and this might be easier way to solve this issue by adding custom fields in the theme.

>  If you want to this I recommend an article I wrote that explain to you how you can accompllish that using a convination of Drupal Console commands

However, base on your article it seem like this can be already done by alter the theme_setting form.

Before close this issue can this command...

```
$ drupal generate:form:alter  --module="testing" --inputs="name:name type:textfield label:Name options: description: maxlength:64 size:64 default_value: weight:0" --no-interaction
```
Can be run in a theme ?

**Comment by enzolutions** [comment]
I don't think so, due the theme hook form alter is part of .module files, I we don't have te template.php file anymore.

**Comment by darol100** [comment]
You can run hook_form_alter in `.theme ` which is been supported by a theme. You can see an example of that at http://cgit.drupalcode.org/casper/tree/casper.theme?h=8.x-1.x Casper is a theme that I'm currently working on, and it runs fine.

**Comment by enzolutions** [comment]
uhhh them mean, we need to enable the form alter to allow themes and modules, can you close this issue and create a new one, please

**Comment by darol100** [comment]
Will that issue be a duplicate of #1717 or is a different issue ?

**Comment by enzolutions** [comment]
Is different , maybe related.

**Comment by darol100** [comment]
I have open #1864. Closing this issue.
