### ISSUE TITLE
Determine if Drupal Console violates the GPL.

### ISSUE THREAD

**Issue by klausi** [hechoendrupal/DrupalConsole#1672]
Drupal Console is MIT licensed, not sure that is allowed: https://www.drupal.org/about/licensing#q7

The question is if Drupal console is a derivative work in the same sense a Drupal module is. The safe way would be to change the license to GPLv2+.

We should probably ask the Drupal licensing group about this: https://www.drupal.org/governance/licensing-working-group

**Comment by stevepurkiss** [comment]
It would be nice, but AFAIK Drupal Console doesn't require Drupal code in order to do anything, therefore is not a derivative work. It's not of much use without it, perhaps best thought of as a restricted functionality Ansible - a tool closely tied with but not a derivative. 

my 2p.

**Comment by fubhy** [comment]
It actually DOES use Drupal code in some sense. ContainerAware commands at least are interacting with the services directly. So in some sense, yes it does use Drupal code. It's not like it's speaking to these services over some sort of API. That said, I have no clue if that is actually against the rules.

**Comment by stevepurkiss** [comment]
"Interacting with" could fall under AGPL, so perhaps it only violates the GPL if you use it on the same machine as the Drupal instance you're controlling ;)

**Comment by Crell** [comment]
The usual litmus test I use is whether it's using GPL-licensed code, ie, making function calls to it and receiving data structures back from it.  I don't know enough about the guts of Console to say if that's the case.

**Comment by fubhy** [comment]
In that case... Yes.

It is making function calls to it. It's directly using services from within Drupal.

**Comment by klausi** [comment]
Agreed, if you look at the cron command for example: https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Cron/ExecuteCommand.php

It uses the module handler and invokes hooks in other Drupal modules (why on earth does it not just invoke the cron service? Also 0 docs there why). So it really is on the same level as a Drupal module, which means Drupal console must be licensed under GPLv2+.

Not sure how you can change the license on a project that has 118 contributors ... but since the project violated the GPL probably from the early stages already it has to be changed anyway.

IANAL, but maybe we should not overthink this and just switch to GPL.

**Comment by jmolivas** [comment]
Changing license is not an issue for us. 

I am not an expert on the topic and need to figurate what is the process to change this or as mentioned by @klausi just switch to GPL.

**Comment by Crell** [comment]
MIT -> GPL is actually safe to do without any further input, legally.  It's probably prudent to put out a call to see if anyone objects, but legally the project lead can do so unilaterally.

IANAL TINLA, ETC.

**Comment by jmolivas** [comment]
PR with license change sent https://github.com/hechoendrupal/DrupalConsole/pull/1677 

What will be a recommendation as a good way of notifying contributors about this license change?

**Comment by Crell** [comment]
I'd ping Lukas Smith.  He's been through that process a couple of times and can probably offer some good war stories. :smile:

**Comment by jygastaud** [comment]
@jmolivas : You may be interested to read about that issue: https://github.com/spf13/hugo/issues/201

**Comment by develCuy** [comment]
Did you guys ever read the licensing faq? https://www.drupal.org/about/licensing

Answer from https://www.drupal.org/about/licensing#q14

"14. I found a module or theme in the contributions repository that says it's available under a different license than the GPL (including the LGPL or AGPL). What should I do?

Please file an issue in the Licensing Working Group issue queue and we will look into the matter."

@klausi, now you know what the next step is.

**Comment by klausi** [comment]
@Crell has already responded here, so that step is already done. We have established that the project must switch to GPL. The next step is to review the PR by @jmolivas .

**Comment by enzolutions** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/1677 looks ok for me

**Comment by darol100** [comment]
@enzolutions , PR #1677 just remove the MIT content from the license, instead of replacing it with GPL Do you think we should have the GPL info in the license file ?

**Comment by jmolivas** [comment]
@darol100 Seems like no need to add the License file, I did check other drupal projects.

**Comment by Crell** [comment]
Drupal.org-hosted projects do not have the LICENSE.txt file in the repo because we add it as part of packaging.  That's not the case for a GitHub-distributed application like Console.  I would recommend including the GPL text in a LICENSE file.

**Comment by darol100** [comment]
[DrupalConsole](https://www.drupal.org/project/console/) is been mirror back to Drupal.org. So something to consider is never creating release on  Drupal.org otherwise it might conflict with the LICENSE.txt file from Drupal.org. 

:+1:  To add LICENSE.txt file.

**Comment by jmolivas** [comment]
@darol100: I did merge your PR, GPL `LICENSE.txt` file added https://github.com/jmolivas/DrupalAppConsole/blob/1672-re-license-project/LICENSE.txt
