### ISSUE TITLE
Errors when run with ioncube loader extension

### ISSUE THREAD

**Issue by rocketeerbkw** [hechoendrupal/DrupalConsole#1695]
I got the following error while trying to run the console:

    Fatal error: require(): Failed opening required 'drupal.php' (include_path='.:/opt/php55/lib/php') in phar:///home/multimed/bin/drupal/bin/drupal on line 3

After quite a bit of googling I came across a similar problem in composer (https://github.com/composer/composer/issues/395) and silex (https://github.com/silexphp/Silex/pull/104/files).

For some reason the ioncube loader messes up phar files. Disabling the extension fixed the problem with drupal console.

The weird thing is that I didn't have any problems running composer.phar with the extension loaded. Maybe there's something else they did to fix the problem?

I wanted to add this issue so others can find it. The iocube loader extension is often loaded on cpanel/whm type hosting environments.

**Comment by jmolivas** [comment]
@rocketeerbkw: Thanks for reporting this. we had a similar issue before https://github.com/hechoendrupal/DrupalConsole/issues/1168

Like the idea of having documented.

We can probably add a section to the documentation for this type of errors and identifying them as 3rd party library errors or somethigng that make more sense.

**Comment by rocketeerbkw** [comment]
Maybe in the installation problems section? https://hechoendrupal.gitbooks.io/drupal-console/content/en/drupal_console_faq/installation-problems.html

**Comment by jmolivas** [comment]
:+1: Make sense then to add it at this mardkdown file:
https://github.com/hechoendrupal/drupal-console-book/blob/master/en/drupal_console_faq/installation-problems.md

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/drupal-console-book/pull/153 on the gitbook/documerntation repository.

**Comment by ropic** [comment]
I'm using plesk, i think is not a solution to disable the extension
