### ISSUE TITLE
[*:install] Download project if not available during install

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1710]
### Problem / Motivation
An expected behavior from Drush user is if the user is going to install a project (module/theme) that is not currently available is going to try to download first and the installed it.

This have happen to me as well to other new DrupalConsole users. For instance - [Install module via Drupal Console fails](http://drupal.stackexchange.com/questions/186598/install-module-via-drupal-console-fails) some people are thinking that this is even a bug because is something expected already.

### Solution
- Add the ability of downloading the project if not available:
 - [module:install] should trigger [module:download] if the module is not available.  
 - [theme:install] should trigger [theme:download] if the theme is not available.

**Comment by jmolivas** [comment]
:+1: I like to have same feature when trying to install missing module dependencies.

**Comment by enzolutions** [comment]
I will take care of this issue.

**Comment by jmolivas** [comment]
The [module:install] should trigger [module:download] if the module is not available. Is fixed with PR #1743

I will take care of:
* [theme:install] should trigger [theme:download] if the theme is not available.
* Download module depencendies as well when not on the local system.
