### ISSUE TITLE
[generate:entity:content] produces unusable settings route

### ISSUE THREAD

**Issue by HaleFx** [hechoendrupal/DrupalConsole#1726]
When I try to visit the settings form for a content entity generated in 0.10.4, I get:
>InvalidArgumentException: Class "Drupal\mymodule\Controller\MyEntitySettingsForm" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 29 of /srv/bindings/e96b8970f1ef4595bb0c19028baccf1c/code/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php).

I think that getSettingsFormRoute() in EntityHtmlRouteProvider is just adding the wrong default form path. I changed `'_form' => 'Drupal\mymodule\Controller\MyEntitySettingsForm',` to `'_form' => 'Drupal\mymodule\Form\MyEntitySettingsForm',` and that fixed the issue for me.

**Comment by mnico** [comment]
This issue is solved with this PR https://github.com/hechoendrupal/DrupalConsole/pull/1805

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/1805
