### ISSUE TITLE
[generate:view:field:output] Views field content into a variable

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1737]
### Problem / Motivation 

If you ever want to create views field template you are going to run into some issue with `{{ kint() }}` trying to load all content and is very difficult to debug (almost impossible, usually the browser will crash). After some investigation the best solution to add wrappers around the fields templates in views need to add the following preprocess function 

    function THEMENAME_preprocess_views_view_field(&$variables) {
        $variables['output'] = $variables['field']->advancedRender($variables['row']);
    } 

This will allow you to have `{{ output }}` as the field information and we can added wrappers around the field.

Here is some discussion about  this issue https://drupal.stackexchange.com/questions/186165/how-to-get-variables-of-field-from-a-view-in-twig

### Solution
 - Adding the above preprocess function to allow the user have a `{{ output }} ` as variable

**Comment by enzolutions** [comment]
This is a very specific implementation, becuase output is outside the stander, and we will forcing developer to use our style.

This sounds like a recommendation inside a tutorial.

**Comment by darol100** [comment]
@enzolutions closing this issue then.
