### ISSUE TITLE
[generate:entity:content] Using custom name other than DefaultEntity causes access denied

### ISSUE THREAD

**Issue by reekris** [hechoendrupal/DrupalConsole#1739]
When generating an entity with bundle support that does not use the default settings I'm getting a permission denied when trying to add a new entity of the created type.

Steps to reproduce using 0.10.5:
1.```drupal generate:module  --module="Test" --machine-name="test" --module-path="/modules/custom" --description="My Awesome Module" --core="8.x" --package="Custom" --composer```
2. ```drupal generate:entity:content  --module="test" --entity-class="Test" --entity-name="test" --label="Test" --has-bundles```
3. ```drupal module:install test```
4. Go to admin/structure/test_type
5. Create an entity type
6. Go to admin/structure/test/add

This gives an access denied error. This does not happen if the content entity was created using the default settings with --has-bundle

**Comment by enzolutions** [comment]
@mnico will take care this issue

**Comment by mnico** [comment]
Fixed with PR #1805
