### ISSUE TITLE
[module:uninstall] add force uninstall option

### ISSUE THREAD

**Issue by Eyal-Shalev** [hechoendrupal/DrupalConsole#1745]
## Motivation
During intensive development we sometimes need to re-install modules that are dependent upon by other modules.

## Solution
Adding  an option to the module uninstall command to ignore dependencies

**Comment by darol100** [comment]
:+1:  For this feature. However, I think this should be a and option on separate command. Something like this `drupal module:uninstall MyModule --force`  instead of adding as part of asking question.

**Comment by Eyal-Shalev** [comment]
Can you clarify?
I thought I added it as an option for the module:uninstall command.

**Comment by Eyal-Shalev** [comment]
I closed it on accident

**Comment by Eyal-Shalev** [comment]
Darol,
Can you clarify?
Because I made it as an option on the module:uninstall command

**Comment by darol100** [comment]
You are right this is a option. Ignore my previous comment.
