### ISSUE TITLE
[generate:entity:content] isPublished() returns FALSE for published entities

### ISSUE THREAD

**Issue by HaleFx** [hechoendrupal/DrupalConsole#1755]
`$this->getEntityKey('status')` does not seem to return a value for a content entity (no bundle) with `status = 1`. As a test, I swapped it with `$this->get('status')->value` and then `isPublished()` worked fine.

    public function isPublished() {
      return (bool) $this->getEntityKey('status');
    }

**Comment by chuongle** [comment]
I got it working by adding `"status" = "status"` to the entity_keys or using @HaleFx solution.

**Comment by enzolutions** [comment]
Fixed with PR #1820
