### ISSUE TITLE
After generating a new entity ..routing.yml does not exist 

### ISSUE THREAD

**Issue by maen007** [hechoendrupal/DrupalConsole#1799]
I had to create it manually...

**Comment by jmolivas** [comment]
May you include steps related how to reproduce:

**Details to include:**
- Drupal version (you can obtain this by running `drupal site:status`).  
- Console version (you can obtain this by running `drupal --version`).
- Steps to reproduce
  * Executed command.
  * Ouput messages
  * Include screen-shot or video whenever necessary.

**Comment by maen007** [comment]
Drupal 8.0.1 
PHP: 5.5.9
Drupal Console version 0.10.5
OS: ubuntu 14.04
Executed commands: 
- drupal generate:module
- drupal generate:entity:content

**Comment by HaleFx** [comment]
I noticed this change a few versions back. It isn't needed. The defined handlers and EntityHtmlRouteProvider.php seem to take care of everything.

**Comment by maen007** [comment]
Nope, after usind the commands and trying to open the settings, there comes a fatal error. So the settings are not routed. Thus I created the routing.yml by hand.

**Comment by HaleFx** [comment]
The settings path doesn't work because of #1726

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/1805
