### ISSUE TITLE
[module:path] - new command that returns the relative path to the module

### ISSUE THREAD

**Issue by Eyal-Shalev** [hechoendrupal/DrupalConsole#1800]
## Motivation
Some of our submodules are buried deep inside other modules

## Solution
Create a command that returns the relative path to the module (or absolute path)

**Comment by enzolutions** [comment]
Hi @Eyal-Shalev could you provide an specific example to use as guide to build the example.

**Comment by Eyal-Shalev** [comment]
`cd $(drupal module:path hello_world)`

`vim $(drupal module:path hello_world)/hello_world.module`

`drupal config:import:single hello_world.settings "$(drupal module:path hello_world)/config/install/hello_world.settings.yml"`

**Comment by enzolutions** [comment]
A new command will be included in beta3 module:path to resolve this request https://github.com/hechoendrupal/DrupalConsole/pull/2435
