### ISSUE TITLE
[generate:entity:config] Add option to specify the base-path for routing

### ISSUE THREAD

**Issue by larowlan** [hechoendrupal/DrupalConsole#1813]
### Problem/Motivation
Generating a config entity defaults to admin/config/{something}.
Sometimes you want it somewhere else.
This would allow an option to nominate the base path

### How to reproduce
N/A

### Solution
Add another question

**Comment by larowlan** [comment]
Working on this

**Comment by kevinquillen** [comment]
Actually the routes aren't updated.. if you say, specify /admin/config/content as the base path, your routing and menu files still wind up receiving the wrong route parent:

```
parent: system.admin_structure
```

Where in this case, it should be:

```
parent: system.admin_config_content
```

**Comment by larowlan** [comment]
damn

**Comment by liquidcms** [comment]
is this the same as issue #2974 which i just opened?

i am not very D8 happy but is it possible this is due to no routing.yml file being created
