### ISSUE TITLE
[config:export:single] Should have an option for exporting dependencies as well.

### ISSUE THREAD

**Issue by acbramley** [hechoendrupal/DrupalConsole#1817]
### Problem/Motivation
Being able to export a single config item is useful, but it would be great to be able to export all dependencies of that config item at the same time.

### Solution
Add option for ````--include-dependencies```` which calculates the dependencies using ConfigDependencyManager ala. the Features module.

PR to follow shortly.

**Comment by darol100** [comment]
This will be a very nice feature.....  1+
