### ISSUE TITLE
Call to a member function getProjects() on a non-object in src/Helper/SiteHelper.php

### ISSUE THREAD

**Issue by balagan73** [hechoendrupal/DrupalConsole#1824]
I have just updated drupalconsole with self-update to version 0.10.6. The update was successful, but running drupalconsole again I get the following error:
or: Call to a member function getProjects() on a non-object in phar:....../php/drupalconsole/src/Helper/SiteHelper.php on line 371

**Comment by balagan73** [comment]
The problem is, I have  no update.manager service on my machine

**Comment by jmolivas** [comment]
Fixed with PR #1837
