### ISSUE TITLE
[migrate] Migrate commands are not working as expected

### ISSUE THREAD

**Issue by miromichalicka** [hechoendrupal/DrupalConsole#1834]
After enabling migrate and migrate_drupal modules I am still getting following error:
[ERROR] Missing module dependency "migrate" is not installed. Try module:install to install it.

With 0.10.3 everything is working fine.

**Comment by miromichalicka** [comment]
Tested with 0.10.3-0.10.6. This is issue only for the latest version.

**Comment by jmolivas** [comment]
Fixed, this wiull be reflected on the next release v0.10.7
As you can see the execution before and after applying the fixes.
![drupal-migrate-debug](https://cloud.githubusercontent.com/assets/366275/12730224/d6d0f032-c8df-11e5-959b-560dde4a7552.png)
