### ISSUE TITLE
[test:run] Running test in the console always failed. 

### ISSUE THREAD

**Issue by DmitryDrozdik** [hechoendrupal/DrupalConsole#1857]
### Problem

I have a test for a module https://github.com/drupal-ukraine/dmaps/blob/8.x-1.x/d8/modules/custom/dmaps/src/Tests/Form/MainSettingsFormTest.php . It works well in the UI and always pass, but when I run it in the console using next command
`drupal -vvv test:run --url http://default "\Drupal\dmaps\Tests\Form\MainSettingsFormTest"`

I can see lot's of errors in the output. Example of output: https://travis-ci.org/drupal-ukraine/dmaps/builds/103942310

### How to reproduce
1. Choose Drupal test for any module
2. Run test using next commend `drupal -vvv test:run --url http://default "{{test namespace}}`

**Comment by enzolutions** [comment]
@DmitryDrozdik all you need to do is pass a valida URL of a Drupal 8 Installation.
