### ISSUE TITLE
[site:new] Prompt for directory

### ISSUE THREAD

**Issue by UnbekanntesPferd** [hechoendrupal/DrupalConsole#1859]
Is there a way to let site:new prompt for directory and maybe version?

I'd like to use it via chain and that file should be used to setup a fresh install as a new project so the directory changes each time.

**Comment by jmolivas** [comment]
@UnbekanntesPferd: Yes you can pass `directory` and `version` values.

* Inline mode:
```
drupal site:new drupal.dev 8.0.2
``` 

Using chain command, this should be the chain definition:
```
commands:
  - command: site:new
    arguments:
      directory: drupal.dev
      version: 8.0.2
```

You can take a look at the provided chain files at the repo: https://github.com/hechoendrupal/DrupalConsole/tree/master/config/dist/chain

You can also copy those files to your home directory for customization by executing:
```
drupal init 
```

**Comment by UnbekanntesPferd** [comment]
Sorry, maybe it wasn't clear enough. 
I was looking for a way to not set some arguments/options in the yml-file, instead to be prompted for missing arguments/options while the chain itself is running.

**Comment by jmolivas** [comment]
At this point when running the chain command this run as `--no-interaction` by default.

What is your use case?

**Comment by UnbekanntesPferd** [comment]
I'd like to have one yml-file that I can use each time I want to start a new project. But each project has to be installed in different folder and database, has a different site name and so on. But most of the times I have a bunch of modules to install.

Maybe than I have to put this into parts like
site:new
site:install
and than chain all the module installation stuff

**Comment by jmolivas** [comment]
@UnbekanntesPferd we added placeholders to chain files example at https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/chain/quick-start-db.yml

May this solve your issue?  

You can custom the YAML file as you need as example add a placeholder on directory 
```
commands:
# Download Drupal
  - command: site:new
    arguments:
      directory: '%{{directory|drupal.dev}}'
    options:
```

* You can execute this and set the value using the interactive mode

![chain-inline](https://cloud.githubusercontent.com/assets/366275/15690613/3ac129c4-2739-11e6-8fed-93d9f287801f.png)

* You can pass the value via the CLI by executing:
```
drupal chain --file="~/.console/chain/quick-start.yml" --placeholder="directory:d8.dev"
```

**Comment by UnbekanntesPferd** [comment]
That looks pretty good! :)
Thanks! 👍

**Comment by enzolutions** [comment]
@UnbekanntesPferd this issue will be closed, as was resolved
