### ISSUE TITLE
[generate:plugin:field] fails with error

### ISSUE THREAD

**Issue by yobottehg** [hechoendrupal/DrupalConsole#1885]
i wanted to generate a field and the following error happens in the step "Enter the default field widget of the field type plugin"

PHP Fatal error:  Call to undefined function contact_form_field_widget() in phar:///usr/local/bin/drupal/vendor/symfony/console/Helper/SymfonyQuestionHelper.php on line 36

Where contact_form_field_widget is the widget i entered earlier.
The same error happens if i leave this question empty

**Comment by adriangordon1231** [comment]
I am currently having the exact same error (Drupal Console version 0.10.11)

**Comment by dagomar** [comment]
Confirmed, I have the same problem :'(

**Comment by greg606** [comment]
ok, any progress on it?

**Comment by darol100** [comment]
This seem the be fixed already. Closing this issue.
