### ISSUE TITLE
[chain:debug] Auto-discovery chain commands

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1899]
### Problem / Motivation

Second part of #1898. We need the ability of auto-discovery chain commands and add at `drupal list`.

## Solution

- Add the ability of auto-discovery with a command.
- Should we run this on every `module:enable` ?

**Comment by jmolivas** [comment]
I am currently working on this:

![drupal-chain-debug](https://cloud.githubusercontent.com/assets/366275/12957903/dadaa69a-cfe3-11e5-8116-a410bc156f27.png)

Should we take advantage of the interactive mode while executing the chain command and no `--file` option entered and show a list of discovered files to select and execute.

**Comment by darol100** [comment]
:+1:

**Comment by jmolivas** [comment]
This is done and already merged

**Comment by jmolivas** [comment]
My bad this is not yet completed
