### ISSUE TITLE
Illegal argument in chdir() in Application.php

### ISSUE THREAD

**Issue by balagan73** [hechoendrupal/DrupalConsole#1923]
Running drupal self-update with 0.10.11 version outside drupal directory I get the following error: 
PHP Warning:  chdir(): Invalid argument (errno 22) in phar:/.../drupalconsole/src/Application.php on line 288
I guess $drupal->getRoot() returns null.
I think self-update should be able to run from outside a drupal installation directory.

**Comment by jmolivas** [comment]
@balagan73: This got fixed on 0.1.12, fo you may to test and confirm if the issue is fixed or continue to  happening.

**Comment by balagan73** [comment]
I confirm now I can run drupal self-update from outside a drupal directory, and it updates itsellf without any problem.

**Comment by balagan73** [comment]
Well, just thinking about it, I was running 0.1.11 to self-update to 0.1.12, and that gave me no warnings.
