### ISSUE TITLE
Unable to self-update with 0.10.11

### ISSUE THREAD

**Issue by pwalter-ebi** [hechoendrupal/DrupalConsole#1926]
Have Drupal Console version 0.10.11 on OSX 10.11.3. Getting error when checking for updates:

> drupal self-update
> Checking for updates from version: 0.10.11
> The latest version 0.10.11, was already installed on your system.
> // settings:set
>
> Warning: file_get_contents(/Users/pwalter/.console/config.yml): failed to open stream: No such file or directory in phar:///usr/local/bin/drupal/src/Command/Settings/SetCommand.php on line 69
>
> Catchable fatal error: Argument 1 passed to Drupal\Console\Helper\NestedArrayHelper::setValue() must be of the type array, null given, called in phar:///usr/local/bin/drupal/src/Command/Settings/SetCommand.php on line 77 and defined in phar:///usr/local/bin/drupal/src/Helper/NestedArrayHelper.php on line 153

**Comment by jmolivas** [comment]
@pwalter-ebi can you try executing `drupal init` if that does not work the try `drupal init --override`

**Comment by pwalter-ebi** [comment]
thank you, 'drupal init' solved the problem

**Comment by darol100** [comment]
@jmolivas We should document the `drupal init --override` info somewhere. I will close this issue since this been solve.
