### ISSUE TITLE
[standard] @file is not required for classes, interfaces and traits

### ISSUE THREAD

**Issue by ddrozdik** [hechoendrupal/DrupalConsole#1928]
Hi,

**Problem/Motivation**
https://www.drupal.org/node/2304909
https://www.drupal.org/node/2665744

**How to reproduce**
Using DrupalConsole generate any controller or form, test, etc. Check that each file with single class contain @ file block in the file.

**Solution**
 Remove this @ file block for such kind of generated classes.

**Comment by darol100** [comment]
@DmitryDrozdik , Great find.

**Comment by vijaycs85** [comment]
Looks like this issue has been fixed already. Generating controller now doesn't add @file block. Please confirm /cc @enzolutions

**Comment by enzolutions** [comment]
@vijaycs85 

There are some @file entries inside templates folder, please check the command that use those template to evaluate if is required to remove 

![screen shot 2016-07-30 at 6 14 06 am](https://cloud.githubusercontent.com/assets/907914/17270311/e5ddc558-561c-11e6-8c2d-78173bd8fde7.png)

**Comment by vijaycs85** [comment]
@enzolutions true, but the removal of @file block is only on class files. all the @file inside templates dir are non-class templates. So I guess, we can leave them.

**Comment by enzolutions** [comment]
True, I am going to close this issue. thanks @vijaycs85
