### ISSUE TITLE
howto: Create module with custom entity and CRUD

### ISSUE THREAD

**Issue by darthf1** [hechoendrupal/DrupalConsole#1929]
Using the Drupal CLI I've generated a D8 module. Now I want to generate a content type with additional fields, for which I can define my own CRUD, forms and other logic. I used `drupal generate:entity:bundle` which generates the new content type and makes it possible to add new fields through the admin interface.

I don't want to add fields through the UI; I want to add fields through code, so I can add new logic in the (CRUD) controller. This will be adding fields, defining new views, adding validation etc. I tried to use `drupal generate:entity:content`, but it doesn't seem to get me anywhere.

I looked at the [example project](https://www.drupal.org/project/examples), specifically the content_entity_example however it doesn't seem to provide the CRUD functionality I'm looking for which is normally embedded in the controller.

**Comment by darol100** [comment]
IMO, @darthf1 , This is far away from the scope of this project. This seem more like a support question rather than reporting a bug or a new feature. For this reason I'm closing this issue.
