### ISSUE TITLE
[database:update] Perform all pending updates

### ISSUE THREAD

**Issue by Eyal-Shalev** [hechoendrupal/DrupalConsole#1930]
### Motivation
From a team workflow perspective it is much more clean to use console commands then to ask developers to go to site.com/update.php and use the wizard.
Commands can also be automated.

**Comment by jmolivas** [comment]
@Eyal-Shalev I remember @enzolutions was working on something like this amnd he wrote an article about executing updates. 
https://drupalconsole.com/articles/running-drupal-8-updates-partially

Not sure if this is what you are looking for.

**Comment by Eyal-Shalev** [comment]
It seems like the update command is what I was looking for.
Thank you.

I'll close the issue later when I'll be near my computer.

On Mon, Feb 15, 2016, 22:44 Jesus Manuel Olivas <notifications@github.com>
wrote:

> @Eyal-Shalev <https://github.com/Eyal-Shalev> I remember @enzolutions
> <https://github.com/enzolutions> was working on something like this amnd
> he wrote an article about executing updates.
> https://drupalconsole.com/articles/running-drupal-8-updates-partially
>
> Not sure if this is what you are looking for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hechoendrupal/DrupalConsole/issues/1930#issuecomment-184386644>
> .
>
-- 

Regards,
Eyal Shalev

**Comment by jmolivas** [comment]
Feel free to re-open if something missing. @Eyal-Shalev
