### ISSUE TITLE
[node:access:rebuild] New Command

### ISSUE THREAD

**Issue by ericpugh** [hechoendrupal/DrupalConsole#1936]
### Problem/Motivation
Since the node_access_rebuild documentation recommends that modules only register the need for a user to rebuilding access permissions, it might be useful for users to do this from the CLI. 

**Details to include:**
- [node_access_rebuild](https://api.drupal.org/api/drupal/core!modules!node!node.module/function/node_access_rebuild/8)
- Looks like there's a [drush extension](https://github.com/dafeder/node_access_rebuild) for Drupal 7

**Comment by jmolivas** [comment]
@ericpugh: Thanks for the PR, I will review and test it.

**Comment by ericpugh** [comment]
Quick question... are there any existing DrupalConsole commands that use a symfony-console-like progress bar for batch processing?

**Comment by jmolivas** [comment]
@ericpugh: Not in DrupalConsole core but you can find one implementation on contrib space at webprofiler module:
https://github.com/lussoluca/webprofiler/blob/8.x-2.x/src/Command/BenchmarkCommand.php
