### ISSUE TITLE
exporting configuration to a directory does not work

### ISSUE THREAD

**Issue by balagan73** [hechoendrupal/DrupalConsole#1949]
Running the drupal config:export --directory directoryname command with 0.10.12 version of drupal console on Windows the command returns an OK result, but the directory is not created.

**Comment by wmhopk** [comment]
When I tried it with a nonexistent directory I got the same results as @balagan73  but when I created the director first it worked.

**Comment by jmolivas** [comment]
thanks @wmhopk we will fix this issue to create parent directories if not exists.

**Comment by wmhopk** [comment]
@jmolivas Also, would it make sense to show the full path upon successful export? Just a thought not sure if it's necessary but may be useful if someone mistakenly types in the wrong path.

**Comment by miguel303** [comment]
I'm using  1.0.0-beta3 version of drupal console and the command drupal config:export --directory works as expected 
I ran drupal config:export --directory sites/default/files/configfolder, then I looked at the folder and the files are there. 

![exportingconfiguration](https://cloud.githubusercontent.com/assets/12614801/16494289/0402b784-3ea6-11e6-89d4-921ae10097fc.png)



@balagan73  can you try again please , try to update the version of drupal console

**Comment by balagan73** [comment]
This command still does not work in version 0.10.14 without creating the directory in advance. When the directory is created in advance, it exports the files, but not otherwise.

**Comment by miguel303** [comment]
@balagan73  update your drupal console version , since your are using  0.10.14, so try with 1.0.0-beta3 version

**Comment by balagan73** [comment]
I confirm the command creates the directory with version 1.0.0-beta3. Closing this issue now.
