### ISSUE TITLE
config:settings:debug does not work

### ISSUE THREAD

**Issue by balagan73** [hechoendrupal/DrupalConsole#1956]
When I try to run the `config:settings:debug` command, I get the following error:

`[InvalidArgumentException]
  There are no commands defined in the "config:settings" namespace.`
I am running 0.10.12

**Comment by jmolivas** [comment]
@balagan73: `config:settings:debug` was renamed to `settings:debug`

**Comment by balagan73** [comment]
Sorry, I was outside my drupal directory. The command runs without any problem, and it seems to be different from `settings:debug`

**Comment by jmolivas** [comment]
@balagan73 true
`config:settings:debug` show drupal site config key values 

`settings:debug` show drupal console config options
