### ISSUE TITLE
Release 0.10.12 needs php5-curl and optionally php5-sqlite

### ISSUE THREAD

**Issue by theodorosploumis** [hechoendrupal/DrupalConsole#1959]
I just updated to version [0.10.12] (https://github.com/hechoendrupal/DrupalConsole/releases/tag/0.10.12) on Ubuntu 15.10. After that I got 1 error and 2 simple messages (recommendations) because of the new [phpcheck.yml](https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/phpcheck.yml) file.

Error 1
```[ERROR] The extension curl is missing.```

Messages 1
```The extension sqlite3 is recommended to install.```

Message 2
```The configuration date.timezone was missing and overwritten with America/Tijuana.```

- I could solve the Error by installing the **php5-curl** extension. 
- I could solve the Message 1 by installing **php5-sqlite** extension.
- For the Message 2 I edited the ```~/.console/phpcheck.yml``` file but still no luck. My server has date.timezone set so I cannot understand why it cannot find it.

I think these should be added on the documentation somehow. Thank a lot!

**Comment by OnkelTem** [comment]
> My server has date.timezone set so I cannot understand why it cannot find it.

Have also set date.timezone in your CLI php.ini?

**Comment by theodorosploumis** [comment]
It's also in php.ini.

**Comment by OnkelTem** [comment]
I meant there are usually at minimum two php.ini-s: one for `libapache2-mod-php5` and another for CLI.

**Comment by ruodeng** [comment]
I install as the php5-fpm and nginx,  the drupal command runs as the php CLI, 
Need add the timezone on /etc/php5/cli/php.ini

**Comment by jmolivas** [comment]
You can try `php -i | grep php.ini` to check where the `php.ini` is loaded from.

**Comment by diqidoq** [comment]
This issue demonstrates that the error message isn't informing enough which timezone setting it talks about since there are many options in a server enviroment. For new Drupal 8 users it is even not sure if it is about a Drupal specific, PHP specific, Apache specific or Server specific timezone in this message.

**Comment by diqidoq** [comment]
Sadly installing *php5-sqlite* (which is the only option under php5 here) doesn't remove the message *missing sqlite3* on Debian 9. Installing php-sqlite3 installs the complete php7 stack which troubles with Drush.

**Comment by jmolivas** [comment]
@diqidoq You savoid warning message to keep appearing by executing:
```
drupal settings:set checked "true"
```

**Comment by jmolivas** [comment]
I will add a configuration to customize if warning messages are show.

**Comment by diqidoq** [comment]
`drupal settings:set checked "true"`
@jmolivas Didn't knew that. Perfect.
@jmolivas++ *for adding a configuration to customize if warning messages are shown*. Thanks for chiming in so fast.

**Comment by fndtn357** [comment]
can I add? I have installed PHP7 with nginx on Ubuntu 14.04 (x64) and the location for date.timezone  is /etc/php/7.0/cli

**Comment by jmolivas** [comment]
@fndtn357 you have the same issue? can you share what is your error/warning.

**Comment by fndtn357** [comment]
I had the same warning. Installed the appropriate mods and later read about
being able to ignore them. I didn't expect it because I am using nginx and
php7.0-fpm

**Comment by fndtn357** [comment]
I'm sorry I didn't read well before answering. I don't remember exactly
what it said, except it was a yellow (not red) highlighted bar with a
warning that I did not have them installed.

*James R Stone*
*Drupal site-builder/developer/consultant*Office: 216-635-9247
fndtn357@gmail.com

------------------------------

This e-mail message, including any attachments, is for the sole use of the
intended recipient(s) and may contain private, confidential, and/or
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited. If you are not the intended recipient,
employee, or agent responsible for delivering this message, please contact
the sender by reply e-mail and destroy all copies of the original e-mail
message.

<fndtn357@gmail.com>

**Comment by fndtn357** [comment]
Messages 1
The extension sqlite3 is recommended to install.

Same message. I also had to go into different folders to relieve the waning about time zones. php7.0-fpm and cli under Php7.0

**Comment by atdc98** [comment]
Because drupal console is using the cli instance of PHP, check that your `/etc/php5/cli/php.ini` file has the timezone set.

**Comment by webharvesting** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

sudo apt-get install php5-sqlite
sudo apt-get install php5-curl

sudo vi /etc/php5/cli/php.ini and
uncomment and set 
date.timezone = <your timezone>

Fixes the issue ..

**Comment by enzolutions** [comment]
@theodorosploumis we could close this issue?
