### ISSUE TITLE
[generate:module] "Do you want to generate .module file" default yes.

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1964]
### Problem / Motivation
Most of the time when the user is generating the a new module (`generate:module`) the user will have to have a .module file. It makes sense to have it the default as `yes` instead of `no`.

### Solution
- Add the default value to be `yes`

**Comment by danielrose28** [comment]
Not sure if this has been done already, but this seems like maybe something a novice could try? If you don't mind kind of helping me through this I'd give it a try. I'm searching the code at the moment, trying to find where this change would be made. Haven't found it yet. heh..

**Comment by danielrose28** [comment]
I think I found the right place. Correct me if I'm wrong: `/DrupalConsole/src/Command/Generate/ModuleCommand.php`?

**Comment by darol100** [comment]
@danielnv18 , In line 208 if I'm not wrong you need to change `false` to `true`. Try that out and see if that changes it to Yes.

If you need any help let us know via Gitter.

**Comment by danielrose28** [comment]
Cool. I'll work on it today and share some updates. Thanks.

**Comment by danielrose28** [comment]
@darol100 I have a really stupid question, but it's been a while since I've contributed here. I've created a new branch, made the necessary changes and pushed to my repo. How do I test this change? Is there a way, or do i just create the PR? <embarrassed> sorry

**Comment by Saphyel** [comment]
Why do you need the .module? I think use the .module is legacy practice tbh...

**Comment by danielnv18** [comment]
@Saphyel it might disappear in [Drupal 9](https://www.drupal.org/node/1509164) but the .module is still needed for some hooks like the [hook_theme](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8).

**Comment by Saphyel** [comment]
@danielnv18 you are right, for a few hooks. And because you are not going to use always them, in fact is very strange you need to use those hooks, I don't see the reason to use default yes....

**Comment by darol100** [comment]
@Saphyel , This issue was create because we were showing this into few training/sessions and Drupal users are expecting to be set to "Yes". 

I'm closing this issue because the PR was merge already.
