### ISSUE TITLE
[generate:module:file] Decouple the .module generation into custom command.

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#1965]
### Problem / Motivation
Sometimes the user did not select the ability of generating a .module. We should decouple the ability of generating a .module file independent and added as chain into the `generate:module` command.

### Solution
- We need to abstract the functionality that generates command the .module a command.
- Add the command into `generate:module`

**Comment by miguel303** [comment]
PR in #2481

**Comment by enzolutions** [comment]
Issue closed after PR was merged
