### ISSUE TITLE
[database:log:debug] by default show latest entries first, descending

### ISSUE THREAD

**Issue by fluxsauce** [hechoendrupal/DrupalConsole#1973]
When reviewing logs, seeing the latest content first is more natural than having to manually specify reverse order:

```bash
drupal database:log:debug --reverse
```

**Comment by jmolivas** [comment]
:+1: on this

**Comment by enzolutions** [comment]
Changes applied in PR https://github.com/hechoendrupal/DrupalConsole/pull/2438
