### ISSUE TITLE
[console] Update CLI output style.

### ISSUE THREAD

**Issue by LiangJ** [hechoendrupal/DrupalConsole#1986]
![bug](https://cloud.githubusercontent.com/assets/2550918/13483522/04cbcc7e-e130-11e5-895a-54ab4f281e82.png)

**Comment by darol100** [comment]
@LiangJ , What OS and type of terminal you are using ?

I'm having the same issue on OSX and iTerm.

**Comment by LiangJ** [comment]
@darol100
OS： Win7
Terminal Type： Putty 0.63

**Comment by darol100** [comment]
I think we should pick a different color that actually can work on other terminals.
