### ISSUE TITLE
Usage workflow: so libraries are always in un-sync state?

### ISSUE THREAD

**Issue by OnkelTem** [hechoendrupal/DrupalConsole#1989]
I have Drupal Console 0.10.12 installed under `~/.composer/` directory.
After upgrading Drupal of a website from 8.0.3 to 8.0.5 I now have the following issue with `drupal cr all`:
```
$ drupal cr all

 Rebuilding cache(s), wait a moment please.
PHP Strict standards:  Declaration of Symfony\Component\DependencyInjection\DefinitionDecorator::setFactoryService() should be compatible with Symfony\Component\DependencyInjection\Definition::setFactoryService($factoryService, $triggerDeprecationError = true) in /var/www/sites/<project>/docroot/vendor/symfony/dependency-injection/DefinitionDecorator.php on line 212
// <stack>

 [OK] Done clearing cache(s).
```

This is pretty obvious and expected as the libraries are of different versions:

![](https://sc-cdn.scaleengine.net/i/60430dd4f130eb6c1a56174aa69742a4.png)

To the left goes the ouput of `composer show -i | sort | grep symfony` launched in the `/var/www/sites/<project>/docroot` dir while to the right — the same command launched in the '~./composer/' dir.

As we can see, versions are different. So my question is - what workflow of updating Drupal and Console is supposed? Or what I do wrong?

**Comment by bojanz** [comment]
You installed Console globally, it has nothing to do with your Drupal install. You need to update both separately.

This is why many sites actually add Console to their site's composer.json (the one in your Drupal root), then access console from vendor/bin/drupal.

**Comment by OnkelTem** [comment]
@bojanz 

> This is why many sites actually add Console to their site's composer.json (the one in your Drupal root), then access console from vendor/bin/drupal.

That's what I wished to hear — i.e. installing Console with the website. Maybe it could be quite safe to reflect this in the docs. 

Thanks for this info.
