### ISSUE TITLE
Prompts for database name in install files

### ISSUE THREAD

**Issue by jmevalentin** [hechoendrupal/DrupalConsole#1990]
Can we add a prompt for the database name in the quick-start-mysql.yml or other quickstart files? This would eliminate (or reduce) the need for multiple install files. Of course, if the user mistypes their database name they will have to run the command again if they don't catch their error. A confirmation page at the end prior to final run would help.

**Comment by darol100** [comment]
@jmevalentin I'm closing this issue because this should be solve in a more generic way, which is going to be https://github.com/hechoendrupal/DrupalConsole/issues/2055.

**Comment by jmevalentin** [comment]
If there is a way to provide either prompts or allow passing of parameters for all of the various options it would be great, but it does seem to be difficult to cover everything via the CLI.

**Comment by jmolivas** [comment]
@jmevalentin seems like is doable, @darol100 and I had a talk yesterday I will try to write a basic implementation to test this possible feature.

**Comment by jmevalentin** [comment]
I have been wondering about another possibility. It's necessary to enter each item 1 line at a time, and you can't go back and undo it. I know that a web UI will solve this, but can we get a command line UI, like the old days of file managers like XTree? It would allow for seeing all of the options and selecting and reviewing them before finalizing them.

**Comment by jmevalentin** [comment]
Ah, I'm seeing the conversation in gitter, seems like the chain command will cover the parameters concern with the extra step of writing a yml file, and the UI (https://github.com/hechoendrupal/drupal-console-desktop/issues/5) will be as good or better than a shell based UI.
