### ISSUE TITLE
Get latest support version of Drupal

### ISSUE THREAD

**Issue by sanglt** [hechoendrupal/DrupalConsole#2000]
````
 ~  drupal

Drupal Console (0.10.12) | Supports Drupal (8.0.3) | Drupal is not installed
============================================================================
...
Create a new Drupal project

   drupal site:new drupal8.dev 8.0.3
````
Current Drupal is follow http://semver.org, so Drupal Console should working fine with any Drupal 8.0.x now. So the intro of Drupal Console should show the latest stable version of Drupal. Because when i follow by the intro, i will get the 8.0.3 version (Not current stable version).

Thanks,

**Comment by darol100** [comment]
@sanglt We update what DrupalConsole support manually base on the release + current Drupal core installation. However, we have not done a release for few weeks already, for this reason, the "supported version is out-date". We will be doing a release soon and we will be taking care of this issue.
