### ISSUE TITLE
Decide when to require Drupal 8.1

### ISSUE THREAD

**Issue by bojanz** [hechoendrupal/DrupalConsole#2022]
Drupal 8.1 brings improvements that significantly reduce entity boilerplate:
- generation of fields for entity keys https://www.drupal.org/node/2635224
- add-form route generation https://www.drupal.org/node/2596095
- add-page route generation https://www.drupal.org/node/2666792
- RevisionableContentEntityBase https://www.drupal.org/node/2666808

To make use of this, Console needs to require Drupal 8.1.
Drupal 8.0 support will be dropped when 8.1 is released (end of April?), so it probably makes sense to create an 8.1-only branch of Console in early April? Could be just in time for 8.1 RC1.

**Comment by jmolivas** [comment]
:+1: on this, make sense to have track of all of this changes

**Comment by greg-1-anderson** [comment]
Drupal 8.1 is scheduled to be released on [Wednesday 20 April](https://groups.drupal.org/node/508968).

**Comment by dgtlmoon** [comment]
bumping this a little, 8.1.0-rc1 is out, is it still preferable to make a 8.1 branch?

**Comment by bojanz** [comment]
Drupal 8.1 itself is out. It's time :)

**Comment by jmolivas** [comment]
I will today ... new DC release is coming.

**Comment by jmolivas** [comment]
@bojanz Drupal Console [v1.0.0-alpha1](https://github.com/hechoendrupal/DrupalConsole/releases/tag/1.0.0-alpha1) is release, providing support for 8.1.x and dropping support for 8.0.1
