### ISSUE TITLE
generate:controller - method title (leave empty and press enter when done) [ ]

### ISSUE THREAD

**Issue by justinlevi** [hechoendrupal/DrupalConsole#2025]
This is more of a minor critique on the prompt being confusing. 

Here's what I see: 
``` 
Enter the Controller method title (leave empty and press enter when done) [ ]:
 > 
```

And if I press enter - which is what it seems the prompt is telling me I can do, then I see the following error: 
          
```                                                                                                              
 [ERROR] Title must contain a value                 
````

If the field is required, it should probably be designated as such.

**Comment by enzolutions** [comment]
Issue closed after PR merged
