### ISSUE TITLE
ExampleCommand

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#2056]
### Problem / Motivation
For new contributors is going to be very nice if there is a command that can be copy and paste like a started.

### Solution
- Provide an `ExampleCommand` with the function execute and interact. 
- This command should not be shown at generate list.

**Comment by jmolivas** [comment]
:+1: on the idea.

**Comment by cosmicdreams** [comment]
This command can now rely on the Generator logic we showed on the Drupal and Coffee show last night.

So if this was code that was intended to be added to Drupal Console or in a stand alone module it should be (mostly) the same.

**Comment by jmolivas** [comment]
@cosmicdreams we have a generator command for command within a module, we can:
* Update and reuse same command. 
* Create a new command.
* Do what @darol100 mentioned here and provide a file adding instructions duplicate, `cp ExampleCommand.php MyCommand.php`

**Comment by jmolivas** [comment]
@darol100 Are we providing a generator command for this? 

The benefits of providing a generator command are:

* Choose if the command is StandAlone or Container Aware.
* Provide Class name.
* Provide Namespace.

**Comment by darol100** [comment]
@jmolivas , I do not think we have support to write commands directly to Drupal Console. Should we create another issue to allow some generators to generates to DC ?
