### ISSUE TITLE
[module:download] options

### ISSUE THREAD

**Issue by Saphyel** [hechoendrupal/DrupalConsole#2065]
I think this command needs more improvements (also in chain files)
I want this command be able to choose the version I want to use in a readable way as parameter and be able to choose where should be download (maybe I want it in sites/ or in one profiles/ )

**Comment by jmolivas** [comment]
@Saphyel based on your sugesstion we should add new options:

### To select version: 
* `--version`: To enter value like `1.0-beta5`, 1.0-dev` (we can default to latest version)

### To decide where to download:
1) `--directory`: To set path (if no value entered default to `module/contrib`
2) `--type`: To set if module/profile (default to module if no value and set path)

**Comment by jmolivas** [comment]
@Saphyel We cannot use `--version` as option since a global `--version` option is built-in with the Application class.

**Comment by Saphyel** [comment]
@jmolivas what about use the term: `release` or `branch` ?

I prefer `release` tbh
