### ISSUE TITLE
[module:uninstall] Interact and Question

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#2074]
### Problem / Motivation
We should provide a question when the module is going to be uninstalled. This should ask which module is going to be uninstalled and it should provide a list of modules that is enabled.

### Solution
- Provide the interact function with the questions.

**Comment by Saphyel** [comment]
@darol100 why your title is about install and your problem is about uninstall ?
Also the functionality you are requestions it already exist, please check: `drupal module:debug`

**Comment by darol100** [comment]
@Saphyel , I mean to open for both commands. I will open a separate issue for the install command.

Good catch.
