### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mvd81** [hechoendrupal/DrupalConsole#2085]
`curl https://drupalconsole.com/installer -L -o drupal.phar`

If i open https://drupalconsole.com/installer it displays an error.

> The website encountered an unexpected error. Please try again later.
> 
> GuzzleHttp\Exception\ClientException: Client error: `GET https://github.com/hechoendrupal/drupalconsole/releases/download/0.10.15/drupal.phar` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...) in GuzzleHttp\Exception\RequestException::create() (line 107 of vendor/guzzlehttp/guzzle/src/Exception/RequestException.php).

Looks like an error in the latest version, i can download 0.10.**14**

**Comment by kiamlaluno** [comment]
I am getting the same errors. `curl https://drupalconsole.com/installer -L -o drupal.phar` download a drupal.phar file, but when I move it to the /usr/local/bin directory and I try to execute `drupal init --override`, I get the following error:

> /usr/local/bin/drupal: line 1: syntax error near unexpected token `<'
> /usr/local/bin/drupal: line 1: `The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">GuzzleHttp\Exception\ClientException</em>: Client error: `GET https://github.com/hechoendrupal/drupalconsole/releases/download/0.10.15/drupal.phar` resulted in a `404 Not Found` response:'

**Comment by jmolivas** [comment]
@mvd81 @kiamlaluno I just fixed this issue few minutes ago. van your p[lease retry and confirm is working?

**Comment by mvd81** [comment]
@jmolivas yes it works, no errors if i visit https://drupalconsole.com/installer

**Comment by jmolivas** [comment]
Awesome, manifest link is also working now as well https://drupalconsole.com/manifest.json

**Comment by kiamlaluno** [comment]
It works for me too.
