### ISSUE TITLE
[console] Improve installation instructions

### ISSUE THREAD

**Issue by koffer** [hechoendrupal/DrupalConsole#2086]
When I install drupal console, feel like there is some problems with the way is writing. The instructions only have a comment and the command, so feel like all steps are simple options and you dont need to follow steps.  This is my sugestions  to improve it:

>  Work Faster and Smarter.
> 
> Steps to follow:
> 
> # 1- Run this in your terminal to get the latest project version:
> curl https://drupalconsole.com/installer -L -o drupal.phar
> 
> ## Or if you don't have curl:
> php -r "readfile('https://drupalconsole.com/installer');" > drupal.phar
> 
> # 2- Accessing from anywhere on your system (in some systems need sudo):
> mv drupal.phar /usr/local/bin/drupal
> 
> 
> # 3- Apply executable permissions on the downloaded file:
> chmod +x /usr/local/bin/drupal
> 
> # 4- Copy configuration files to user home directory:
> drupal init --override
> 
> # 5- Check and validate system requirements
> drupal check
> 
> the installation is finished!
> 
> # Download, install and serve Drupal 8:
> drupal chain --file=~/.console/chain/quick-start.yml
> 
> # Create a new Drupal 8 project:
> drupal site:new drupal8.dev 
> 
> # Lists all available commands:
> drupal list
> 
> # Update DrupalConsole to the latest version:
> drupal self-update
> 

Im not sure if installations process end in step 5 but if im correct after the last step. give a end message and begin with Options: terminal commands you can use atfer installation but not part of the process.

**Comment by levhita** [comment]
![Visual Example](https://cloud.githubusercontent.com/assets/225066/14215204/c2e3faa8-f7fe-11e5-8dca-2753a86d93c6.jpg)

**Comment by diqidoq** [comment]
@levhita what a useful comment ... *facepalm*

**Comment by omero** [comment]
> Instead of adding numbers why not just break in two groups `Installing` and `Running`

## Installing Drupal Console
```
# Run this in your terminal to get the latest Console version:
curl https://drupalconsole.com/installer -L -o drupal.phar

# Or if you don't have curl:
php -r "readfile('https://drupalconsole.com/installer');" > drupal.phar

# Move downloaded file to a globally accessible path (this may require sudo)
mv drupal.phar /usr/local/bin/drupal

# Apply executable permissions on the downloaded file:
chmod +x /usr/local/bin/drupal

# Copy configuration files.
drupal init --override

# Check and validate system requirements
drupal check
```

## Running Drupal Console
```
# Download, install and serve Drupal 8:
drupal chain --file=~/.console/chain/quick-start.yml

# Create a new Drupal 8 project:
drupal site:new drupal8.dev

# Lists all available commands:
drupal list

# Update to the latest version.
drupal self-update
```
