### ISSUE TITLE
[plugin:debug] Commands for listing plugins

### ISSUE THREAD

**Issue by milesw** [hechoendrupal/DrupalConsole#2096]
I've created some commands for developing and debugging plugins. Like container:debug (super useful), it lists all the available plugin types / instances. 

https://github.com/milesw/plugin_devel

Would this be something you'd consider including with Console? Let me know if anything needs to be changed and I'll create a pull request.

**Comment by jmolivas** [comment]
@milesw: This looks awesome and yes this is we like to include on the project. 

Please send PR and then I will make some notes about the required changes.

**Comment by jmolivas** [comment]
I tested and this is awesome 
![drupal-plugin-debug](https://cloud.githubusercontent.com/assets/366275/14272708/28947f18-faba-11e5-9ea9-3c3471978a06.gif)

**Comment by milesw** [comment]
@jmolivas: Great to hear! Working on a PR now.

**Comment by darol100** [comment]
@milesw , Great work...

**Comment by milesw** [comment]
I'm noticing that a number of plugin types in contrib don't expose services and therefore won't show up using this command. Might need to find a better way to scan for plugins.

**Comment by jmolivas** [comment]
@mnico do you know a better way to discover all of the registered plugins on the system?

**Comment by jmolivas** [comment]
Merged
