### ISSUE TITLE
generate:content:entity won't take an input for the module name.

### ISSUE THREAD

**Issue by lhridley** [hechoendrupal/DrupalConsole#2102]
I am trying to use Drupal console to generate a content entity.  Each time I enter a module name, I get "[ERROR] Value "publications" is invalid.  Please assist?

I am running the dev version, after trying with verion 0.10 and version 0.11.1.

**Comment by jmolivas** [comment]
@lhridley Is `publications ` the module name?, if yes, is the module installed?, if not installed try `drupal module:install publications`

**Comment by lhridley** [comment]
That's my mistake.  I forgot you have to generate the module first!

**Comment by darol100** [comment]
This is not an issue. Closing this issue.
