### ISSUE TITLE
Workaround for missing mysql extension

### ISSUE THREAD

**Issue by drubb** [hechoendrupal/DrupalConsole#2130]
DrupalConsole does a settings check when running commands, which checks for php 'mysql' extension. When this extension is missing, it says ```The extension mysql is recommended to install.```.

This extension has been removed in PHP 7, and for previous versions it's not mandatory. There are mysqli and mysqlnd, too. IMHO DrupalConsole should not check the ancient mysql extension, if there's a newer extension available.

**Comment by jmolivas** [comment]
@drubb You can change setting `checked` as `true` and avoid receiving any messages by executing
```
drupal settings:set checked "true"
```

**Comment by rkoberg** [comment]
The above does not work (php70, and just installed everything (php, php extensions, composer, drupal console) new today):
```
[rkoberg@mbp ~/Sites/fwi/drupal (master *)]$ drupal settings:set checked "true"
 [OK] Setting checked was set to true                                             
[rkoberg@mbp ~/Sites/fwi/drupal (master *)]$ drupal check
 The extension mysql is recommended to install.                                                                      
 [OK] Checks passed.            
 // settings:set                                                                                                                     
 [OK] Setting checked was set to true  
```

**Comment by jmolivas** [comment]
I need to test on php7 and create a diff set of extensions for this version. 

Currently the checker only for works properly on php5 
https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/phpcheck.yml

**Comment by gagarine** [comment]
So if it's broken, the check for mysql should be removed until it's fixed.

I just end up losing an hours trying to fix a problem than I didn't have.

**Comment by cristinallamas** [comment]
me too

**Comment by poproar** [comment]
:-1:

**Comment by thisisablock** [comment]
same issue here

**Comment by zuernBernhard** [comment]
same here als sqlite3 (Ubuntu 16.04 - PHP7.0)

**Comment by Saphyel** [comment]
I use everyday PHP7 and my extensions are this one:
**pdo_mysql opcache gd** soap bcmath imagick xdebug

(The black ones are mandatory, the others are specific for my projects)

**Comment by gagarine** [comment]
@zuernBernhard I changed the pull request according to your comment. If you have some time review it so it can be merged https://github.com/hechoendrupal/DrupalConsole/pull/2518
