### ISSUE TITLE
[generate:form] When I load a service, the console generate twice the service in create method

### ISSUE THREAD

**Issue by igasi** [hechoendrupal/DrupalConsole#2131]
**Problem/Motivation**
I loaded 1 service and the console generate
```
Do you want to load services from the container (yes/no) [no]:
 > yes           


Type the service name or use keyup or keydown.
This is optional, press enter to continue

 Enter your service [ ]:
 > config.factory
 Enter your service [ ]:
 > 
```

![screenshot from 2016-04-12 15-39-36](https://cloud.githubusercontent.com/assets/3912749/14474978/3d3a61ba-00c5-11e6-9e03-5b74add12b55.png)

**Propose solution**

Review the template for render this and remove double service in create method.

**Comment by igasi** [comment]
This also is happening in generate:form:config command

![screenshot from 2016-04-12 16-04-21](https://cloud.githubusercontent.com/assets/3912749/14475590/5d09ea62-00c8-11e6-9be3-0b1cb419bf43.png)

**Comment by omero** [comment]
the config

**Comment by igasi** [comment]
the config?

**Comment by omero** [comment]
It looks that the `form` template always injects the `config.factory` service https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/src/Form/form.php.twig#L41

in the `generate:form:config` you need this service so, is correct, otherwise on a generic form is not necessary, any thoughts @jmolivas ?

**Comment by igasi** [comment]
Yes, in this case, is a generic form.

![screenshot from 2016-04-12 16-31-09](https://cloud.githubusercontent.com/assets/3912749/14476217/0e7341b0-00cc-11e6-9631-d77ae61f6c87.png)
![screenshot from 2016-04-12 16-29-59](https://cloud.githubusercontent.com/assets/3912749/14476226/199211a2-00cc-11e6-84a3-3567abc8fe8a.png)

You're right, we are injecting at first but it is not used in the constructor.

**Comment by omero** [comment]
:+1: for removing the line on the template at least for `generate:form` command.

**Comment by igasi** [comment]
This template only use for generate:form, or in other side?

**Comment by omero** [comment]
yes! is used on `generate:form` and `generate:form:config` commands

**Comment by igasi** [comment]
There are any way to differentiate between both?

For implements some thing this: (and send my PR)

```
{% if services is not empty %}
  public static function create(ContainerInterface $container) {
    return new static(
    {% if isDenerateFormConfigTemplate %}
      $container->get('config.factory'),
    {% endif %}
{{ serviceClassInjection(services) }}
    );
  }

{% endif %}

```

**Comment by omero** [comment]
Sorry my mistake, when looking the `FormGenerator` class https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Generator/FormGenerator.php#L42, uses a different template for configuration forms, removing only the line can work

**Comment by igasi** [comment]
Nice, Thx.

**Comment by igasi** [comment]
PR sent.

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/DrupalConsole/pull/2133
