### ISSUE TITLE
Installation issue on PHP 7.0.5: unexpected '[' in drupal.php

### ISSUE THREAD

**Issue by asauterChicago** [hechoendrupal/DrupalConsole#2132]
Tried the installation directions from the website, when I get to this step: 

`drupal init --override`

I get the following error: 

`PHP Parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/drupal/bin/drupal.php on line 56`

Also, don't know if this makes any difference, but I'm running nginx with multiple versions of PHP (I have an older 6 site that requires 5.3.29) with php fpm. The folder I'm trying to run the install is on the php 7.0.5 version.

**Comment by asauterChicago** [comment]
Huh, I just tried reinstalling it as a non-root user and it installed ok. I have other problems though. I assume because I'm running different versions of PHP, DC can't find gd, json, pdo, curl, or mysql and throws an error when I run it. 

However, that might be a legitimate config issue on my side. So I'm going to close this for now. I'll look into this further and make sure it's just not my own config before re-opening a ticket.

**Comment by jmolivas** [comment]
We have not tested on PHP 7.0, we support PHP PHP 5.5.9 same as Drupal 8 https://www.drupal.org/requirements

**Comment by asauterChicago** [comment]
@jmolivas it was my own config. My issue was that the version the command line was calling was php version 5.3.29. I updated my server to use 7.0.5 when in that site folder and no issues with Drupal Console. 

So, Drupal Console works find in php 7+, it was my own bad server config that was causing issues.

**Comment by jmolivas** [comment]
@asauterChicago glad to read that, thanks for letting me know.
