### ISSUE TITLE
Traits Directory

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#2148]
### Problem / Motivation
We should be encouraging to use trait to move some of the logic of commands into traits. However, we currently do not have a place to add those traits. All traits are unorganized at the commands directory.

### Solution
- We should move all traits to a directory call traits.
- We should fixed all namespace that are broken because of this change. 

#### UPDATES
* 2016-04-27 Assigned to: @pierregermain

**Comment by jmolivas** [comment]
We should probably: 
* Add a `src/Traits/` directory.
* Relocate all traits.
* Update references.

**Comment by pierregermain** [comment]
I would like to help here to start contributing

**Comment by darol100** [comment]
@pierregermain , if you want to start working on it. Please look at all the Traits that are at `src/Command/` and move them to  `src/Trait` then search for every single trait and change their namespace. 

If you have any question please let us know via Gitter.

**Comment by jmolivas** [comment]
@pierregermain make sure you ping us at the chat https://gitter.im/hechoendrupal/DrupalConsole

**Comment by pierregermain** [comment]
Thank you. I will let you know.

**Comment by jmolivas** [comment]
@pierregermain  Yes for now keep that `src/Helper/HelperTrait.php` where is at

**Comment by pierregermain** [comment]
So, we will call the new directory `Shared` (will update this later on my fork)

What has been done up to today ...

https://github.com/pierregermain/DrupalConsole/commits/traits_issue_2148

 - We moved the Traits to the new directory.
 - Updated the use statements
 - Updated some comments
 - Added some use statements that were not existent.

**Comment by pierregermain** [comment]
This should now be ready for Pull Request.

**Comment by pierregermain** [comment]
We will try to resolve this issue tonight:

My Notes:

#Files that use Trait in its Filename
./Command/Config/ExportTrait.php
./Command/ProjectDownloadTrait.php
./Command/MenuTrait.php
./Command/ThemeBreakpointTrait.php
./Command/CreateTrait.php
./Command/Locale/LocaleTrait.php
./Command/ConfirmationTrait.php
./Command/FormTrait.php
./Command/ChainFilesTrait.php
./Command/ThemeRegionTrait.php
./Command/EventsTrait.php
./Command/Database/ConnectTrait.php
./Command/Database/DatabaseTrait.php
./Command/ServicesTrait.php
./Command/InputTrait.php
./Command/PermissionTrait.php
./Command/ModuleTrait.php
./Command/TranslationTrait.php
./Helper/HelperTrait.php

**Comment by pierregermain** [comment]
We move the files from the command line with git

```
cd src/Command
mkdir Shared
git mv ProjectDownloadTrait.php Shared/ProjectDownloadTrait.php
git mv MenuTrait.php Shared/MenuTrait.php
git mv ThemeBreakpointTrait.php Shared/ThemeBreakpointTrait.php
git mv CreateTrait.php Shared/CreateTrait.php
git mv Locale/LocaleTrait.php Shared/Locale/LocaleTrait.php
git mv ConfirmationTrait.php Shared/ConfirmationTrait.php
git mv FormTrait.php Shared/FormTrait.php
git mv ChainFilesTrait.php Shared/ChainFilesTrait.php
git mv ThemeRegionTrait.php Shared/ThemeRegionTrait.php
git mv EventsTrait.php Shared/EventsTrait.php
git mv Database/ConnectTrait.php Shared/Database/ConnectTrait.php
git mv Database/DatabaseTrait.php Shared/Database/DatabaseTrait.php
git mv ServicesTrait.php Shared/ServicesTrait.php
git mv InputTrait.php Shared/InputTrait.php
git mv PermissionTrait.php Shared/PermissionTrait.php
git mv ModuleTrait.php Shared/ModuleTrait.php
git mv TranslationTrait.php Shared/TranslationTrait.php
```

**Comment by pierregermain** [comment]
Replace Comments

![replace comments](https://cloud.githubusercontent.com/assets/6091588/15595418/92dc7ffe-2384-11e6-9e31-efdc6bd69533.png)

**Comment by pierregermain** [comment]
Now we have to change all the use statements for every file (not 14, but 15 files because I have also added the ExportTrait.php)

**Comment by pierregermain** [comment]
But we have still to worry about use statements that are not declared ... so we search for Trait statemens manually to see if we are using Tratis without declaring it with a use statement

![searching for trait statements](https://cloud.githubusercontent.com/assets/6091588/15596143/95774ee6-238a-11e6-8122-cce8ea436a1b.png)

**Comment by pierregermain** [comment]
And when this is done we must execute drupal console to see if it is working ...

**Comment by jmolivas** [comment]
@pierregermain how did you moved those that does not work?

**Comment by pierregermain** [comment]
with git mv

**Comment by jmolivas** [comment]
how about those 
> I just noticed that the following moves did not work
```
git mv Database/ConnectTrait.php Shared/Database/ConnectTrait.php #Did not work
git mv Database/DatabaseTrait.php Shared/Database/DatabaseTrait.php #Did not work
git mv Locale/LocaleTrait.php Shared/Locale/LocaleTrait.php #Did not work
```

**Comment by pierregermain** [comment]
Tomorrow we will do it! For sure!!!

**Comment by pierregermain** [comment]
I am happy, the PR worked :)
https://github.com/hechoendrupal/DrupalConsole/pull/2398
