### ISSUE TITLE
[generate:command] container-aware command option does not result in correct ContainerAwareCommand inheritance

### ISSUE THREAD

**Issue by markdorison** [hechoendrupal/DrupalConsole#2153]
## Problem/Motivation
The `drupal generate:command` does not respect the `container-aware` option specified by the user during it's run. Regardless, of what the user selects, it generates a command class that inherits from `Command` and never `ContainerAwareCommand`.

## How to reproduce
* Use the `drupal generate:command` and when asked whether the command should be "aware of the drupal site installation when executed," specify `yes`.
* Open the command class created by the generate command and confirm that the class inherits from `Command` instead of `ContainerAwareCommand` as the [documentation specified](https://hechoendrupal.gitbooks.io/drupal-console/content/en/extending/registering-commands-automatically.html).

## Solution
The `drupal generate:command` should respect the [container-aware](https://github.com/hechoendrupal/DrupalConsole/blob/87d596b37697bceb354b64f5ecaa071db58c107f/src/Command/Generate/CommandCommand.php#L46-L51) option specified by the user.

**Comment by jmolivas** [comment]
@markdorison  Thanks a lot for filing this issue! We'll take a look at it as soon as possible!
