### ISSUE TITLE
drupal console should first check if there is a local installed drupal console and call that

### ISSUE THREAD

**Issue by Schnitzel** [hechoendrupal/DrupalConsole#2180]
If I install drupal console via phar or `composer global` it's all good.
If I now use something like https://github.com/drupal-composer/drupal-project which additionally installs me drupal console via composer locally in my local drupal site, I've got two drupal consoles installed.

So far so good, just that the local drupal console is never called, because the global installed one is used all the time.
But there are maybe cases where I need a specific drupal console for my project, when the global one does not work.

So I would have expected, that the global console first checks if there is a local console installed and if yes, actually runs that.

drush is doing that and it works great :)

http://docs.drush.org/en/master/install/

**Comment by jmolivas** [comment]
@Schnitzel Thanks looking at this 👍 sounds like a nice feature, this can help solving the issues with dependencies between global Drupal Console and Drupal site installation dependencies.

**Comment by Schnitzel** [comment]
also when this is implemented, we will install DrupalConsole as default with @amazeeio :)

**Comment by jmolivas** [comment]
Awesome. I saw the announcement today. Congrats with the new project ;)

**Comment by jmolivas** [comment]
@Schnitzel How can we test DrupalConsole with @amazeeio to make sure is working properly?

**Comment by Schnitzel** [comment]
so we have our local docker development environment which is the exact same system as we have on the production server: docker.docs.amazee.io
currently we do not install drupal console by default in there, because drupal console cannot figure out that there might be another drupal console installed (from a project like https://github.com/drupal-composer/drupal-project).

So currently the way to have drupal drupalconsole is installed:
- install it via composer
- then run it via `vendor/bin/drupal`

you can try that within the Docker if you like

**Comment by jmolivas** [comment]
@Schnitzel we are working on this project https://github.com/hechoendrupal/drupal-console-launcher to have this fixed

**Comment by marcvangend** [comment]
Thanks for working on this, I'd love to see Drupal Console follow the same pattern (check for local, fall back on global) as tools like Drush and Gulp do. Can I help test something?

**Comment by jmolivas** [comment]
Fixed @Schnitzel @marcvangend

**Comment by jmolivas** [comment]
@Schnitzel How can I test using amazee.io ?

**Comment by marcvangend** [comment]
Nice, thanks!
