### ISSUE TITLE
[drupal site:new] downloading drupal code fails if absolute path is given

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2185]
comes out that if an absolute path is given to DC, it fails to renaming the directory where to place the downloaded code.

in first place, i think is an error that DC expects a relative path, also
i think DC should check if the absolute path exists before performing the renaming

![seleccion_508](https://cloud.githubusercontent.com/assets/423279/14912927/b6fd7cac-0dff-11e6-9434-73d3f9dde0b9.png)

**Comment by novia713** [comment]
just in case were absolutely mandatory the path were relative, DC should point it out to the user in the wizard ....

**Comment by jmolivas** [comment]
This is a bug and should accept an absolute path.

**Comment by novia713** [comment]
PR sent, it's 9c15766 commit

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2191 merged
