### ISSUE TITLE
[module:download] command typo issue

### ISSUE THREAD

**Issue by naveenvalecha** [hechoendrupal/DrupalConsole#2198]
Steps are in the screenshot below.

<img width="1003" alt="screen shot 2016-05-03 at 10 47 51" src="https://cloud.githubusercontent.com/assets/2075378/14975176/d1a8203c-111c-11e6-84c3-77e1284869c6.png">

I'll work on this issue and will raise a PR for the same.

Problem :

if we did not specify the path then the console downloads the module into the **module**/contrib directory.

**Comment by jmolivas** [comment]
@naveenvalecha  This is a bug, it must use the suggested default value `modules/contrib` if no value provided during the interaction.

**Comment by jmolivas** [comment]
This is a different issue but since you will be touching the DownloadCommand class

The interactive method is using the `modulesQuestion` 
```
        if (!$module) {
            $module = $this->modulesQuestion($io);

            $input->setArgument('module', $module);
        }
```
This is not working since that method validates the entered value for the module to be an available module on the system, this should be using `$io->ask()` method instead to allow enter any value.

That value must be validated by the execution instead.

**Comment by jmolivas** [comment]
@naveenvalecha do you have any plans to work on this issue?

**Comment by naveenvalecha** [comment]
will work on this tonight.

**Comment by jmolivas** [comment]
@naveenvalecha  awesome thanks.

**Comment by naveenvalecha** [comment]
@jmolivas Here's the PR for module download path https://github.com/hechoendrupal/DrupalConsole/pull/2209
The PR also contains the punjabi translation update https://github.com/hechoendrupal/DrupalConsole/pull/2195 b/c the PR was from master to master. Hope its a translation so you can trust on me :) cc / @enzolutions 

Had to fix it in office time b/c it was annoying me everytime b/c module was getting downloaded to wrong folder.

I'll fix the interactive method is using the modulesQuestion later tonight.

**Comment by naveenvalecha** [comment]
Filed a separate issue for the above change https://github.com/hechoendrupal/DrupalConsole/issues/2212
