### ISSUE TITLE
Error generating drupal.phar

### ISSUE THREAD

**Issue by opdavies** [hechoendrupal/DrupalConsole#2199]
I'm trying to generate a local copy of the phar for development purposes using the `box build` command, but I'm getting this error.

Am I doing this the correct way?

> 07:20 DrupalConsole (use-package-version) ✗ box build
> Building...
>
> PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): unable to create pipe Too many open files' in phar:///usr/local/Cellar/box/2.7.1/libexec/box-2.7.1.phar/src/vendors/symfony/console/Application.php:954

**Comment by jmolivas** [comment]
@opdavies This is an OS configuration, try setting a higher number of this by executing `ulimit -n 10000`

**Comment by opdavies** [comment]
Great. Thanks!

**Comment by sanduhrs** [comment]
```
> ulimit -n 10000
ulimit: value exceeds hard limit
```
Everything greater than 4096 gives me the error.
