### ISSUE TITLE
[generate:entity:content] DB table not created

### ISSUE THREAD

**Issue by tnfno** [hechoendrupal/DrupalConsole#2204]
I have a problem with 1.0.0-alpha2, generate:entity:content does not generate the entity content table. Worked before, at least 2 versions ago.

No errors shown during creation, but I found this error in the dblog that might be related?
Notice: Undefined index: profile i Drupal\Console\Helper\SiteHelper->getExtensions() (linje 112 i phar:///usr/local/bin/drupal/src/Helper/SiteHelper.php)

**Comment by tnfno** [comment]
Just found this issue https://github.com/hechoendrupal/DrupalConsole/issues/1848  that probably explains the problem since my module is already installed.

The question then is how can I add entities to a running site with data?  If I uninstall the module I will lose the existing fields and data defined by the module?

**Comment by tnfno** [comment]
Just to keep answering my own question;

I have now run generate:entity:content on an enabled module and everything except the table seems to be generated OK.  I added the table manually and copied the fields from another entity added with generate:entity:content and now everything seems to work fine.  I added some fields and then entered data for the entety, and it seems OK.

SO, the question is; whey does not generate:entity:content generate the table if the module is enabled?

**Comment by darol100** [comment]
> There should be a warning when you try to run this (and maybe other) commands towards an active module.

If `generate:entity:content` was an interact command that will makes sense but not for a generator.

> SO, the question is; whey does not generate:entity:content generate the table if the module is enabled?

`generate:entity:content ` is just a boilerplate generator. This does not have any interaction with your website. For this reason, if your module needs to be enabled in order to interact to your DB.

Closing this issue, feel free to reopen if there is an issue; otherwise for support use the Gitter Channel 

:)

**Comment by lhguerra** [comment]
I might be a lot late but just came across the same issue and what was needed here was the drush entity:updates command, which isn't supported anymore, so we need to make an explicit update when adding an entity to an already installed module: https://www.nextide.ca/index.php/create-content-entity-during-update

**Comment by unpredictable-raunak** [comment]
I have Got the same problem. 
**Project Name: MyTask
Module name : Asset
Entity Name: Asset**
I created a custom entity using generate:entity:content
And I thought everything is fine and I enabled the module. 
But I was not able to entity list from structure menu. It shows 
**The website encountered an unexpected error. Please try again later.**
When I saw the log files it has error : 
**Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'MyTask.asset' doesn't exist: SELECT COUNT(*) AS expression FROM (SELECT 1 AS expression FROM {asset} base_table) subquery; Array ( ) in Drupal\Core\Entity\EntityListBuilder->getEntityIds() (line 104 of /var/www/html/MyTasks/web/core/lib/Drupal/Core/Entity/EntityListBuilder.php).**

Even I am unable to uninstaLlthe module. It shows : 
  **SQLSTATE[42S02]: Base table or view not found: 1146 Table 'MyTask.asset' doesn't exist: SELECT base_table.vid AS vid, base_table.id AS id               
  FROM                                                                         
  {asset} base_table                                                           
  LIMIT 1 OFFSET 0; Array                                                      
  (                                                                            
  )**
