### ISSUE TITLE
dependencies failure when trying to install via composer

### ISSUE THREAD

**Issue by sghinescu** [hechoendrupal/DrupalConsole#2208]
composer global require drupal/console
Changed current directory to /home/noname/.composer
Using version ^0.11.3 for drupal/console
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ocramius/generated-hydrator 1.1.1 requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.
    - ocramius/generated-hydrator 1.1.1 requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.
    - ocramius/generated-hydrator 1.1.1 requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.
    - Installation request for ocramius/generated-hydrator (locked at 1.1.1) -> satisfiable by ocramius/generated-hydrator[1.1.1].

**Comment by jmolivas** [comment]
@sghinescu based on the error message

>- ocramius/generated-hydrator 1.1.1 requires php ~5.4 -> your PHP version (7.0.4) does not satisfy that requirement.

Composer is expecting PHP equals or greater than `5.4` but smaller than `6.x` and your current PHP version is `7.0.4`
