### ISSUE TITLE
[meta] Register commands as services

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#2225]
### Problem/Motivation

Register DC core commands as services on the DC container.
### Why
- Improve command discover by using code like this: 

```
$tags = $this->container->findTaggedServiceIds('console.command');
foreach ($tags as $name => $tags) {
  $this->add($this->getContainerHelper()->get($name));
}
```
- Instead of the current FileSystem discovery [CommandDiscoveryHelper](https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Helper/CommandDiscoveryHelper.php)
##### Remove use keyword

```
use Drupal\Console\Command\Command;
# or 
use Drupal\Console\Command\ContainerAwareCommand;
```
#### Add new use keyword:

```
use Symfony\Component\Console\Command\Command;
```
#### Update class to extend from `Command`

> NOTE: Instead of `Command` or `ContainerAwareCommand`
##### Before:

```
class AwesomeCommand extends Command
# or
class AwesomeCommand extends ContainerAwareCommand
```
##### After

```
class AwesomeCommand extends Command
```
##### For commands previously extending `Command`

Add use keyword

```
use Drupal\Console\Command\Shared\CommandTrait;
```

Add use trait:

```
use CommandTrait; 
```
##### For commands previously extending `ContainerAwareCommand`

Add use keyword

```
use Drupal\Console\Command\Shared\ContainerAwareCommandTrait;
```

Add use trait:

```
use ContainerAwareCommandTrait; 
```
#### Register command class as a service at `config/services/NAMESPACE.yml`

```
awesome:
   class: Drupal\Console\Command\AwesomeCommand
    tags:
      - { name: console.command }
```

> NOTE: Make sure you get latest changes from Drupal Console repository for instructions [Keeping your fork up to date](http://docs.drupalconsole.com/en/contributing/keeping-your-fork-up-to-date.html)
##### Replace calls to any of  the helpers on the Command class

| Before | After |
| --- | --- |
| $this->getSite(); | $this->getApplication()->getSite(); |
| $this->getChain(); | $this->get('chain_queue'); |
| $this->getStringHelper(); | $this->getApplication()->getStringHelper(); |
| $this->getValidator(); | $this->getApplication()->getValidator(); |
| $this->getDrupalHelper(); | $this->get('site'); |
| $this->getKernelHelper(); | $this->getApplication()->getKernelHelper(); |
| $this->getShowFileHelper(); | $this->get('showfile'); |
| $this->getRenderHelper() | $this->getApplication()->getRenderHelper() |
| $this->getNestedArrayHelper() | $this->getApplication()->getNestedArrayHelper() |
| $this->getCommandDiscoveryHelper() | $this->getApplication()->getCommandDiscoveryHelper() |
| $this->getRemoteHelper() | $this->getApplication()->getRemoteHelper() |
| $this->getHttpClientHelper() | $this->getApplication()->getHttpClientHelper() |
| $this->getDrupalApi() | $this->getApplication()->getDrupalApi() |
| $this->getContainerHelper() | $this->getApplication()->getContainerHelper() |
#### Replace any calls:

| Before | After |
| --- | --- |
| $this->getService('SERVIDE_NAME'); | $this->getDrupalService('SERVIDE_NAME'); |
| $this->hasService('SERVIDE_NAME'); | $this->hasDrupalService('SERVIDE_NAME'); |
## Completed Namespace
- [x] Miscellaneous without Namespace. 
- [x] Breakpoints Namespace
- [x] Chain Namespace
- [x] Config Namespace
- [x] Create Namespace
- [x] Cron Namespace
- [x] Database Namespace
- [x] Develop Namespace
- [x] Exclude Namespace
-      Generate Namespace (This will be done in another issue)
- [x] Image Namespace
- [x] Libraries Namespace
- [x] Migrate Namespace (WIP)
- [x] Module Namespace
- [x] Multisite Namespace
- [x] Node Namespace
- [x] Rest Namespace
- [x] Router Namespace
- [x] Self Namespace
- [x] Settings Namespace
- [x] Site Namespace
- [x] State Namespace
- [x] Test Namespace
- [x] Theme Namespace
- [x] Update Namespace
- [x] User Namespace
- [x] Views Namespace
- [x] Yaml Namespace
  #

**Comment by jmolivas** [comment]
[plugin:debug] Register Command as a Service. #2227 by @omero

**Comment by Saphyel** [comment]
`Theme` is already merge in, and `Yaml` on the way..? #2417

**Comment by jmolivas** [comment]
Yay completed thank you all the participants on this issue
