### ISSUE TITLE
[config:delete] Delete all configuration at once

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [hechoendrupal/DrupalConsole#2228]
## Motivation
A Drupal site would contain a lot of configurations, currently we can remove by DC command one at time, however we should expose option to remove everything at once.

## Solution
Add an option and manage to remove all configuration in a single execution.

**Comment by omero** [comment]
Thanks for the PR @kenneth-bolivar-castro, i have a little question:

What is the difference between this command and only remove the folder where the configurations are located something like:

```
rm -rf /mysite/sites/default/config/*
```

**Comment by darol100** [comment]
@omero , The ability of using it on a chain command.

**Comment by kenneth-bolivar-castro** [comment]
@omero and @darol100 while I was testing behavior of new feature, I noticed It was removing "**active**" configuration, it means, it was removing configuration from database, then I decided to add new argument to define which configuration type use to delete (**Active** and **Staging**).

If we want to remove configuration from database then we should select _active_, otherwise select _staging_ to delete YAML file(s).

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2229 merged
