### ISSUE TITLE
Allow option to generate translatable content entities

### ISSUE THREAD

**Issue by SiliconMind** [hechoendrupal/DrupalConsole#2242]
When generating content entities with `generate:entity:content` the entity is always generated as non-translatable.

There should be an option asking "Is the entity type translatable?" question. Technically all that has to be done is to add proper property to entity annotation, but it would also be nice if a stub for a content translation class (inheriting from `ContentTranslationHandler`) along with translation handler annotation was also created.

**Comment by jmolivas** [comment]
New release tagged https://github.com/hechoendrupal/DrupalConsole/releases/tag/1.0.0-beta3
