### ISSUE TITLE
[generate:plugin:action]

### ISSUE THREAD

**Issue by naveenvalecha** [hechoendrupal/DrupalConsole#2247]
New feature. 
Will work on this and raise a PR

**Comment by naveenvalecha** [comment]
This was already implemented from the name of rulesaction in https://github.com/hechoendrupal/DrupalConsole/pull/707

**Comment by JPustkuchen** [comment]
@naveenvalecha Just wanted to generate an Action Plugin (like https://git.drupalcode.org/project/examples/-/tree/3.x/modules/action_example). Is "generate:plugin:rules:action" really correct for that?

If yes, I don't think this is a good name, as in [Drupal 8/9 the rules module never made it to a stable release](https://www.drupal.org/project/rules), while actions are core!

If it's the same for Rules and for Core actions, the action should be renamed or an alias should be created:
`generate:plugin:action`

Should I create a separate issue for that or should this one be reopened?

**Comment by JPustkuchen** [comment]
I now tried this command and don't think @RulesAction is === @Action( ... voting for a separate command for Drupal Core Action Plugins!

**Comment by JPustkuchen** [comment]
My result: Use `drush gen plugin-action` instead! :)
