### ISSUE TITLE
Multisite issue

### ISSUE THREAD

**Issue by wgufm** [hechoendrupal/DrupalConsole#2250]
When I use "drupal multisite:debug", I got a list of sites. But then when I use "drupal --uri=[site-name] views:plugins:debug", it didn't pick up the settings of the sub-site. I have to add http:// in front of the site name, such as "drupal --uri=http://[site-name] views:plugins:debug" so it would pick up the correct settings.

**Comment by Ashwini7** [comment]
PR raised for fix of this issue https://github.com/hechoendrupal/DrupalConsole/pull/2252

**Comment by jmolivas** [comment]
Fixed on https://github.com/hechoendrupal/DrupalConsole/pull/2252
