### ISSUE TITLE
Question description in config yml

### ISSUE THREAD

**Issue by amouro** [hechoendrupal/DrupalConsole#2270]
I want to ask about a correction in yaml.merge.yml. 
`(empty to start with merge process)` to `(cannot be empty to start the merge process)`

This correction means different as previous one, but are both of them applicable?
Does it mean: 

> To merge files, you must at least one file by answer question "other-file" and then leave empty to start the process.

https://github.com/hechoendrupal/DrupalConsole/commit/eba67882160d06a4fd6a7fff048db5dd04ca5ad9#commitcomment-17477561

**Comment by jmolivas** [comment]
@balagan73 may have a better idea of this change, not remember if was wrong and that was the reason for the change

**Comment by enzolutions** [comment]
Hi @amouro

Thanks for your contribution, this improvement was included in PR https://github.com/hechoendrupal/DrupalConsole/pull/2971 and https://github.com/hechoendrupal/drupal-console-en/pull/41
