### ISSUE TITLE
Block plugin template should use `defaultConfiguration()` for default form values

### ISSUE THREAD

**Issue by TravisCarden** [hechoendrupal/DrupalConsole#2271]
The `generate:plugin:block` command uses the following code in `templates/module/src/Plugin/Block/block.php.twig` to get default values for form elements:

```php
'#default_value' => isset($this->configuration['{{ input.name }}']) ? $this->configuration['{{ input.name }}'] : '{{ input.default_value }}',
```
The correct way to handle defaults is to specify them with `defaultConfiguration()`, like so:

```php
public function defaultConfiguration() {
  return [
    'example' => $this->t('Default value'),
  ] + parent::defaultConfiguration();
}

public function blockForm($form, FormStateInterface $form_state) {
  $form['example'] = [
    '#type' => 'textfield',
    '#title' => $this->t('Example'),
    '#default_value' => $this->configuration['example'], // <= No conditional necessary. It's always set.
  ];
  return $form;
}
```

This centralizes the values and simplifies access. (Note: The example above also runs the default value through the `t()` method, which is not done in the current template as it should be.)

**Comment by miguel303** [comment]
PR in #2477

**Comment by enzolutions** [comment]
Issue closed after PR was merged
