### ISSUE TITLE
Custom Entity overview list permission

### ISSUE THREAD

**Issue by sgurlt** [hechoendrupal/DrupalConsole#2289]
Hey,

I created a custom entity with the drupal console. After that I gave all the newly created permissions to a editor role. The editor is now able to add,delete,update the custom entities. So this works fine :)

The only thing that is not working the overview of the existing entities located at the path "admin/structure/myentity". When it try to open the url I get a access denied page.
Any thoughts?

**Comment by sgurlt** [comment]
Found the issue.
The console creates a access check in: /src/MyEntityHtmlRouteProvider.php:

`  protected function getCollectionRoute(EntityTypeInterface $entity_type) {
    if ($entity_type->hasLinkTemplate('collection') && $entity_type->hasListBuilderClass()) {
      $entity_type_id = $entity_type->id();
      $route = new Route($entity_type->getLinkTemplate('collection'));
      $route
        ->setDefaults([
          '_entity_list' => $entity_type_id,
          '_title' => "{$entity_type->getLabel()} list",
        ])
        ->setRequirement('_permission', 'administer ibe query entities')
        ->setOption('_admin_route', TRUE);

      return $route;
    }
  }`

So the access check is performed on 'administer ibe query entities'.

But the permission file that got created just got the following perms:

`add myentity entities:
  title: 'Create new myentity entities'

administer myentity entities:
  title: 'Administer myentity entities'
  description: 'Allow to access the administration form to configure myentity entities.'
  restrict access: true

delete myentity entities:
  title: 'Delete myentity entities'

edit myentity entities:
  title: 'Edit myentity entities'

access myentity overview:
  title: 'Access myentity overview'

view published myentity entities:
  title: 'View published myentity entities'

view unpublished myentity entities:
  title: 'View unpublished myentity entities'
`

The permission 'administer ibe query entities' is not created. I would suggest to add a permission same like nodes have here 'access myentity overview'.

**Comment by jlbellido** [comment]
I sent a first pull request trying to solve the issue: https://github.com/hechoendrupal/DrupalConsole/pull/2394

Thanks for reporting!

**Comment by jmolivas** [comment]
New release tagged https://github.com/hechoendrupal/DrupalConsole/releases/tag/1.0.0-beta3
