### ISSUE TITLE
[module:debug] module_name as arg should list only that module

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2292]
as user, would expect that module:debug should accept a module name as argument.
this way i'm interested only in info about that module and expect to see only info related to only that module.

**Comment by jmolivas** [comment]
@novia713  You mean to show detailed information about the module ?

**Comment by novia713** [comment]
i mean this, instead of doing _drupal module:debug | grep taxonomy_
![seleccion_597](https://cloud.githubusercontent.com/assets/423279/15404850/b2213718-1dff-11e6-9f72-4ae7dab44736.png)

**Comment by darol100** [comment]
@novia713 We recommend users to use [Peco](https://github.com/peco/peco). I do not think we should change the behavior of our debugs commands.  If you need to filter something use Peco. 

It makes sense to use as argument and it will display more information about the project, such as the description of the module and/or any other specify info of the module.

**Comment by darol100** [comment]
What it will be cool is to added a filtering tool like Peco to the console. For all debug commands. 

So users can do .... `module:debug --search` and it will show something similar to Peco.

**Comment by jmolivas** [comment]
I see this more like a detailed information as result than a filter similar to `router:debug` command:

![](https://monosnap.com/file/csg0YOZBJoCbQFT9Mi0lKDvs1cvWpq.png)

**Comment by novia713** [comment]
well, initially my use case was to know roughly if i already installed a module or not.
just knowing if it is installed on my project or not: i bet i can survive with just _grep_ ...

i will look into Peco, and i will try to integrate it as option [--search]

i like also the argument possibility as detailed info,
but right know i can not see myself capable of doing something like that ^^
i would need some guidance on how to accomplish that with no doubt.

i stay after this issue with a taste a bit bitter, because i conclude from your words that there is no way to know quickly if i have a given and specific module installed or not :disappointed:

**Comment by jmolivas** [comment]
@novia713  We currently have some filter for this command you can see using `--help`
```
drupal module:debug --help

Usage:
  module:debug [options]

Options:
      --status[=STATUS]  Module status [enabled|disabled]
      --type[=TYPE]      Module type [core|no-core]

...

Help:
 Display current modules available for application
```

If you are interested in passing a module name argument and showing a detailed information. I can guide you on how to write the code.

**Comment by novia713** [comment]
PR for module info (module name as argument) in #2343

**Comment by novia713** [comment]
seems that this line doesn't work no more
`$data = $this->getApplication()->getHttpClientHelper()->getUrlAsJson($url);`

so i include a change in that line including the repo domain before `$url`
note that searching in _packagist.org_ doesn't work sometimes because some modules there are not present there

so i put as repo url to search `https://packagist.drupal-composer.org` but given this repository is taken as obsolete by the own owner, i firmly suggest to change it further in time to `https://packages.drupal.org/8`

PR at #2460
