### ISSUE TITLE
Tokens in a translation sentence need to be distinct

### ISSUE THREAD

**Issue by amouro** [hechoendrupal/DrupalConsole#2293]
I'm doing the translation for Chinese Traditional. We may have different order in the sentence to express the idea.

In the update.execute.yml, there are same token in a sentence, and the first one is always the number while the second one is the module name.

`executing-update: 'Executing update function %s of module %s'`
`// Executing update function 8001 of module sample`

Is it possible to make them identical?

**Comment by jmolivas** [comment]
@amouro what do you mean by identical? the placeholder `%s` ?

**Comment by amouro** [comment]
@jmolivas, sorry for the wrong description. I actually think the placeholder need to be different to be able to use them in different order.

**Comment by jmolivas** [comment]
@amouro you mean the `%s`? since we use [sprintf](http://php.net/manual/en/function.sprintf.php) what is important is the order of them and how you pass the values when executing the `sprintf` function.

**Comment by amouro** [comment]
@jmolivas Yes I mean the %s.

Your reference for sprintf actually solve my problem. I've checked the how drupalconsole render the msg and I'm now able to swap the placeholder by using the _$n position specifier_. 

See **Example 4 Argument swapping** in [`sprintf`](http://php.net/manual/en/function.sprintf.php)

`executing-update: 'Executing update function %s of module %s'` 
is equal to 
`executing-update: 'Executing update function %1$s of module %2$s'`

`%1$s` will always return the Update N, and `%2$s` is always the module name

Hope this can help the other translations

**Comment by jmolivas** [comment]
@amouro feel free to close the issue if no more questions.

**Comment by amouro** [comment]
Reopen to try to update the update:execute command message
