### ISSUE TITLE
[site:status] is broken

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2310]
i'm using Drupal Console (1.0.0-alpha2) and site:status is broken

![seleccion_601](https://cloud.githubusercontent.com/assets/423279/15448162/40d3ad96-1f5a-11e6-9147-73da32673259.png)

**Comment by novia713** [comment]
i think this is the conflictive line:
https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Site/StatusCommand.php#L94

**Comment by jmolivas** [comment]
@novia713 do you have pathauto installed?

**Comment by novia713** [comment]
no, sir

**Comment by jmolivas** [comment]
@novia713  Do you mind to share a list of the installed modules on the site?

**Comment by novia713** [comment]
here you are 
http://paste.fedoraproject.org/369408/46385999

**Comment by enzolutions** [comment]
I can't reproduce the error @novia713 could you confirm , this is still an issue for you.

**Comment by novia713** [comment]
seems it works for me now
