### ISSUE TITLE
[Aliases] are broken

### ISSUE THREAD

**Issue by Saphyel** [hechoendrupal/DrupalConsole#2323]
So I'm using Ubuntu 16 with PHP7.0 (last version) and I follow [this tutorial](https://github.com/hechoendrupal/DrupalConsole#getting-the-project-to-contribute)

I created a custom command (it's the `ipr:default` generated by drupal console by the way) and I get this error ... also when I use aliases is broken as well.
I uploaded a capture for make easy to understand my issue :)

![screenshot from 2016-05-25 19-09-48](https://cloud.githubusercontent.com/assets/5764721/15551239/06e44716-22ad-11e6-8714-67d52884b426.png)

**Comment by jmolivas** [comment]
@Saphyel:

- Did you installed DC using the installer or cloning the project?
- Did you run drupal init ?

**Comment by Saphyel** [comment]
@jmolivas cloning and yes

**Comment by jmolivas** [comment]
That is why, for now on master I got the aliases disabled

**Comment by Saphyel** [comment]
@jmolivas and about the custom command?

**Comment by jmolivas** [comment]
@Saphyel Same, since I am overriding aliases to []
https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Application.php#L341

**Comment by Saphyel** [comment]
ok, thanks for the quick answer! keep me update when everything is back! ^^
