### ISSUE TITLE
[ProyectDownloadTrait] configurable options in YML config for use several modules repositories when install modules with Composer

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2330]
this $repoUrl https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/ProjectDownloadTrait.php#L19

should be a yml value in config file, giving the user the option to choose which repository for modules to use.

the most common options would be:

- https://packages.drupal.org/8
- https://packagist.drupal-composer.org
- any custom URL the user provides

afaik, the d.o repo should be the default one ...

**Comment by jmolivas** [comment]
@novia713 +1 on this but I think for now `https://packagist.drupal-composer.org` must be the default one

**Comment by novia713** [comment]
PR in #2341

working with the following key in the config.yml
![seleccion_646](https://cloud.githubusercontent.com/assets/423279/15606932/5d7406d0-240f-11e6-8329-5db02d1db679.png)


//@TODO: **drupal init** should set this value.
i would need some hints about how to accomplish this.

**Comment by novia713** [comment]
perhaps drupal init would have an interactive behaviour in order to giving the user the opportunity to choose which composer repo to use and enter a custom url if desired.

also from where download drupal installs, if he/she wants to use Composer and (if installed) where is it, etc ....


all this user choices would be written in the config.yml by drupal init

**Comment by ryanaslett** [comment]
FYI: packages.drupal.org/8 is now beta, and packagist.drupal-composer.org will eventually be deprecated.
