### ISSUE TITLE
Add support for build command

### ISSUE THREAD

**Issue by guiajlopes** [hechoendrupal/DrupalConsole#2342]
Hello Guys, What do you think about add a command to build the whole project? It's like the command that kraftwagen do. For example we can create a yml file on project and specify the command to run on build and when run drupal build it run all the command

For example the drupal build can run:
composer install
npm install
gulp build 

etc. The user can specify in the yml file the commands and drupal console just run.

What do you think about it? If you guys like it I can implement it

**Comment by jmolivas** [comment]
@guiajlopes sounds interesting let's discuss this.

**Comment by darol100** [comment]
@jmolivas , @guiajlopes ... Bash in YML ? lol

**Comment by guiajlopes** [comment]
@darol100 no, just the command to run, take a look at platform cli

https://github.com/platformsh/platformsh-cli

they have a .plaform.app.yaml

take a look in a example of build and deploy commands

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      cd profiles/kic_profile/themes/kaplan_blog
      npm install
      gulp build

    # We run deploy hooks after your application has been deployed and started.
    deploy: |
      cd public
      redis-cli -h redis.internal FLUSHALL
      drush -y updatedb
      drush fra -y
      drush config-import -y
      drush cr -y

**Comment by jmolivas** [comment]
@guiajlopes I am totally in. We can take advantage of: 

* DrupalComposer => https://github.com/drupal-composer/drupal-project
* Composer scripts => https://gist.github.com/jmolivas/318b3d251f71510dd213#file-composer-json-L91
* Drupal Console `chain` command => http://docs.drupalconsole.com/en/commands/chain.html

The chain command helps you to automate command execution, allowing you to define an external YAML file containing the definition name, options and arguments of several commands and execute that list based on the sequence defined in the file.

YAML file example => https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/chain/site-update.yml 

This YAMLs files supports 
* Placeholders
https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/chain/quick-start-db.yml

* ENV vars
https://github.com/hechoendrupal/DrupalConsole/blob/master/config/dist/chain/quick-start-db-env.yml

* And we are planning to support this:
https://github.com/hechoendrupal/DrupalConsole/issues/2267

**Comment by jmolivas** [comment]
@guiajlopes any plans to keep working on this?

**Comment by guiajlopes** [comment]
Actually I didn't start it, but I plan to do when I have time

**Comment by jmolivas** [comment]
OK i will try to discuss this on the TwincCities Camp this week and try to get more ideas about this feature.

**Comment by guiajlopes** [comment]
thanks @jmolivas

**Comment by guiajlopes** [comment]
Just to let you know, I already started it on one fork repository here: https://github.com/guiajlopes/DrupalConsole

If anyone like to help 
Thank you guys

**Comment by Saphyel** [comment]
Now thanks to this command is possible to build a project running only one build.yml : #2444

**Comment by guiajlopes** [comment]
@Saphyel the exec command on #2444 already do this build?

**Comment by Saphyel** [comment]
@guiajlopes you can add in the yml file something like this:
```yml
  - command: exec
    arguments:
      bin: 'npm install theme/custom/blabla'
```

**Comment by guiajlopes** [comment]
@Saphyel it's an idea or it's already done?

**Comment by guiajlopes** [comment]
Closing this issue because we can do it with the exec command. Ex: create a file called build.yml put it inside the build.yml file

```
commands:
  - command: exec
    arguments:
      bin: 'ls -lah'
  - command: exec
    arguments:
      bin: 'ls -l'
```

and run drupal chain --file=build.yml
