### ISSUE TITLE
[package] composer commands

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2353]
I think we need discuss which **Composer's commands** we need to shortcut.
My proposal is:

|  now implemented  | proposed implementation |  composer correlation  |
|---|---|---|
|  site:new  |   |  create-project  |
|  _module:*_  |  -  |  - |
|  module:download  |  package:download  |  composer require  |
|  module:uninstall  |  package:remove  |   composer remove  |
|  module:debug  |  package:debug  |   composer show |
|  module:debug modulename |  package:debug modulename |  composer show modulename  |
|  module:search  |  package:search |  composer search  |
|  module:update  |  package:update |  composer update |
|  _theme:*_  |  -  |  - |
|  theme:download  |  package:download  |  composer require  |
|  theme:uninstall  |  package:remove  |   composer remove  |
|  theme:debug  |  package:debug  |   composer show |
|  theme:search  |  package:search |  composer search  |
|  theme:update  |  package:update |  composer update |

`site:new` i don't know how to call it, but works with composer.
`module:install` has nothing to do with composer
`module:uninstall` should manage only Drupal related things while `package:remove` should remove the package from _composer.json_

i would add:
`drupal package:outdated` to see outdated packages

so for installing a module i would do 2 steps:

1. `drupal package:download token`
2. `drupal module:install token`

and for uninstalling, the contrary:
`drupal module:uninstall token` (do things with database, etc..)
`drupal package:remove token`

what do you think, @darol100 , @jmolivas ?

**Comment by darol100** [comment]
@novia713 , If all these proposed commands are wrappers to Composer, I do not think we should do that. 

Why ? I remember @bojanz mentioning that  [Composer Manager](https://www.drupal.org/project/composer_manager) was built to help the user with Composer and what it ended up doing it was actually doing is confusing the user. Because they never had an understanding of how Composer works. And they look at Composer Manager like this black box that do magic.

IMO, I think if these commands are doing the same functionality as Composer (without anything custom) we are going to end up with the same issue as Composer Manager. At this point, we should let the user use composer and not Drupal Console.

What you guys think ?
@novia713 , @jmolivas

**Comment by novia713** [comment]
yeah, i get your point, @darol100. also managing Composer with DC adds more work and more code to mantain...

my first idea was that «_a only tool for managing a problem is better than two tools_», so people still don't know how to deal with Composer would be able to do all the things with DC ...

but i'm totally unsure about what to do right now ... can we get attention of more people about this?

i think that for doing things in D8 is totally necessary using Composer, so if we document clearly how to accomplish regular tasks using Composer and DC, wrapping Composer with DC would be redundant & innecessary ... but then a clear documentation about mixing the two tools is  mandatory. Something like a "user guide" on how to do usual tasks illustratring how to deal with composer and DC together ...

lastly, besides a new command like «**package:xxx**» would be too much work and redundant, i would not remove the existent behaviour _--composer_ in «**module:xxx**», perhaps (i'm not really sure about this, too) like an option (shortcut) for power-users...

**Comment by jmolivas** [comment]
I know having DC commands to run Composer command looks like a duplicated effort and work, but this may help to advocate usage of a more modern approach to manage packages know as modules, themes, profiles aka extensions on the Drupal lingo.

We can show the executed Composer command on the CLI to clarify what is the command doing as we currently do on `database:dump` & `database:client` when using the `--learning` option. 

This is for me is more a temporary shortcut solution while people get used to using composer.

**Comment by jmolivas** [comment]
@novia713 `site:new` is like composer `create-project`

**Comment by novia713** [comment]
theme:download --composer PR at #2414
