### ISSUE TITLE
[generate:entity:content] Entity created isn't translatable

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalConsole#2354]
After activate many languages on site. The entities created aren't translateables

**Comment by jlbellido** [comment]
Following

**Comment by oskarcalvo** [comment]
Following

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2393 merged

**Comment by jmolivas** [comment]
New release tagged https://github.com/hechoendrupal/DrupalConsole/releases/tag/1.0.0-beta3
