### ISSUE TITLE
[console:server] help msg is not rendered

### ISSUE THREAD

**Issue by amouro** [hechoendrupal/DrupalConsole#2356]
<img width="545" alt="2016-05-30 23 50 45" src="https://cloud.githubusercontent.com/assets/3444618/15653752/5f8cefb8-26c1-11e6-97e7-d56e8c8e3b23.png">

help text for argument `address` is not correctly rendered. This happens in English and zh_hant.
I've checked the ServerCommand.php, but couldn't find an error.
<img width="520" alt="2016-05-30 23 52 53" src="https://cloud.githubusercontent.com/assets/3444618/15653784/af32599a-26c1-11e6-9316-868e719bcd04.png">

**Comment by darol100** [comment]
@amouro , Which language do you have it set ? Sometimes, if you change the language and that key is not available in the language you will get that error.

**Comment by amouro** [comment]
It happens both English and my working language zh_hant.
The key is correct in both language.

**Comment by jmolivas** [comment]
@amouro I saw it and found this happens on every command the `arguments` are not translated. This issue does not affect the command `options`.

**Comment by stevepurkiss** [comment]
@jmolivas I'm getting this on my `--detailed` option - also included screenshot of `config:import` as that has a `--remove-files` option which also isn't displaying the text:

![field-info-help](https://cloud.githubusercontent.com/assets/6438292/17447675/b363a860-5b47-11e6-9329-fad469ee0fb3.png)


![config-import-help](https://cloud.githubusercontent.com/assets/6438292/17447655/a1640e8e-5b47-11e6-8909-9fd3e7a7d5f7.png)

**Comment by jmolivas** [comment]
@stevepurkiss I will have time next week to take a look at this issue.

**Comment by stevepurkiss** [comment]
@jmolivas cool thanks - will let you know if I see anything along the way!

**Comment by jmolivas** [comment]
I will back to DrupalConsole mode starting Monday next week.

**Comment by jmolivas** [comment]
I just fixed this issue, this will be included on next release RC-1 ETA early next week.

@amouro 
![drupal-help-server](https://cloud.githubusercontent.com/assets/366275/17451289/821f2bb2-5b1a-11e6-88e2-df91c3679d00.png)

@stevepurkiss  
![drupal-help](https://cloud.githubusercontent.com/assets/366275/17451304/9a2319c6-5b1a-11e6-9542-84613e7fa28d.png)

**Comment by stevepurkiss** [comment]
Awesome!!

**Comment by enzolutions** [comment]
Fixed
