### ISSUE TITLE
[translation] Incorrect address:port format in example msg of server.xml

### ISSUE THREAD

**Issue by amouro** [hechoendrupal/DrupalConsole#2366]
The address in example description  (`127.0.0.1.8088`) is not in the correct format of `address:port`
I want to check if this is actually a typo before I sending the PR to patch all languages.

https://github.com/amouro/DrupalConsole/commit/b922f4d9fabb9f01b61eb08d3214cca54392f658

**Comment by jmolivas** [comment]
Yes is a typo must be `:` instead of `.`
