### ISSUE TITLE
Fatal Error on theme:download - undefined method DownloadCommand::get

### ISSUE THREAD

**Issue by bshaffer** [hechoendrupal/DrupalConsole#2386]
My tests are failing because of an undefined method error when running `drupal theme:download`:

```sh
$ ./drupal theme:download bootstrap 8.x-3.0-beta2
 Downloading theme bootstrap release 8.x-3.0-beta2
PHP Fatal error:  Call to undefined method Drupal\Console\Command\Theme\DownloadCommand::get() in phar:///private/tmp/drupaltest/drupal/src/Command/ProjectDownloadTrait.php on line 175

Fatal error: Call to undefined method Drupal\Console\Command\Theme\DownloadCommand::get() in phar:///private/tmp/drupaltest/drupal/src/Command/ProjectDownloadTrait.php on line 175
```

[here](https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/ProjectDownloadTrait.php#L175) is the offending line.

**Comment by bshaffer** [comment]
Looks like this is fixed in `master`. Can we tag another release so the installer at https://drupalconsole.com/installer is not broken?

**Comment by jmolivas** [comment]
@bshaffer which DC version are you using?

**Comment by bshaffer** [comment]
@jmolivas `1.0.0-beta1` (I am downloading and installing from https://drupalconsole.com/installer )

**Comment by jmolivas** [comment]
This PR https://github.com/hechoendrupal/DrupalConsole/pull/2382 contains the fix. This will be included on 1.0.0-beta2.

**Comment by bshaffer** [comment]
Do you know when beta2 will be tagged? Until then, the installer at https://drupalconsole.com/installer is broken.

**Comment by jmolivas** [comment]
@bshaffer I will tag a new release later on today.

**Comment by bshaffer** [comment]
thank you!

**Comment by bshaffer** [comment]
Can you tag the `1.0.0-beta2` release?

**Comment by jmolivas** [comment]
@bshaffer Just tagged few minutes ago. Can you confirm this fixed your issue?

**Comment by bshaffer** [comment]
it works! thank you @jmolivas !!
