### ISSUE TITLE
Feature Request: Devel dumper change command

### ISSUE THREAD

**Issue by twhiston** [hechoendrupal/DrupalConsole#2389]
Proposed feature: command to switch the devel dumper on the site

Use Case: Its pretty easy to run out of memory with kint debugging and sometimes its useful to be able to quickly switch between dumpers

Status: Command available in https://github.com/twhiston/DrupalConsole/tree/devel-dumper

**Comment by enzolutions** [comment]
Command will be restored at release 1.0.0-rc10
