### ISSUE TITLE
[module:download] & module:update doesn't work with Composer

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2395]
i've found several issues using _--composer_ option with _module:download_ and _module:update_

1. This line https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/ProjectDownloadTrait.php#L288 afaik is wrong, because `application.composer.repositories` is an array. We need in this case `application.composer.repositories.default`. This was malforming the url repo for Composer, so i corrected this.

2. Once Composer is working, its output is not now shown. This is bad, because _Composer_ is an interactive command and may ask the user for interaction. I did several enhancements to show the Composer output in **Utils/ShellProcess.php**.

3. Regarding point 2., would be cool to _$io->info()_ the output, but i was not able to use _$io_ into **Utils/ShellProcess.php** :(

4. I firmly suggest change `application.composer.repositories.default` to `application.composer.repositories.packages` so it would be much more clear

**Comment by novia713** [comment]
i also did some enhancements in md & mu string files.
PR in #2396

**Comment by novia713** [comment]
i don't get why `application.composer.repositories` is an array nor why we have _default_, _drupal_ & _packagist_, but perhaps would be good idea create an option for power-users as _--repository=drupal_
for choosing one of the three, overriding the default one. 

right now in my PR i'm doing
`$this->setComposerRepositories("default");`
so one would can easly do
`$this->setComposerRepositories($input->getOption('repository'));`

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2396 merged

**Comment by jmolivas** [comment]
@novia713 Why this was re-opened ?

**Comment by novia713** [comment]
i can't remember well. maybe this issue proposes many things and in that moment i were thinking in attach to this more PRs

i think we can close it already. i close it.
