### ISSUE TITLE
Method not found error on router:debug

### ISSUE THREAD

**Issue by nmeegama** [hechoendrupal/DrupalConsole#2400]
When I run
drupal router:debug [route name]
I get the following error
Error: Call to undefined method Drupal\Console\Command\Router\DebugCommand::getRouteProvider() in phar:///usr/local/bin/dc/src/Command/Router/DebugCommand.php on line 67
Error: Call to undefined method Drupal\Console\Command\Router\DebugCommand::getRouteProvider() in Drupal\Console\Command\Router\DebugCommand->getRouteByNames() (line 67 of phar:///usr/local/bin/dc/src/Command/Router/DebugCommand.php).

PHP Version : 7.0
OS X Version 10.11

Does anyone know how to solve this

**Comment by jmolivas** [comment]
Thanks a lot for filing this issue!. I got if fixed sending a PR, this fix will be included on the next release.

**Comment by jmolivas** [comment]
@nmeegama Thanks a lot for filing this issue!. I got if fixed sending a PR, this fix will be included on the next release.

**Comment by jmolivas** [comment]
PR sent https://github.com/hechoendrupal/DrupalConsole/pull/2402

**Comment by nmeegama** [comment]
@jmolivas, glad to be able to help the project this way at least. Kudos on the project BTW. We owe you big time :)

**Comment by jmolivas** [comment]
New release tagged https://github.com/hechoendrupal/DrupalConsole/releases/tag/1.0.0-beta3
