### ISSUE TITLE
[generate:twig:extension] Expose TwigExtension

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [hechoendrupal/DrupalConsole#2403]
**Problem/Motivation**
We could [create custom TwigExtension](http://keboca.com/node/4), but we don't have command for that yet, then let's get down to work

**Solution**
We could create a new command to expose a new service as TwigExtension within Drupal.

**Comment by jmolivas** [comment]
@kenneth-bolivar-castro Awesome, as mentioned before I will love to see as part of Drupal Console core commands.

**Comment by darol100** [comment]
👍 on this.

**Comment by darol100** [comment]
This have been fixed.
