### ISSUE TITLE
[generate:form:config] text_format type

### ISSUE THREAD

**Issue by ismaeil** [hechoendrupal/DrupalConsole#2407]
Hi,
using generate:form:config, in the form structure, i can add form elements of type 'textarea' or 'textfield' but i can't use the type text_format.
can we please support it too ?

Thanks for this awsome project

**Comment by enzolutions** [comment]
@ismaeil Thanks for your suggestion. but Form must follow the FAPI elements in Drupal 8 as you can see in https://www.drupal.org/node/2117411

text_format is not a valid element.

**Comment by ismaeil** [comment]
Hello,
actually it's listed in the Drupal 8 FAPI elements https://api.drupal.org/api/drupal/elements
https://api.drupal.org/api/drupal/core!modules!filter!src!Element!TextFormat.php/class/TextFormat/8.2.x

**Comment by enzolutions** [comment]
OK we will work in include

**Comment by jlbellido** [comment]
I think https://github.com/hechoendrupal/DrupalConsole/pull/2453 solves this issue.

**Comment by enzolutions** [comment]
Closing issue
