### ISSUE TITLE
cron:execute all does not update site

### ISSUE THREAD

**Issue by krknopp** [hechoendrupal/DrupalConsole#2408]
I'm using `drupal cron:execute all` to run crons on a Drupal 8 site and it's not updating the last run on admin/config/system/cron or the admin/reports/status page.

```
drupal cre all
 Executing cron function of module comment
 Executing cron function of module dblog
 Executing cron function of module field
 Executing cron function of module file
 Executing cron function of module history
 Executing cron function of module node
 Executing cron function of module search
 Executing cron function of module system
 Executing cron function of module update


 [OK] All cron implementations requested were executed successfully


 // cache:rebuild

 Rebuilding cache(s), wait a moment please.


 [OK] Done clearing cache(s).
```

**Comment by andrewbelcher** [comment]
It also doesn't implement the lock (though there is a command to release the lock) or process queues as `\Drupal\Core\Cron::run` does (and there isn't a separate command providing that)... This means it can't be used in a crontab for example...

**Comment by enzolutions** [comment]
I just did a PR https://github.com/hechoendrupal/DrupalConsole/pull/2464 to fix two reported issues, thanks @andrewbelcher and @krknopp
