### ISSUE TITLE
route:debug PHP Fatal Error

### ISSUE THREAD

**Issue by fadehelix** [hechoendrupal/DrupalConsole#2441]
When I want to debug particular route, for example: _drupal route:debug  entity.user.edit_form_ 
I get following error:
_PHP Fatal error:  Call to undefined method Drupal\Console\Command\Router\DebugCommand::getRouteProvider() in phar:///usr/local/bin/drupal/src/Command/Router/DebugCommand.php on line 67_

Drupal Console version 1.0.0-beta2

**Comment by enzolutions** [comment]
@fadehelix I can't reproduce the error, maybe its your PHP version or local environemnt

**Comment by enzolutions** [comment]
@fadehelix if you don't provide more information this ticket will be close
