### ISSUE TITLE
[module:debug] Update the value for module status

### ISSUE THREAD

**Issue by dinarcon** [hechoendrupal/DrupalConsole#2443]
Per https://www.drupal.org/node/2193013, modules cannot be in a disabled state anymore, only installed and uninstalled.

The `module:debug` command still uses `Enabled/Disabled` for indicating site status. Let's change this to `Installed/Uninstalled`.

This issue was pointed out by @jmolivas during the Drupal 8 Module Development training at Twin Cities Drupal Camp 2016.

**Comment by jmolivas** [comment]
@dinarcon  Thanks for filling the issue.
