### ISSUE TITLE
Remove target from --generate-chain export

### ISSUE THREAD

**Issue by dinarcon** [hechoendrupal/DrupalConsole#2449]
### Problem / Motivation

If you have run `drupal site:import:local` to configure an alias, when you run a command using the `--generate-chain` option the `target` is included as part of the output. `target` should not be part of the export.

This issue was pointed out by @jmolivas during the Drupal 8 Module Development training at Twin Cities Drupal Camp 2016.

**Comment by enzolutions** [comment]
Teste in latest version of Drupal Console 1.0.0-rc9 dev version , this behavior is not happening any more.
