### ISSUE TITLE
[generate:service] Check that the specified service name has not been taken already

### ISSUE THREAD

**Issue by dinarcon** [hechoendrupal/DrupalConsole#2452]
### Problem / Motivation

When generating a service, it is possible to specify the name of an existing service.
### Solution

Validate that the specified service name has not been taken already.

This issue was pointed out by @darol100 during the Drupal 8 Module Development training at Twin Cities Drupal Camp 2016.

**Comment by miguel303** [comment]
PR sent in #2455

**Comment by enzolutions** [comment]
Solved in 1.0.0-beta4

**Comment by darol100** [comment]
Great work guys...
