### ISSUE TITLE
[migrate:debug] The "migration" entity type does not exist.

### ISSUE THREAD

**Issue by jmuzz** [hechoendrupal/DrupalConsole#2470]
I am getting this error message when attempting to run drupal migrate:debug

  [Drupal\Component\Plugin\Exception\PluginNotFoundException]  
  The "migration" entity type does not exist.

Tried it in clean installs of the latest drupal 8.1.x and 8.2.x after enabling migrate modules.

**Comment by jmuzz** [comment]
I got migrate_plus and it seems to be working better.  Maybe it could say something about migrate_plus.  It told me I needed the migrate module when I tried to run it the first time.

**Comment by enzolutions** [comment]
Fixed in PR https://github.com/hechoendrupal/DrupalConsole/pull/2493

**Comment by enzolutions** [comment]
Issue closed after issue merged and will be released in Beta4
