### ISSUE TITLE
[migrate:setup] You have requested a non-existent service "state".

### ISSUE THREAD

**Issue by jmuzz** [hechoendrupal/DrupalConsole#2471]
I am getting this error after running drupal migrate:setup and inputting values up to Files Directory.  After that it shows

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "state".

Tried it on a clean install of latest Drupal 8.1.x after enabling migrate modules.

For what it's worth I ran through migrate UI after with the same values and the migration completed.

**Comment by jmuzz** [comment]
I tried it after enabling migrate_plus and migrate_tools as well but the error persists.

**Comment by jmolivas** [comment]
pinging @enzolutions and @miguel303 since they are working on improving the `migrate` commands

**Comment by enzolutions** [comment]
That command will be removed in 1.0 release as part of  https://drupalconsole.com/articles/help-us-complete-drupal-console

**Comment by enzolutions** [comment]
Fixed in PR https://github.com/hechoendrupal/DrupalConsole/pull/2493

**Comment by enzolutions** [comment]
Issue closed after issue merged and will be released in Beta4
