### ISSUE TITLE
 drupal router: rebuild

### ISSUE THREAD

**Issue by edwinvalencia05** [hechoendrupal/DrupalConsole#2479]
how to make a registry rebuild, I have dealt with drupal router: rebuild and have this

[Symfony \ Component \ Console \ Exception \ CommandNotFoundException]
There are no commands defined in the "router" namespace.

**Comment by enzolutions** [comment]
Hi @edwinvalencia05 that error is because are you trying to execute that command outside a Drupal installation, try change the directory or pass the directory path using the option --root=xxxx
