### ISSUE TITLE
[generate:plugin:field-widget] Generate a new Field Widget

### ISSUE THREAD

**Issue by AxelBriche** [hechoendrupal/DrupalConsole#248]
Hello, it's possible with Console to create a new Field Widget please ?
Example: a field of type Media for upload images and video from youtube, vimeo, etc.

Thanks.

**Comment by jmolivas** [comment]
This is what you where asking the other day @enzolutions, about generating new field widget and @dmouse mentioned is working please related any PR to this issue.

**Comment by jmolivas** [comment]
@AxelBriche I rather like to have a separated issues for each Field Widget requested and link to the d.o. section or a working code example.

**Comment by Sutharsan** [comment]
We now have:
```
generate:plugin:field             Generate field type, widget and formatter plugins.
generate:plugin:fieldformatter    Generate field formatter plugin.
generate:plugin:fieldtype         Generate field type plugin.
generate:plugin:fieldwidget       Generate field widget plugin.
```
I guess we can close this issue.

**Comment by jmolivas** [comment]
This was included on PR https://github.com/hechoendrupal/DrupalConsole/pull/753

Thanks for the PR and notice @Sutharsan
