### ISSUE TITLE
[create:nodes] Passing an invalid content type machine name produces faulty nodes

### ISSUE THREAD

**Issue by dinarcon** [hechoendrupal/DrupalConsole#2483]
### Problem

The `create:nodes` command accepts as argument the machine name of the content type to create demo nodes for. If you pass as argument a string that does not matches the machine name of any valid content type, the command will generate nodes that can be seen in the `/admin/content` page. However, these nodes are listed without a specific content type and they cannot be seen, edited, or deleted via the user interface.

### Proposed solution

Check if the argument passed corresponds to the machine name of an existing content type on the system. If that check fails, show an error message and abort the command execution.

**Comment by sag13684** [comment]
Could you please check if my commit fixes this?

**Comment by jmolivas** [comment]
@sag13684 do you mind to send a PR ;)

**Comment by sag13684** [comment]
thanks, added a pull request.

**Comment by enzolutions** [comment]
Close issue after PR was merged
