### ISSUE TITLE
Drupal installation error

### ISSUE THREAD

**Issue by asathcol78** [hechoendrupal/DrupalConsole#2488]
I am following the instructions to install the console. After trying to execute any command I get this error:
```
andress-mbp:~ andres$ sudo drupal init --override

Parse error: parse error in phar:///usr/local/bin/drupal/src/Command/Config/DeleteCommand.php on line 168
andress-mbp:~ andres$
```
I assume I am getting the latest release.

Thanks guys, great job!

**Comment by enzolutions** [comment]
Hi @asathcol78 

Thanks for your report, but there is not an error, the problem is your PHP version.

The line reported as an error use a PHP directive [yield](http://php.net/manual/en/language.generators.syntax.php) introducing in PHP 5.5+ 

Verify your php version, as you can see below

```bash
$ php --version
PHP 5.5.31 (cli) (built: Jan 11 2016 23:27:33)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```
