### ISSUE TITLE
generate:entity:content fail to module name recognition

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalConsole#249]
When I try generate content entity the console prompt ask for module name. The console doesn't autocomplete the module name and when type this the console fail:
Error message:
 Module "mimodulo" is invalid. You can use first generate:module command. 

but the module exist.

**Comment by vacho** [comment]
Yes this issue has been solved.. Thanks.

**Comment by jmolivas** [comment]
Thanks for confirming @vacho
