### ISSUE TITLE
Not compatible with metatag

### ISSUE THREAD

**Issue by podarok** [hechoendrupal/DrupalConsole#2496]
```
vagrant@precise64:/var/www/docroot$ drupal init --override
PHP Fatal error:  Trait 'Drupal\Console\Command\ServicesTrait' not found in /var/www/docroot/modules/contrib/metatag/src/Command/GenerateTagCommand.php on line 28
```

when there is a metatag module installed

**Comment by miguel303** [comment]
this is the issue for metatag module https://www.drupal.org/node/2760661  and the patch is here https://www.drupal.org/files/issues/drupal-consol_2760661.patch , so you can try using the development version of module , apply the patch and test again.

**Comment by enzolutions** [comment]
Fixed in contrib module
