### ISSUE TITLE
Don't export _core and default_config_hash

### ISSUE THREAD

**Issue by mariano-dagostino** [hechoendrupal/DrupalConsole#2544]
When using the commands of the family config:export:\* it would be nice to have the chance to strip the values:

> _core:
>     default_config_hash: 8DPjvg7y7dEwtd5-tDKxx8ImqA17KhUktZXIEO-RR6w

Features already did this in https://www.drupal.org/node/2668526

**Comment by jmolivas** [comment]
@mariano-dagostino We can probably add a new option to remove this information `--remove-hash`.

**Comment by enzolutions** [comment]
@jmolivas I just implemented as default, because is the same reason why we don't export state

Thanks @mariano-dagostino for your feedback.

Resolved and merged at https://github.com/hechoendrupal/DrupalConsole/pull/2975

**Comment by GDrupal** [comment]
Some extra tweaks related to this on https://github.com/hechoendrupal/DrupalConsole/pull/2991
