### ISSUE TITLE
[database:connect] command is useless

### ISSUE THREAD

**Issue by jerbob92** [hechoendrupal/DrupalConsole#2564]
The command ```database:connect``` generates a connection string for connecting to the database.
Since #2190, the command is useless as it replaces the password with asterisks.

I propose to revert the change for the ```database:connect``` command.

**Comment by jmolivas** [comment]
@jerbob92  I agree with that, if you have access to the CLI and can execute DC you can easily execute `cat  sites/default/settings.php` no need to hide database user/password.

**Comment by enzolutions** [comment]
I restore the password display in database:connect win PR https://github.com/hechoendrupal/DrupalConsole/pull/2571

What about commands *database:dump* and *site:status*?

**Comment by jmolivas** [comment]
@enzolutions  I think is the same approach we should display those values.

**Comment by enzolutions** [comment]
Restored password in all commands
