### ISSUE TITLE
get console to look in /web to prevent: The "/core/lib/Drupal/Core/Database/Driver" directory does not exist. 

### ISSUE THREAD

**Issue by therobyouknow** [hechoendrupal/DrupalConsole#2592]
I'm nearly able to install Drupal 8 using composer, after successfully overcoming errors seen in: https://github.com/hechoendrupal/DrupalConsole/issues/2589#issuecomment-240429610

```
[02:46 PM]-[vagrant@d8]-[/var/www/d8.dev] 
$ ./vendor/bin/drupal site:install standard --db-type="mysql" --db-name="d8" --db-user="d8" --db-pass="d8" --site-name="D8 site"  --site-mail="email@example.com" --account-name="admin" --account-mail="email@example.com" --account-pass="password"
 Select language for your Drupal installation [English]:
 > 

 Database Host [127.0.0.1]:
 > 

 Database Port [3306]:
 > 

 Database Prefix [ ]:
 > 


                                                                         
  [InvalidArgumentException]                                             
  The "/core/lib/Drupal/Core/Database/Driver" directory does not exist.  
                                                                         
```

But I know /core/lib/Drupal/Core/Database/Driver does exist - it's under the web folder.

How do I tell console to look in the web folder ?

**Comment by therobyouknow** [comment]
Solution would be to cd into web and run console from there, e.g:

```
[02:46 PM]-[vagrant@d8]-[/var/www/d8.dev] 
$ ./vendor/bin/drupal site:install standard --db-type="mysql" --db-name="d8" --db-user="d8" --db-pass="d8" --site-name="D8 site"  --site-mail="email@example.com" --account-name="admin" --account-mail="email@example.com" --account-pass="password"
 Select language for your Drupal installation [English]:
 > 

 Database Host [127.0.0.1]:
 > 

 Database Port [3306]:
 > 

 Database Prefix [ ]:
 > 

 Starting Drupal 8 install process

                                                                                                                        
 [OK] Your Drupal 8 installation was completed successfully                                                             
                                                                                                                        


[03:00 PM]-[vagrant@d8]-[/var/www/d8.dev/web] 
$ 

```

So this worked, but if you can suggest something better - e.g. perhaps using command aliases or whatever then I'd be pleased to know!

**Comment by Greg-Boggs** [comment]
It means in your properties.yml file, which is the config key for robo.... set the key for "webroot" to "web".

**Comment by jmolivas** [comment]
@therobyouknow this will change once RC-1 is out by the end of this month. We will be releasing a new executable and this is the project => https://github.com/hechoendrupal/drupal-console-launcher

**Comment by therobyouknow** [comment]
@jmolivas thank you for all you hard work.

When you say "this will change once RC-1 is out" - what specifically will be changing?

Thank you for advising on https://github.com/hechoendrupal/drupal-console-launcher - is this what RC-1 is going to be, or is it a separate project entirely?

**Comment by jmolivas** [comment]
@therobyouknow Welcome and thank you for using the project.

The Launcher is a separated project is only the global executable with some stand alone commands on a separated repo, this will be the one you download using the `curl` command from the CLI when executing:
```
curl https://drupalconsole.com/installer -L -o drupal.phar
```

The main repo will keep be this one `https://github.com/hechoendrupal/DrupalConsole` but you will need to install it per/site executing from your site root.
```
composer require drupal/console:~1.0 \
--prefer-dist \
--optimize-autoloader \
--sort-packages
```

You can read more about what is changing on RC-1 on this blog post http://jmolivas.com/drupalconsole-rc-1-release-close-a-lot-of-changes

**Comment by therobyouknow** [comment]
Thank you @jmolivas I will read up on it
