### ISSUE TITLE
composer global require drupal/console it doesn't work

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#260]
I tried a `composer global require drupal/console` and it doesn't work.

This is the error message

```
Changed current directory to /Users/jmolivas/.composer
Using version 0.5.* for drupal/console
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/console 0.5.* -> satisfiable by drupal/console[0.5.0].
    - Conclusion: remove symfony/console v2.5.5
    - drupal/console 0.5.0 requires symfony/console 2.6.* -> satisfiable by symfony/console[v2.6.0, v2.6.1].
    - Can only install one of: symfony/console[v2.6.0, v2.5.5].
    - Can only install one of: symfony/console[v2.6.1, v2.5.5].
    - Installation request for symfony/console == 2.5.5.0 -> satisfiable by symfony/console[v2.5.5].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by grayside** [comment]
I have 'The service file "core/core.services.yml" is not valid.' from a composer-based install.

* **Run command:** `vendor/bin/console --drupal=build/html list`
* **Console Version:** 0.7.12
* **Drupal Version:** 8.0.0-beta10

**Comment by jmolivas** [comment]
@grayside is `build/html` a relative path of your D8 installation, from where are you executing `vendor/bin/console`?

**Comment by grayside** [comment]
Correct. I am working from a top level directory containing both build/ and vendor/.

**Comment by ArtuGit** [comment]
Hello.
I do 
`composer global require drupal/console:@stable`
and I still have v0.5.1 which has the limited set of commands.

How to get the latest version wich has *generate* and *self-update* commands?

**Comment by jmolivas** [comment]
@ArtuGit try installing it again 

As a note starting on RC releases DC should be installed per site, you should do:
https://github.com/hechoendrupal/DrupalConsole/#download-as-new-dependency

You can still have the global executable but that is only a Launcher tool for DC
https://github.com/hechoendrupal/DrupalConsole/#install-drupal-console-launcher

**Comment by ArtuGit** [comment]
Thank you, jmolivas.
