### ISSUE TITLE
[command:export]Add flag to config:export:single command to include site uuid

### ISSUE THREAD

**Issue by allgood2386** [hechoendrupal/DrupalConsole#2621]
Currently the config:export:single command does not export site uuid's which is great for creating modules with install config, however we should have the option to include it with the export. I will look into adding this flag and hopefully provide a pull request in a short time.

**Comment by Saphyel** [comment]
drush has a lot of commands about config files (counting contribs too) and is one of the most hateful and important things in d8 so I think we have to improve the actual console commands

**Comment by enzolutions** [comment]
@allgood2386 @Saphyel we agree.

The config:export:single already had that option and was included in config:export at PR https://github.com/hechoendrupal/DrupalConsole/pull/2977

Thanks for your feedback.
