### ISSUE TITLE
Confirming Drupal Console equivalents for enabling, disabling and uninstalling a drupal module (suggestions within)

### ISSUE THREAD

**Issue by therobyouknow** [hechoendrupal/DrupalConsole#2659]
I have provided some suggestions below that would answer the following 2 questions:

- What are the Drupal Console enabling, disabling and uninstalling a contrib module?
- Also what is the standard practice for downloading a module in Drupal 8?

Please can you confirm if my suggestions are correct.

I think perhaps one thing that could accelerate transition from Drupal 7 to Drupal 8 is to show how things were done in Drupal 7 with how they are done in Drupal 8.

**For downloading a module**, in Drupal 7, we use:
drush dl module

For Drupal 8 we add the module to the composer.json file, under the "require" section, e.g. for OAuth 8.x-2.0 module, this would look like:

```
    "require": {
        "composer/installers": "^1.0.20",
        "drupal-composer/drupal-scaffold": "^2.0.1",
        "cweagans/composer-patches": "~1.0",
        "drupal/core": "~8.0",
        "drush/drush": "~8.0",
        "drupal/console": "@stable",
        "drupal/oauth": "8.2.0"
```

Then run `composer install`

**For enabling a module**, in Drupal 7, we can use:
drush en module

In Drupal 8, we can use Drush, but the Drupal Console equivalent is:
drupal module:install module

(is this the correct equivalent?)

**For disabling a module**, in Drupal 7, we can use:
drush dis module

In Drupal 8, we can use Drush, but the Drupal Console equivalent is:
drupal module:uninstall module

(is this the correct equivalent?)

**For uninstalling a module** - i.e. where it should remove its database tables etc (i.e. all evidence it existed), in Drupal 7, we can use:
drush pm-uninstall module

In Drupal 8, what would this be? Or do we continue to use drush?

**Comment by jmolivas** [comment]
@therobyouknow no disable module option in D8, is only installed/uninstalled and yes you are correct.

* Install module or modules in the application
`drupal module:install module` 

* Uninstall module or modules in the application
`drupal module:uninstall module`

**Comment by jmolivas** [comment]
@therobyouknow you can also pass `--composer` to `module:download `command.

```
drupal module:download pathauto --composer
```
And the command will execute `composer require drupal/module` for downloading the module instead of downloading the tar from d.o.
 
![drupal-module-download-composer](https://cloud.githubusercontent.com/assets/366275/18254885/9757059a-7357-11e6-99a7-b55bd08c1efb.png)

**Comment by therobyouknow** [comment]
> jmolivas commented 14 hours ago
> @therobyouknow no disable module option in D8, is only installed/uninstalled and yes you are correct.

Thank you very much @jmolivas for confirming my suggestions and for your input on disabling a module.

I think I should be able to close this issue, but would like your thoughts on the following, please:

From my research about the general concept of disabling a Drupal module, it sounds it is  complex issue when we consider how the site should behave after disabling a module, regarding data integrity, dependencies etc. My research was to read about it here https://www.drupal.org/node/1199946 "Disabled modules are broken beyond repair so the "disable" functionality needs to be removed". It sounds like it is an ongoing debate at the moment.

Is that the reason why disabling a module is not provided by Drupal Console? 

(I would think that not providing it is a reasonable position to take on the basis that disabling is still being debated. So if that was your reason I would certainly respect that. I would be interested in any other reasons too, of course)

I think myself I should think about in what scenarios I would need to disable a module instead of uninstalling it, bearing the issues in mind. Commenters https://www.drupal.org/node/1199946 thread suggest approaches.

Only for additional background information:
I also found a question about disabling a module here: http://drupal.stackexchange.com/questions/72927/manually-disable-a-module and it mentions the https://www.drupal.org/project/disable_modules Drupal 8 module.

Thank you very much again for your input @jmolivas
