### ISSUE TITLE
Is there an equivalent to drush updb in Drupal Console?

### ISSUE THREAD

**Issue by therobyouknow** [hechoendrupal/DrupalConsole#2660]
i.e. the command that runs the database updates (hooks) when new updates to modules are downloaded.

I couldn't see one in the documentation.

Please advise, thank you.

**Comment by jmolivas** [comment]
@therobyouknow yes we have `update:execute`

![drupal-update](https://cloud.githubusercontent.com/assets/366275/18254449/be9bf05c-7352-11e6-8930-31baaa2b8b61.png)

**Comment by therobyouknow** [comment]
Thank you very much jmolivas! Closing ticket.
