### ISSUE TITLE
[meta] Register generator commands in the Drupal container. 

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#2679]
### Problem/Motivation

Register Drupal Console generator commands as services on the Drupal container.
### Why
- Improve command discover and take advantage of dependency injection.
#### Remove class import

```
use Drupal\Console\Command\GeneratorCommand;
```
#### Extend from `Command`

Add `use` keyword

```
use Symfony\Component\Console\Command\Command;
```

Update class to extend from `Command` 

```
class AwesomeCommand extends Command
```
#### Add `CommandTrait`

Add `use` keyword

```
use Drupal\Console\Command\Shared\CommandTrait;
```

Add `use` trait:

```
use CommandTrait; 
```
#### Remove `createGenerator`

```
protected function createGenerator()
{
  ...
}
```
### Remove line on `execute`

```
$generator = $this->getGenerator();
```
#### Register generator class (not the command class) as service

File `config/services/generator.yml`

```
  console.awesome_generator:
    class: Drupal\Console\Generator\AwesomeGenerator
    tags:
      - { name: drupal.generator }
```

NOTE: Make sure you tag as `drupal.generator`.
#### Register generator command class as a service.

File `config/services/generate.yml`

```
console.awesome:
   class: Drupal\Console\Command\Generate\AwesomeCommand
   arguments: ['@console.awesome_generator', '@service_id', '@other_service_id']
   tags:
      - { name: drupal.command }
```

NOTE: Make sure you inject the previously registered generator class service.
#### How to know which services to inject

Any call to:

```
$this->getService('SERVICE_NAME')
$this->getDrupalService('SERVICE_NAME')
$this->get('SERVICE_NAME')
\Drupal::service('SERVICE_NAME')
\Drupal::getContainer()->get('SERVICE_NAME')
$this->getApplication()->getContainerHelper()->get('SERVICE_NAME')
```

Should be added as `argument: ['@SERVICE_NAME']` on the service definition.
#### Inject service add use, property and constructor method.

```
...
use Drupal\Console\Generator\AwesomeGenerator;
use Vendor\Package\ServiceName;
...

    /**
     * @var AwesomeGenerator
     */
    protected $generator; 

    /**
     * @var ServiceName
     */
    protected $serviceName; 

    /**
     * AwesomeCommand constructor.
     * @param ServiceName $serviceName
     */
    public function __construct(AwesomeGenerator generator, ServiceName $serviceName) {
        $this->generator = $generator;
        $this->serviceName = $serviceName;
        parent::__construct();
    }
```

NOTES: 
- You can find the `Vendor\Package\ServiceName` of your service by executing from your Drupal 8 site `drupal container:debug SERVICE_NAME`.
- Make sure you call the `parent::__construct();` on the added `__construct`method.
#### Some methods and classes has been relocated to new service and maybe renamed, this is the table mapping those changes.

| Current | New Service name | New Method name |
| --- | --- | --- |
| $this->get('site')->loadLegacyFile | console.site | loadLegacyFile |
### How to test

Read setup instructions at https://gist.github.com/jmolivas/97bbd07f328217be3564a434c5bd2618
### Related documentation
- http://symfony.com/doc/current/console/commands_as_services.html
### Related issues:
- [meta] Register commands as services https://github.com/hechoendrupal/DrupalConsole/issues/2225
## Completed Namespace
- [x]  AuthenticationProviderCommand.php
- [x]  BreakPointCommand.php
- [x] CommandCommand.php
- [x]  ConfigFormBaseCommand.php
- [x]  ControllerCommand.php
- [ ]  EntityBundleCommand.php
- [ ]  EntityCommand.php
- [ ]  EntityConfigCommand.php
- [ ]  EntityContentCommand.php
- [x]  EventSubscriberCommand.php
- [x]  FormAlterCommand.php
- [x]  FormBaseCommand.php
- [x]  FormCommand.php
- [x]  HelpCommand.php
- [x]  ModuleCommand.php
- [ ]  ModuleFileCommand.php
- [x]  PermissionCommand.php
- [x]  PluginBlockCommand.php
- [x]  PluginCKEditorButtonCommand.php
- [ ]  PluginConditionCommand.php
- [x]  PluginFieldCommand.php
- [x]  PluginFieldFormatterCommand.php
- [x]  PluginFieldTypeCommand.php
- [x]  PluginFieldWidgetCommand.php
- [x]  PluginImageEffectCommand.php
- [x]  PluginImageFormatterCommand.php
- [x]  PluginMailCommand.php
- [x]  PluginRestResourceCommand.php
- [x]  PluginRulesActionCommand.php
- [x]  PluginSkeletonCommand.php
- [x]  PluginTypeAnnotationCommand.php
- [x]  PluginTypeYamlCommand.php
- [x]  PluginViewsFieldCommand.php
- [x]  PostUpdateCommand.php
- [x]  ProfileCommand.php
- [x] RouteSubscriberCommand.php
- [x] ServiceCommand.php
- [x] ThemeCommand.php
- [x] TwigExtensionCommand.php
- [x] UpdateCommand.php
- Make sure you add a comment on the generator you take to work to avoid working on same classes. 
- Make sure you get latest changes from Drupal Console repository for instructions [Keeping your fork up to date](http://docs.drupalconsole.com/en/contributing/keeping-your-fork-up-to-date.html)

**Comment by jmolivas** [comment]
Working on `ModuleCommand

**Comment by enzolutions** [comment]
Completed GenerateCommand , working in AuthenticationProvider

**Comment by novia713** [comment]
Working on `BreakPointCommand`

**Comment by enzolutions** [comment]
Working in ConfigFormBaseCommand.php

**Comment by enzolutions** [comment]
Working in ControllerCommand

**Comment by enzolutions** [comment]
Working in FormAlterCommand

**Comment by novia713** [comment]
Working in `HelpCommand`

**Comment by enzolutions** [comment]
Working in EventSubscriberCommand.php

**Comment by novia713** [comment]
working on `PermissionCommand`

**Comment by enzolutions** [comment]
Working in UpdateCommand

**Comment by enzolutions** [comment]
Working in TwigExtensionCommand.php

**Comment by enzolutions** [comment]
Working in ThemeCommand.php

**Comment by enzolutions** [comment]
Working in ServiceCommand.php

**Comment by enzolutions** [comment]
Working in  ServiceCommand.php

**Comment by enzolutions** [comment]
Working in RouteSubscriberCommand.php

**Comment by enzolutions** [comment]
Working in  ProfileCommand.php

**Comment by enzolutions** [comment]
Working in PostUpdateCommand.php

**Comment by enzolutions** [comment]
Working in  PluginViewsFieldCommand.php

**Comment by enzolutions** [comment]
Working in PluginTypeYamlCommand.php

**Comment by jmolivas** [comment]
Working on `CommandCommand`

**Comment by enzolutions** [comment]
Working in PluginTypeAnnotationCommand.php

**Comment by novia713** [comment]
Working on ` PluginBlockCommand`

**Comment by enzolutions** [comment]
Working in PluginSkeletonCommand.php

**Comment by novia713** [comment]
Working on `PluginCKEditorButtonCommand`

**Comment by enzolutions** [comment]
working in PluginRulesActionCommand.php

**Comment by enzolutions** [comment]
Working in PluginRestResourceCommand.php

**Comment by enzolutions** [comment]
Working in PluginMailCommand.php

**Comment by enzolutions** [comment]
Working in PluginImageFormatterCommand.php

**Comment by enzolutions** [comment]
Working in PluginFieldWidgetCommand.php

**Comment by novia713** [comment]
Working on `EntityBundleCommand`

**Comment by enzolutions** [comment]
Working in  PluginFieldTypeCommand.php

**Comment by enzolutions** [comment]
Working in PluginImageEffectCommand.php

**Comment by enzolutions** [comment]
Working in PluginFieldFormatterCommand.php

**Comment by enzolutions** [comment]
working in Plugin Field Command.php

**Comment by novia713** [comment]
Working on `EntityCommand`

**Comment by novia713** [comment]
@enzolutions found this 2 little errors in `src/Command/Generate/PluginFieldCommand.php`

![seleccion_491](https://cloud.githubusercontent.com/assets/423279/18618381/0d4d76d8-7de6-11e6-82d2-d77c32732bfc.png)

**Comment by enzolutions** [comment]
@novia713 plese fix in your next commit

**Comment by enzolutions** [comment]
Working in EntityContentCommand.php

**Comment by harold20** [comment]
Working in ModuleFileCommand.php

**Comment by novia713** [comment]
working on `PluginConditionCommand`
