### ISSUE TITLE
[update:execute] Can't run all N updates for all modules

### ISSUE THREAD

**Issue by smalot** [hechoendrupal/DrupalConsole#2731]
Hi,

Currently the `update:execute` requires at least the name of the module to run update N function.
Is there another command to run all pending updates for all module ?

Thanks

**Comment by smalot** [comment]
or maybe, we can alter this one to be run on all modules with a flag like "--all"

**Comment by novia713** [comment]
@smalot  you want `update:execute all` 

we should improve the documentation, i encourage you to do it yourself :)

**Comment by smalot** [comment]
Excellent !
I'll try to do it
Many Thanks

**Comment by smalot** [comment]
Does the "update:execute" followed by a natural "cache:clear" or the cache clear needs to be done manually ?

**Comment by smalot** [comment]
After reading at the `execute` function of this command, I've noted that the maintenance mode is disable after the update process.
Even if the maintenance mode was already available before `update:execute`.

**Comment by smalot** [comment]
using the magical module name `all` is not the best thing.
a flag like `--all` should be better.
what do you think ?

**Comment by jmolivas** [comment]
@smalot we follow the same approach as `cache:rebuild all`

**Comment by smalot** [comment]
Ok for me.
Thanks

**Comment by jmolivas** [comment]
@smalot closing this issue you may want to add a new one about reporting 

> After reading at the execute function of this command, I've noted that the maintenance mode is disable after the update process.
Even if the maintenance mode was already available before update:execute.

**Comment by smalot** [comment]
Ok for that
Thanks
