### ISSUE TITLE
[site:statistics] command fails when comment module is uninstalled.

### ISSUE THREAD

**Issue by matthewmessmer** [hechoendrupal/DrupalConsole#2744]
I ran the site:statistics command on a site where the comment module was disabled/uninstalled and received the following error:
 [Drupal\Component\Plugin\Exception\PluginNotFoundException]
  The "comment" entity type does not exist.

Drupal                       8.1.8
Drupal Console version 1.0.0-rc1

**Comment by jmolivas** [comment]
@matthewmessmer nice catch, we will take care of this unless you like to send a PR to have it fixed.

**Comment by daydiff** [comment]
I can implement this, if nobody has started to work on it.

**Comment by jmolivas** [comment]
@daydiff this is the line that needs to be fixed https://github.com/hechoendrupal/DrupalConsole/blob/master/src/Command/Site/StatisticsCommand.php#L118
