### ISSUE TITLE
Any reason why the 1.0-rc& doesn't have phar files?

### ISSUE THREAD

**Issue by hanoii** [hechoendrupal/DrupalConsole#2762]
Thanks,
Ariel.=

**Comment by jmolivas** [comment]
@hanoii This is the new repo containing the executable phar files
https://github.com/hechoendrupal/drupal-console-launcher/releases

But you still get them using the same instructions
```
# Run this in your terminal to get the latest project version:
curl https://drupalconsole.com/installer -L -o drupal.phar

# Accessing from anywhere on your system:
mv drupal.phar /usr/local/bin/drupal

# Apply executable permissions on the downloaded file:
chmod +x /usr/local/bin/drupal
```

And update using the same `self-update` command

**Comment by jmolivas** [comment]
@hanoii closing this, feel free to re-open or ask any more questions about it.
