### ISSUE TITLE
Error: Command "chain" is not defined, amongst many others

### ISSUE THREAD

**Issue by bshaffer** [hechoendrupal/DrupalConsole#2763]
In the latest release (`1.0.0-rc4`), I am getting the error "chain command is not defined", even though it shows up in the `about` command:

```sh
$ curl https://drupalconsole.com/installer -L -o drupal.phar
$ chmod -x drupal.phar
$ php drupal.phar 

Drupal Console Launcher (1.0.0-rc4)
===================================

Copy configuration files.

   drupal init --override

Download, install and serve Drupal 8

   drupal chain --file=~/.console/chain/quick-start.yml

Create a new Drupal project

   drupal site:new drupal8.dev --latest

Install a Drupal project

   drupal site:install

Lists all available commands

   drupal list

Update project to the latest version.
-------------------------------------

   drupal self-update

$ php drupal.phar chain

  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "chain" is not defined.                                 
                                                                  
```

This is very frustrating because it's breaking my automated tests, and I cannot find a way to revert to the previous version. Downloading the previous versions via composer results in the following error:

```sh
$ echo "{}" >> composer.json
$ composer config minimum-stability dev
$ composer require drupal/console:1.0.0-rc1 --prefer-dist --optimize-autoloader --sort-packages
$ php vendor/bin/drupal

 Something goes wrong with your package.
 Try downloading again.
 Executing:
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
```

I found out this is because the script is expecting the user's `cwd` to be `vendor`. This is frustrating, but OK. I moved into the `vendor` dir and received the following error:

```sh
Fatal error: Class 'Drupal\Core\DrupalKernel' not found in vendor/drupal/console/src/Bootstrap/DrupalKernel.php on line 14
```

At this point, I fell to the ground and wept softly. Can someone please tell me there's some sense to this chaos?

**Comment by bshaffer** [comment]
I highly recommend using `drush`, to anyone who is struggling with this repository. I was very easily able to get up and running (took me minutes) in contrast to the hours I've spent struggling with this library.

**Comment by jmolivas** [comment]
@bshaffer Starting on RC release DrupalConsole must be installed per site and the `phar` is only a launcher tool to find the DrupalConsole loaded on the site.

We are planning to move more commands to the launcher tool 

* chain
* site:debug
* site:new

Our ETA for having those 2 commands available is BADCamp.

I am currently looking at the execution issue to have it fixed, we actually have some PR we are currently testing.

**Comment by bshaffer** [comment]
Some honest feedback: this has been a nightmare using your tool and I will never use it again.
