### ISSUE TITLE
Packaging Drupalconsole

### ISSUE THREAD

**Issue by sanduhrs** [hechoendrupal/DrupalConsole#2771]
Hey ! I'm trying to package drupalconsole for arch linux.
Until 1.0.0-beta5 it was sufficient to run

    php /usr/bin/composer install --no-dev
    php -d phar.readonly=Off /usr/bin/php-box build

Since 1.0.0-rc1 things obviously changed, running the above commands is still working well, but the resulting drupal.phar just gives:

    > ./drupal.phar 
    Something goes wrong with your package.
    Try downloading again.
    Executing:
    composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader

./bin/drupal gives the exact same.

What is the current process of building drupalconsole?

**Comment by jmolivas** [comment]
@sanduhrs Starting on RC releases we decouple DrupalConsole into separated projects
This is the new repo containing the box configuration and the one we ship as the global executable

https://github.com/hechoendrupal/drupal-console-launcher

**Comment by sanduhrs** [comment]
Thanks, I missed that.
