### ISSUE TITLE
[migrate:setup] Cannot access protected property Drupal\migrate\Plugin\Migration::$migration_tags

### ISSUE THREAD

**Issue by langelhc** [hechoendrupal/DrupalConsole#2775]
## Problem/Motivation

I tried to setup a migration D7 to D8.2, but I get this error:

Details to include:
- Drupal version: 8.2
- "Drupal Console" version "1.0.0-beta5"
## How to reproduce

$ drupal migrate:setup --db-type=mysql --db-host=127.0.0.1 --db-name=db --db-user=root --db-pass=root --db-port=3306 --no-interaction
PHP Fatal error: Cannot access protected property Drupal\migrate\Plugin\Migration::$migration_tags in /path/to/project/vendor/drupal/console/src/Command/Shared/MigrationTrait.php on line 32

Line 32: $migrations[$migration->id()]['tags'] = implode(', ', $migration->migration_tags);
## Solution

Change the get method getMigrationTags().

**Comment by enzolutions** [comment]
This issue was solved
