### ISSUE TITLE
Shellexec Output Is Not an Option

### ISSUE THREAD

**Issue by tooleyantoine** [hechoendrupal/DrupalConsole#2782]
After updating I get this error on attempting to run any drupal console command such as drupal list. Pulling my hair out!
Using MAMP and drupal 8.
Thanks!

**Comment by jmolivas** [comment]
Try this https://github.com/hechoendrupal/DrupalConsole/issues/2754#issuecomment-251450025

**Comment by tooleyantoine** [comment]
Life saver!
Removing the last line 'shellexec_output: true' from file ~/.console/config.yml worked a treat.
Thanks!
