### ISSUE TITLE
Add an initial test to the module generator

### ISSUE THREAD

**Issue by damienmckenna** [hechoendrupal/DrupalConsole#2784]
It would be pretty awesome if the module generator automatically added a test that simply ensured the front page could be loaded properly when the module was enabled. This would provide two benefits: a) a way of ensuring that future changes applied don't completely break the site, b) provide a starting point for module maintainers to add tests.

**Comment by jmolivas** [comment]
Test added by https://github.com/hechoendrupal/DrupalConsole/pull/2807
