### ISSUE TITLE
--root for drupal console doesn't appear to propogate

### ISSUE THREAD

**Issue by s3than** [hechoendrupal/DrupalConsole#2789]
Started with the same issues as here https://github.com/hechoendrupal/DrupalConsole/issues/2785

This all takes place on a fresh vm project is located in /app, drupal core is located in /app/web/core

1/ Items having the drupal/console installed in to the project it was unable to locate the autoload see here: [PR](https://github.com/hechoendrupal/DrupalConsole/issues/2786)
2/ Once using the above PR I was able to run the list command 'bin/drupal --root=/app/web list' Receiving the following  [WARNING] In order to list all of the available commands you should install drupal first.
3/ Running 'bin/drupal --root=/app/web site:install project' selecting default options only and being located in /app

- Select language for your Drupal installation [English]:

- Using "mysql" database with name "db" and user "user"

- Provide your Drupal site name [Drupal 8 Site Install]:

- Provide your Drupal site mail [admin@example.com]:

- Provide your Drupal administrator account name [admin]:

- Provide your Drupal administrator account password:

- Provide your Drupal administrator account mail [admin@example.com]:

```
  [InvalidArgumentException]                                                  
  The "/app//core/lib/Drupal/Core/Database/Driver" directory does not exist.  

Exception trace:
 () at /app/vendor/symfony/finder/Finder.php:656
 Symfony\Component\Finder\Finder->in() at /app/vendor/drupal/console/src/Utils/Site.php:67
 Drupal\Console\Utils\Site->getDatabaseTypes() at /app/vendor/drupal/console/src/Command/Site/InstallCommand.php:374
 Drupal\Console\Command\Site\InstallCommand->execute() at /app/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:866
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /app/vendor/drupal/console-core/src/ConsoleApplication.php:85
 Drupal\Console\ConsoleApplication->doRun() at /app/vendor/drupal/console/src/Application.php:39
 Drupal\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at /app/vendor/drupal/console/bin/drupal.php:53
 require() at /app/vendor/drupal/console/bin/drupal:4
```

Currently working on this PR https://github.com/hechoendrupal/DrupalConsole/pull/2786

**Comment by jmolivas** [comment]
@s3than We can probably try to implement similar logic as the launcher (the global executable)

https://github.com/hechoendrupal/drupal-console-launcher/blob/master/bin/drupal.php#L33

This is the repo where the `ArgvInputReader ` class is at 
https://github.com/hechoendrupal/drupal-console-core/blob/master/src/Utils/ArgvInputReader.php

**Comment by jmolivas** [comment]
@s3than  This should be fixed with RC-6

**Comment by jmolivas** [comment]
@s3than I merged your PR and more logic in top of it.

**Comment by s3than** [comment]
Excellent thank you for the quick work.

**Comment by s3than** [comment]
Confirmed resolved.
