### ISSUE TITLE
[generate:module] PHP Fatal error:  Call to undefined method Drupal\Console\Command\Generate\ModuleCommand::validateModuleName() in ./vendor/drupal/console/src/Command/Generate/ModuleCommand.php on line 271

### ISSUE THREAD

**Issue by qinshuguo** [hechoendrupal/DrupalConsole#2801]
PHP Fatal error:  Call to undefined method Drupal\Console\Command\Generate\ModuleCommand::validateModuleName() in ./vendor/drupal/console/src/Command/Generate/ModuleCommand.php on line 271

**Comment by PacificMorrowind** [comment]
ah I think I found the right commit message to trigger the auto-convert to PR from Issue.

**Comment by PacificMorrowind** [comment]
Wait no I didn't and now I see there already was a PR for this although it only fixed the one bug. Want me to delete  my branch and redo it as a new PR  that only fixes the second bug?

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2808 merged
