### ISSUE TITLE
Composer manager struggle with version when trying to get latest Drupal console version

### ISSUE THREAD

**Issue by RoySegall** [hechoendrupal/DrupalConsole#2803]
When using composer manager to download DrupalConsole we get the 0.11.3 version. It should download the latest release - 1.0.0-rc5(if I recall properly).

But that not all the problems. When specifying the version like `composer require drupal/console:~1.0.0-rc5` i needed to specify drupal console core like that:
`composer require drupal/console-core:~1.0.0-rc5 drupal/console:~1.0.0-rc5` 
But when downloading it to Drupal I got some errors with dom crawler versions. My solution is to use:
`composer require symfony/dom-crawler:~2.8.11 drupal/console-core:~1.0.0-rc5 drupal/console:~1.0.0-rc5 --working-dir=$DRUPAL_DIR`

Any better solution for this?

**Comment by pfrenssen** [comment]
The solution for this is to fix this in Drupal console so they can work with the same version of DomCrawler as Drupal core.

**Comment by jmolivas** [comment]
@pfrenssen @RoySegall  we are using https://github.com/hechoendrupal/DrupalConsole/blob/master/composer.json#L45

Looking at Drupal core
```
symfony-cmf/routing                  1.4.0   Extends the Symfony2 routing component for dynamic routes and cha...
symfony/browser-kit                  v2.7.6  Symfony BrowserKit Component
symfony/class-loader                 v2.8.4  Symfony ClassLoader Component
symfony/console                      v2.8.4  Symfony Console Component
symfony/css-selector                 v2.8.4  Symfony CssSelector Component
symfony/debug                        v2.7.6  Symfony Debug Component
symfony/dependency-injection         v2.8.4  Symfony DependencyInjection Component
symfony/dom-crawler                  v2.7.6  Symfony DomCrawler Component
symfony/event-dispatcher             v2.8.4  Symfony EventDispatcher Component
symfony/http-foundation              v2.8.4  Symfony HttpFoundation Component
symfony/http-kernel                  v2.8.4  Symfony HttpKernel Component
symfony/polyfill-apcu                v1.1.1  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-iconv               v1.1.1  Symfony polyfill for the Iconv extension
symfony/polyfill-mbstring            v1.1.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54               v1.1.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP ...
symfony/polyfill-php55               v1.1.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP ...
symfony/process                      v2.8.4  Symfony Process Component
symfony/psr-http-message-bridge      v0.2    PSR HTTP message bridge
symfony/routing                      v2.8.4  Symfony Routing Component
symfony/serializer                   v2.8.4  Symfony Serializer Component
symfony/translation                  v2.8.4  Symfony Translation Component
symfony/validator                    v2.8.4  Symfony Validator Component
symfony/yaml                         v2.8.4  Symfony Yaml Component
```

I will do something similar that we do with `symfony/debug`
https://github.com/hechoendrupal/DrupalConsole/blob/master/composer.json#L44

I will be tagging a new release later on today

**Comment by jmolivas** [comment]
@RoySegall related to download 0.11.3 maybe your composer stability is set to stable?

**Comment by jmolivas** [comment]
I just sent a PR to fix the required `symfony/dom-crawler` for DrupalConsole https://github.com/hechoendrupal/DrupalConsole/pull/2806

**Comment by jmolivas** [comment]
@RoySegall do you want to try again we just tag a new release with the composer changes

**Comment by RoySegall** [comment]
I tried it couple of days ago but now that you say you tag a new version I'll try this tomorrow morning. 

10x.

**Comment by RoySegall** [comment]
No, still not working as expected. When downloading only drupal console I still get 0.11.3 but if I specify the version as I did with the fix for OG, `composer require drupal/console:~1.0.0-rc5`, I'm getting this:
> ./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>  Problem 1
    - drupal/console 1.0.0-rc6 requires drupal/console-core ^1.0 -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - drupal/console 1.0.0-rc5 requires drupal/console-core ^1.0 -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - Installation request for drupal/console ~1.0.0-rc5 -> satisfiable by drupal/console[1.0.0-rc5, 1.0.0-rc6].

Trying to specify as before, `composer require drupal/console-core:~1.0.0-rc5 drupal/console:~1.0.0-rc5`, I'm getting:
> ./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>  Problem 1
    - drupal/console-core 1.0.0-rc6 requires drupal/console-en ~1.0 -> satisfiable by drupal/console-en[1.0.0-rc1, 1.0.0-rc2] but these conflict with your requirements or minimum-stability.
    - drupal/console-core 1.0.0-rc5 requires drupal/console-en ~1.0 -> satisfiable by drupal/console-en[1.0.0-rc1, 1.0.0-rc2] but these conflict with your requirements or minimum-stability.
    - Installation request for drupal/console-core ~1.0.0-rc5 -> satisfiable by drupal/console-core[1.0.0-rc5, 1.0.0-rc6].

If I'm changing the version using `composer require drupal/console-core:~1.0.0-rc6 drupal/console:~1.0.0-rc6` I'm getting:
>   Problem 1
    - Installation request for drupal/console-core ~1.0.0-rc6 -> satisfiable by drupal/console-core[1.0.0-rc6].
    - drupal/console-core 1.0.0-rc6 requires drupal/console-en ~1.0 -> satisfiable by drupal/console-en[1.0.0-rc1, 1.0.0-rc2] but these conflict with your requirements or minimum-stability.
  Problem 2
    - drupal/console-core 1.0.0-rc6 requires drupal/console-en ~1.0 -> satisfiable by drupal/console-en[1.0.0-rc1, 1.0.0-rc2] but these conflict with your requirements or minimum-stability.
    - drupal/console 1.0.0-rc6 requires drupal/console-core ^1.0 -> satisfiable by drupal/console-core[1.0.0-rc6].
    - Installation request for drupal/console ~1.0.0-rc6 -> satisfiable by drupal/console[1.0.0-rc6].

so no dramatic changes for me. I tried to clear composer cache and still did not worked.

**Comment by RoySegall** [comment]
@pfrenssen Can you please verify it? Just to make sure I'm not the only who's getting this?

**Comment by jmolivas** [comment]
@RoySegall is your `composer.json` set as:
```
 "minimum-stability": "stable",
```
if yes, can you try this instead:
```
minimum-stability: dev,
prefer-stable: true
```

**Comment by RoySegall** [comment]
I'm installing in on a clean directory without any composer.json file in there.

**Comment by jmolivas** [comment]
Another option could be to try:
```
composer require drupal/console:~1.0@RC
```

**Comment by RoySegall** [comment]
> composer require drupal/console:~1.0@RC
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>  Problem 1
    - drupal/console 1.0.0-rc6 requires drupal/console-core ^1.0 -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - drupal/console 1.0.0-rc5 requires drupal/console-core ^1.0 -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - drupal/console 1.0.0-rc4 requires drupal/console-core ^1.0 -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - drupal/console 1.0.0-rc3 requires drupal/console-core ^1.0@RC -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - drupal/console 1.0.0-rc2 requires drupal/console-core ^1.0@RC -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - drupal/console 1.0.0-rc1 requires drupal/console-core ~1.0 -> satisfiable by drupal/console-core[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6] but these conflict with your requirements or minimum-stability.
    - Installation request for drupal/console ~1.0@RC -> satisfiable by drupal/console[1.0.0-rc1, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6].

You don't get it?

**Comment by RoySegall** [comment]
I'm installing it as it was global installation, something that people would usually do. But I can git it a try with a Drupal installation and let you know.

**Comment by RoySegall** [comment]
The dom crawler issue is OK but still when downloading the drupal console using composer we get version 0.11.3 which mean that developers could not use OG integration with DrupalConsole if they not specify the version number. Something which we can't take for granted.

The only solution I can think of is if we specify in OG composer file the Drupal Console version number.

@pfrenssen What do you think?

**Comment by pfrenssen** [comment]
The latest 1.0.0-rc6 release works perfect for me on vanilla core 8.2.x-dev. The dependencies match perfectly with core.

Here's the output I get on a freshly reset D8 instance (`git reset --hard @{u} && rm -rf vendor && composer install`):

```
[pieter@arch-desktop drupal (8.2.x %=)]$ composer require --dev drupal/console:~1.0@rc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/expression-language (v2.8.12)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing stecman/symfony-console-completion (0.5.1)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing phpseclib/phpseclib (2.0.4)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing gabordemooij/redbean (v4.3.2)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/finder (v2.8.12)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/filesystem (v2.8.12)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/config (v2.8.12)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drupal/console-en (1.0.0-rc2)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dflydev/placeholder-resolver (v1.0.2)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dflydev/dot-access-data (v1.0.1)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dflydev/dot-access-configuration (v1.0.1)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drupal/console-core (1.0.0-rc6)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing alchemy/zippy (0.3.5)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drupal/console (1.0.0-rc6)
    Loading from cache

> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
alchemy/zippy suggests installing guzzle/guzzle (To use the GuzzleTeleporter)
Writing lock file
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
```

**Comment by pfrenssen** [comment]
I also just tested on core versions 8.1.x and 8.3.x and both work great. Thanks a lot for fixing this!

**Comment by pfrenssen** [comment]
@RoySegall the reason you get 0.11.3 by default if you do not provide the `@rc` constraint is because the core `composer.json` contains the following directive:

```
"prefer-stable": true
```

Because of this Composer will use the latest stable version that is available. In this case it considers the 0.x branch stable, and the 1.x branch unstable (because it is still in RC phase).

We can override this by specifying that we are fine with any RC release. I like the short syntax provided by @jmolivas above:

```
$ composer require --dev drupal/console:~1.0@rc
```

Once the 1.0.0 is out this will start following that, so it will work fine for the time being. There is a small drawback in that it will also track any future RC release like 1.1.0-rc1 which may or may not be wanted. This can easily be fixed by dropping the `@rc` suffix as soon as Drupal Console gets a full release.

**Comment by RoySegall** [comment]
The issue for the integration with merged. Thanks for the work everyone.  There is a list over [here](https://github.com/Gizra/og/issues/196) for future integrations with DrupalConsole.

Thanks again.
