### ISSUE TITLE
[user:delete] command fails when user id is left empty

### ISSUE THREAD

**Issue by daydiff** [hechoendrupal/DrupalConsole#2804]
## Problem
When I run user:delete command trying to delete users by roles it fails with fatal error:

PHP Fatal error:  Call to a member function getStorage() on null in console/src/Command/User/DeleteCommand.php on line 174

## How to reproduce

1. run `user:delete`
2. leave `user id` empty
3. choose `user role`
4. here you get an error

## Solution
Replace mistyped
```php
$userStorage = $this->entityManager->getStorage('user');
```
 with 
```php
$userStorage = $this->entityTypeManager->getStorage('user');
```

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2805 merged
