### ISSUE TITLE
$root variable can't get proper directory when site is drupal-project composer template

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2819]
![seleccion_009](https://cloud.githubusercontent.com/assets/423279/19409923/61ac1320-92df-11e6-801b-cdb92485e204.png)

note that he is searching for _services.yml_ in _~/public_html/secundario.dev/**web/**vendor/drupal/console-core_

i'm linking composer components to my actualized repositories of DrupalConsole
somebody can point me out where `$root` variable is built, in order to enhance it?

**Comment by jmolivas** [comment]
@novia713 can you confirm there is no `composer.json` file on your web directory?

**Comment by novia713** [comment]
hmmm yes, there were an empty composer.json in /web
i don't know from where it comes ....

erasing it, aparently drupal console works
