### ISSUE TITLE
[translation:pending] getDirectoryRoot() error

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2821]
are `translation` commands still in use?

I'm getting this error when i try `drupal translation:pending es`

```php
PHP Fatal error:  Call to undefined method Drupal\Console\Application::getDirectoryRoot() in /home/leandro/git/DrupalConsole/src/Command/Develop/TranslationPendingCommand.php on line 69
```

**Comment by jmolivas** [comment]
@novia713 yes we will require them to sync translation repositories. I am not sure if the namespace was migrated, @enzolutions do you  remember that?

**Comment by novia713** [comment]
i can see no services are bein injected on these  `translation` commands  ...

**Comment by jmolivas** [comment]
Seems like not yet migrated.

**Comment by novia713** [comment]
i can try to migrate it tomorrow

**Comment by novia713** [comment]
I'm migrating `translation` commands. faced some troubles, dealing with them ...

**Comment by novia713** [comment]
PR for  `translation` commands at https://github.com/hechoendrupal/DrupalConsole/pull/2830

**Comment by novia713** [comment]
already merged
