### ISSUE TITLE
[settings:set] can't find local config

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2822]
i did a `drupal init` and set my `config.yml` at the local directory of my website,
so there is still no `config.yml` in my home

but,
when i do a `settings:set language es` i get the following error 

``` php
 [ERROR] El archivo de configuración "/home/leandro/.console/config.yml" no     
         está disponible, intenta ejecutando `drupal init` 
```

so it is seeking the `config.yml` ONLY in my home :-(

**Comment by jmolivas** [comment]
@novia713  which version do you installed have globally and on the site?

**Comment by novia713** [comment]
globally, 1.0.0-rc5
but i was using a custom repos linked version on that site (1.0.0-rc5 also)
my repos are actualized today

**Comment by jmolivas** [comment]
Did you run the init and answered yes to the first question?

**Comment by jmolivas** [comment]
I re-read your comment about running `settings:set` looking at that

**Comment by novia713** [comment]
for being clearer i'm having this problem:
```php
 dom 23 oct - 13:33  ~/public_html/secundario.dev/web 
 @leandro  drupal settings:set language en                                                                                          
 [ERROR] The "/home/leandro/.console/config.yml" config file is missing, try executing `drupal init`
```
actually, my `config.yml` is in 
```
~/public_html/secundario.dev/web/console/config.yml
```

i would do some work on this if someone point me out which direction to take on this

**Comment by novia713** [comment]
time has passed and this is working. closing.
