### ISSUE TITLE
drupal site:new broken?

### ISSUE THREAD

**Issue by nbunney** [hechoendrupal/DrupalConsole#2825]
I have a fresh install of the drupal console installed using the instructions on the home page.  The only difference is that I needed to move config.yml from the console directory to .console.

With this install I try to run drupal site:new drupal8.dev and get the following error:

>   [Symfony\Component\Console\Exception\CommandNotFoundException]  
>   There are no commands defined in the "site" namespace.   

drupal check returns:

> Checking requirements using file at:
>  /Users/nathan/.console/phpcheck.yml
>  [OK] Checks Passed

**Comment by jmolivas** [comment]
@nbunney yes not yet migrated to the new Drupal Launcher the goal is to migrate during BADCAmp this week

**Comment by nbunney** [comment]
LOL, I will be there on Thursday in one of the sessions or whatever and hoping to use this to set up.  Ah well...  I guess I will do it the old fashioned way.  :-)

**Comment by jmolivas** [comment]
@nbunney What you got using the curl command is the global executable, this is like a shortcute to have a drupal command system-wide, this executable provides a limited number of commands.

Try using this to Download Drupal + DrupalConsole
```
composer create-project \
drupal-composer/drupal-project:8.x-dev \
drupal8.dev \
--prefer-dist \
--no-progress \
--no-interaction
```

We are planning to resurrect the `site:new` command I will let you know on this issue when is done.

**Comment by nbunney** [comment]
Nice.  I love composer.

I wish I could stay and meet the community on Thursday but I am going to the training and then blasting out to Hawaii on Friday.  Do you guys do regular area meetups?  Once I get going I may have to come over for a good topic.  I live in Modesto.

**Comment by xmacinfo** [comment]
Can we hide commands like "site" when they are not available? Or have those display a nice warning?

**Comment by jmolivas** [comment]
@xmacinfo when you  receive a 
> There are no commands defined in the "site" namespace.

Is because is not listed
<img width="1128" alt="drupal-list-no-site" src="https://cloud.githubusercontent.com/assets/366275/19575505/a7f0d7de-96c3-11e6-8260-a4e863aa5de4.png">

We can probably catch the error and display a user friendly error message, could you please create a separated issue for that?

**Comment by smalot** [comment]
Hi all,
Resurect the "site:install" or "site:new" is a very good idea.
Is there an issue already opened about that ?
Do you need help ?
BR

**Comment by smalot** [comment]
note: I'll be happy to work on it if necessary

**Comment by jmolivas** [comment]
@smalot I know @igasi was working on this not sure how is this going?

**Comment by smalot** [comment]
@igasi, $jmolivas: I made changes on those PR:

- https://github.com/hechoendrupal/drupal-console-core/pull/75
- https://github.com/hechoendrupal/drupal-console-launcher/pull/46
- https://github.com/hechoendrupal/DrupalConsole/issues/2887

**Comment by smalot** [comment]
I'm available if needed to work on it

**Comment by marcelovani** [comment]
This could possibly replace site:new by using it as a chain
https://github.com/hechoendrupal/DrupalConsole/pull/2961

**Comment by jmolivas** [comment]
@nbunney @xmacinfo @smalot @marcelovani Starting on RC-11 chain files could be registered as commands. 

This mean of you update to latest version and execute the init command the site:new will be available.
