### ISSUE TITLE
[console] Don't clear the shell when running console

### ISSUE THREAD

**Issue by gergelypap** [hechoendrupal/DrupalConsole#2829]
Currently all `drupal` commands clear the console output. Why? This is super annoying...

(Using version **1.0.0-rc6**)

**Comment by jmolivas** [comment]
@gergelypap This will be a configurable feature on next RC-7.

**Comment by esolitos** [comment]
+1 to have it configurable, and I think the right approach should be to have it disabled by default.
This is very annoying, and it's an odd behaviour if compared with _any_ other cli command.

**Comment by jmolivas** [comment]
PRs sent and merged:
https://github.com/hechoendrupal/DrupalConsole/pull/2836
https://github.com/hechoendrupal/drupal-console-core/pull/67
https://github.com/hechoendrupal/drupal-console-launcher/pull/42

**Comment by pfrenssen** [comment]
Can we make a new release ASAP containing this important fix? I lost data due to this.

**Comment by jmolivas** [comment]
@pfrenssen A new release will be tagged the later tomorrow Oct 26th.

**Comment by pfrenssen** [comment]
Great news! Thanks!

**Comment by jmolivas** [comment]
@pfrenssen @esolitos @gergelypap New release tagged this should stop happening.

Update instructions at => https://gist.github.com/jmolivas/a0970e1ea252ecb852fe8c7182d85d3e

**Comment by jmolivas** [comment]
For the record The CLI output this message. (Something wrong with a YAML file, fix and new release by the end of the week)
> commands.yaml.unset.key.yml Unable to parse at line 2 (near "  arguments:").

**Comment by jmolivas** [comment]
Fixed
