### ISSUE TITLE
Fatal Error when enabling module with entity type created via generate:entity:content

### ISSUE THREAD

**Issue by clrockwell79** [hechoendrupal/DrupalConsole#2839]
This is my first real attempt at using DrupalConsole and I absolutely love it - coming from a project where I created custom entities and bundles in code this is such a breath of fresh air - thank you!

I am using 1.0.0-rc6 on a fresh Drupal install that was built using `composer create-project drupal-composer/drupal-project:8.x-dev celav2 --prefer-dist --no-progress --no-interaction`.

I generated a module using `$ drupal generate:module` and then generated an entity using `$ drupal generate:entity:content`.  Everything seemed to go fine until I enabled the module via the GUI.  I received the error: `Fatal error: Class 'Drupal\projects\Entity\ContentEntityBase' not found in /some/irrelevant/paths/web/modules/custom/projects/src/Entity/ProjectEntity.php`

This was because a use statement was missing: `use Drupal\Core\Entity\ContentEntityBase;`.  Should this be included in `entity-content.php.twig`?

If someone wants to guide me I'll happily submit a patch but, again, I'm day one on this so I wouldn't be surprised if I'm missing something.

```
diff --git a/console/templates/module/src/Entity/entity-content.php.twig b/console/templates/module/src/Entity/entity-content.php.twig
index b37eb75..d78620c 100644
--- a/console/templates/module/src/Entity/entity-content.php.twig
+++ b/console/templates/module/src/Entity/entity-content.php.twig
@@ -14,6 +14,7 @@ use Drupal\Core\Field\BaseFieldDefinition;
 {% if revisionable %}
 use Drupal\Core\Entity\RevisionableContentEntityBase;
 {% else %}
+use Drupal\Core\Entity\ContentEntityBase;
 use Drupal\Core\Entity\ContentEntityInterface;
 {% endif %}
 use Drupal\Core\Entity\EntityChangedTrait;
```

Thanks again!

**Comment by clrockwell79** [comment]
Hmm, also note that `use Drupal\Core\Entity\ContentEntityInterface;` isn't necessary in the generated file.  Line 111 in entity-content.php.twig has `implements {{ entity_class }}Interface` -- that generated Interface is what implements `ContentEntityInterface`.

**Comment by jmolivas** [comment]
Seems like this PR fix this issue https://github.com/hechoendrupal/DrupalConsole/pull/2834

**Comment by clrockwell79** [comment]
Yep - sorry my github searching failed me :)
