### ISSUE TITLE
drupal site:mode dev broken?

### ISSUE THREAD

**Issue by andrade1379** [hechoendrupal/DrupalConsole#2848]
Hello, I have a fresh install of Drupal Console and I've read the documentation provided on the DC site and it doesn't seem to be updating the services.yml files when drupal site:mode dev is run.

I've attached screen shots of what I'm seeing. If it's something with how I set things up please let me know.

I cd > web and run drupal site:mode dev
![terminal-shot](https://cloud.githubusercontent.com/assets/1234484/19656732/b980cb46-99e6-11e6-9fc2-5a593e272b30.jpg)

I checked services.yml after command was run and I don't see anything updated especially the debug options.
![services-shot](https://cloud.githubusercontent.com/assets/1234484/19656739/c037bd3c-99e6-11e6-976a-d678552754dc.png)

Since this was not working I had to update the development.services.yml file manually. 
![development-services](https://cloud.githubusercontent.com/assets/1234484/19656798/0910ce86-99e7-11e6-8b0d-9323496c6c10.png)

**Comment by jmolivas** [comment]
@andrade1379 which version are you running?

**Comment by andrade1379** [comment]
Hey @jmolivas, thanks for getting back to me. I have DC version 1.0.0-rc5 and Drupal version 8.2.1.

I am also developing locally using MAMP
PHP: 5.6.25

If there is anymore info I can provide please let me know.

**Comment by Narretz** [comment]
I am seeing this too.
1.0.0-rc.6
Drupal 8.2.0

**Comment by enzolutions** [comment]
@Narretz I just send a PR https://github.com/hechoendrupal/DrupalConsole/pull/2968 to resolve issues with site:mode, please test again after release 1.0.0-rc10 to confirm that is working

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2968 was merged and included on RC-10.

Fee free to re-open if still failing.
