### ISSUE TITLE
Inject services in several commands

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2858]
Some commands still are not being injected the services, like
- site:new
- module:uninstall
- module:install
- database:client (i'm doing a special PR for this command)

**Comment by novia713** [comment]
1. regarding services injection, seems `site:new` command don't need any service :tada: :balloon: 

2. regarding
  * module:install
  * module:uninstall


i'm trying to pass from `shellProcess` to `ProcessBuilder`
but `$appRoot`'s value in those commads is
`/home/leandro/public_html/secundario.dev/web`
instead of
`/home/leandro/public_html/secundario.dev/`
don't know why :(

**Comment by jmolivas** [comment]
@novia713 @igasi is taking care of `site:new` command.

**Comment by novia713** [comment]
`install` and `uninstall` already have constructor with services injected
