### ISSUE TITLE
Pass «query» option to database:client to execute some determined query

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2859]
Use case:
imagine i would like to execute some query on my site like 
`DELETE FROM key_value WHERE name like 'fontawesome';`

i would pass an option "query" to _database:client_ to avoid enter the mysql console and executing directly this query, like
`../vendor/bin/drupal database:client --query="DELETE FROM key_value WHERE name like 'fontawesome';"`

i know this is dangerous and output should be clear, even a confirm message would be nice; but also this is very helpful for chain-scripts or bash-scripts

**Comment by jmolivas** [comment]
@novia713 like the idea but probably this will fit better into a new command how about `database:query`

**Comment by novia713** [comment]
`database:query "my-sql-statement"` working

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/2860 merged
