### ISSUE TITLE
add global option for knowing if the command was executed successfully or gave error

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/DrupalConsole#2866]
what i mean is in a scenario like we have an script in which we want to control a flow of given commands of DrupalConsole and we *need* to know if the command was executed cleanly or gave an error

so (for example) passing the command a _-b_(oolean) option, the command should return 
 * 1 for success
 * 0 for error interruption

_no other info or output should be shown_

this way we could control the flow of several commands' execution
[i can't imagine other way to accomplish this, if it exists, please comment]

DISCLAIMER: i don't have idea about if this is possible, even if this is hard or easy, i only want to pose the question. Perhaps this doesn't worth the effort and the alternative would be to use `stdout` & `stderr`

**Comment by SchnWalter** [comment]
For checking the flow you should probably use the program exit codes.

For bash scripts you might want to read this http://www.tldp.org/LDP/abs/html/exit-status.html

Or you could instruct bash to exit on first error using `set -o errexit` (or it's alias `-e`). See `man bash`
> Exit immediately if a pipeline (which may consist of a single simple command), a subshell command enclosed in parentheses, or one of the commands executed as part of a command list enclosed by braces (see SHELL GRAMMAR above) exits with a non-zero status. The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test following the if or elif reserved words, part of any command executed in a && or ││ list except the command following the final && or ││, any command in a pipeline but the last, or if the command's return value is being inverted with !. A trap on ERR, if set, is executed before the shell exits. This option applies to the shell environment and each subshell environment separately (see COMMAND EXECUTION ENVIRONMENT above), and may cause subshells to exit before executing all the commands in the subshell. 


Here's an example script
```
#!/usr/bin/env bash

# Exit on any error.
set -o errexit

# Verify if the site is configured and exit if not.
ROOT_PATH=$1
#verify_root_path ${ROOT_PATH}

echo 'Bringing the site offline.'
drupal --root="${ROOT_PATH}/web" site:maintenance on

echo 'Running database updates...'
drush --root="${ROOT_PATH}/web" updatedb --yes

echo 'Importing config from the sync directory...'
drush --root="${ROOT_PATH}/web" config-import --yes

# DO MORE STUFF HERE...

echo 'Rebuilding the site cache...'
drush --root="${ROOT_PATH}/web" cache-rebuild

echo 'Bringing the site online.'
drupal --root="${ROOT_PATH}/web" site:maintenance off
```

**Comment by novia713** [comment]
oh, very cool! thanks, @SchnWalter

**Comment by novia713** [comment]
so i will use the excellent answer of @SchnWalter here.
closing.
