### ISSUE TITLE
exception 'ReflectionException' with message 'Class \Drupal\testmodule\Controller\TestModuleEntityController does not exist' with generate:entity:content and revisions enabled

### ISSUE THREAD

**Issue by showards** [hechoendrupal/DrupalConsole#2881]
It looks like when revision capabilities are utilized in generate:entity:content an exception is thrown.  I don't know enough to help with it, but the generation code lives in templates/module/src/entity-content-route-provider.php.twig and was introduced in 0dc8f715.  The offending Class code is not generated when revisions are disabled.  I've attached a rundown of the setup including the exact steps used to generate the error.  The error appears at the bottom of the document.

I'm not sure if it's something I'm doing or if it's missing code in the generate:entity:content portion of Drupal Console. :(

[Drupal Console - New Module Revisions.txt](https://github.com/hechoendrupal/DrupalConsole/files/570370/Drupal.Console.-.New.Module.Revisions.txt)

EDIT: Note, there are errors in the above text when using drupal console; "commands.yaml.unset.key.yml Unable to parse at line 2 (near "  arguments:")."  I am pretty sure those will be fixed in [2878](https://github.com/hechoendrupal/DrupalConsole/pull/2878), though the version of console used is 1.0.0-rc7

**Comment by gone3uo6** [comment]
Controller is not generated using generate:entity:content

**Comment by plopesc** [comment]
I'm having the same issue with Console 1.0.0-rc8 & Drupal 8.2.2

Thanks

**Comment by gone3uo6** [comment]
I think "getControllerPath()" in line 208 in EntityContentGenerator.php...
`$this->extensionManager->getModule($module)->getControllerPath() .'/'.$entity_class.'Controller.php',`
should be "getControllerDirectory()"
which is what is used in ControllerGenerator.php

**Comment by gone3uo6** [comment]
I modded getControllerDirectory() and renamed it to getControllerPath(). Also modded ControllerGenerator.php to use the renamed function. I'll push the changes.
