### ISSUE TITLE
DrupalStyle spaces before message output

### ISSUE THREAD

**Issue by PatrickBauer** [hechoendrupal/DrupalConsole#2893]
Hi guys,
whats the idea behind the space in every DrupalStyle output?

$io->info(), $io->comment(), $io->simple() and $io->text() echo the message with a preceding space. 

Example:
`$message = sprintf('<info> %s</info>', $message);`

Now every time I use writeln() at the OutputInterface (without using DrupalStyle) I have to remember the space or get non-consistent output.

**Comment by jmolivas** [comment]
@PatrickBauer This is by design since `DrupalStyle` extends the `SymfonyStyle` class.

To avoid appending the space use instead the `simple` method added to `DrupalStyle`.

```
$io->simple($message)
```

**Comment by jmolivas** [comment]
@PatrickBauer Also The idea behind the `SymfonyStyle` and `DrupalStyle` is to provide helpers and shortcuts to standardize the output avoiding using the `$output` object by itself and customizing each time
