### ISSUE TITLE
[permission:debug] 

### ISSUE THREAD

**Issue by edutrul** [hechoendrupal/DrupalConsole#2895]
# Motivation

When working permissions you need to know the exact machine name instead of the label that is being displayed in /admin/people/permissions. So a new command is suggestable to display all permissions 
(same functionality as $ plugin:debug ) it should:

1. Get all permission machine name and labels
2. If we pass a parameter it should display machine name, label and also roles that use that permission in the site currently

**Comment by edutrul** [comment]
I am going to be working on it as per conversation with @enzolutions 
WIP PR in a few minutes coming

**Comment by edutrul** [comment]
PR in WIP
https://github.com/hechoendrupal/DrupalConsole/pull/2896

**Comment by edutrul** [comment]
PRs have been merged:

PR [permission:debug] new command #2895
https://github.com/hechoendrupal/DrupalConsole/pull/2896
PR [permission:debug] Add English translation
https://github.com/hechoendrupal/drupal-console-en/pull/30
PR [permission:debug] Add Spanish translation
https://github.com/hechoendrupal/drupal-console-es/pull/7

Please feel free to ask any questions(I'll get back to you asap) or mark this ticket as resolved
It will be a pleasure 
thanks

**Comment by enzolutions** [comment]
Thanks @edutrul for your contribution
