### ISSUE TITLE
services.yml files can't overwritten by drupal console

### ISSUE THREAD

**Issue by nathan-zhu** [hechoendrupal/DrupalConsole#2904]
Hi, 

I'm use drupal console to set my website to dev 

`drupal site:mode dev`

but i got error like below: 

`Services files "/private/var/www/d8/sites/default/services.yml" was overwritten`

it seems not permission problem. i set to 777 for that files but still get error.

i don't know where is wrong , please let me know how to fix it thanks.

**Comment by dinarcon** [comment]
Hi @nathan-zhu, your issue has been reported already. See https://github.com/hechoendrupal/DrupalConsole/issues/2848 for details.

**Comment by enzolutions** [comment]
@nathan-zhu 

Actually, this is not an error, is just a warning that before you used to have services.yml file and was changed by the command you just executed.

I will close this issue becuase works as expected.
