### ISSUE TITLE
[generate:entity:content] Twig_Error_Loader: Template is not defined

### ISSUE THREAD

**Issue by syamvilakudy** [hechoendrupal/DrupalConsole#2906]
**Problem**
After created custom entity by using command generate:entity:content , can't load the View route. Edit and Delete working perfectly.

**How to reproduce**
Drupal version : 8.2.2
Console Version : v1.0.0-rc8
Steps to reproduce:

1. Run command drupal generate:entity:content
2. Run command drush updatedb --entity-updates
3. Go to the corrsponding route ( eg: /admin/structure/book )

-  /admin/structure/book  --- works
- /admin/structure/book/3/edit  ---- works
- /admin/structure/book/3 --- ERROR

Twig_Error_Loader: Template "modules/custom/books/templates/book.html.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "modules/custom/books/templates/book.html.twig" in the Drupal theme registry.). in Twig_Loader_Chain->getCacheKey() (line 146 of /var/www/vendor/twig/twig/lib/Twig/Loader/Chain.php).

**Solution**
The command generate templates folder under the src folder. 

modules
|---books
...... |----src
............|---templates

I have moved templates outside the src folder in order to fixed the issue. 

modules
|---books
.....|----src
.....|----templates

**Comment by jmolivas** [comment]
@syamvilakudy This issue was fixed. Feel free to re-open if still happening you after updating to latest version.
