### ISSUE TITLE
[rest:enable] Does not enable as expected

### ISSUE THREAD

**Issue by edutrul** [hechoendrupal/DrupalConsole#2912]
# Problem/Motivation

I was trying to enable a REST, but when I wanted to check it out in /admin/config/services/rest it doesn't enable as expected, it stays in disabled state.

# How to reproduce

Steps:
1. Make sure you have restui contrib module install https://www.drupal.org/project/restui
2. Go to /admin/config/services/rest) enable an entity resource like for instance "content" which name is "entity:node"
3. You will see "Content" is disabled
4. Then execute "drupal rest:enable"
5. After that type "entity:node" and choose method and authentication provider e.g "GET and basic_oauth"
6. Go back to /admin/config/services/rest
7. You will see it is not enabled

Other details:
Drupal version: 8.2
Console version: 1.0.0-rc8

# Solution

I am going to be working on it and soon I'll have a PR asap

**Comment by edutrul** [comment]
I did initial attempt
PR https://github.com/hechoendrupal/DrupalConsole/pull/2919
I'll keep working on it!

**Comment by edutrul** [comment]
PR implementation:
https://github.com/hechoendrupal/DrupalConsole/pull/2919

PR languages:
English: https://github.com/hechoendrupal/drupal-console-en/pull/39
Spanish: https://github.com/hechoendrupal/drupal-console-es/pull/11

**Comment by jmolivas** [comment]
PR merged.

**Comment by amaisano** [comment]
This is still a problem for me on Drupal console 1.6.1 and Drupal 8.4.5 (installed with composer).
