### ISSUE TITLE
[ERROR] Command "generate:module", is not a valid command name.

### ISSUE THREAD

**Issue by liquidcms** [hechoendrupal/DrupalConsole#2913]
New to DrupalConsole and wasn't getting anywhere with installing it (hadn't used composer in a while although it was installed). Finally i think i got DC installed.

I already had a working D8 install and in that folder i ran 
`  vendor/bin/drupal init (need the full path)`
which seemed to do something.

Now, when i try to generate a new module from this:
`vendor/bin/drupal vendor/bin/generate:module --module reserve --module-path "sites/all/modules/reserve"`

i get the error:
`
[ERROR] Command "generate:module", is not a valid command name.`

any way to tell if i have DC installed correctly?

**Comment by jmolivas** [comment]
@liquidcms is Drupal installed?

**Comment by liquidcms** [comment]
yes..

> I already had a working D8 install and in that folder i ran
> vendor/bin/drupal init (need the full path)
> which seemed to do something.

i think the bottom line is that most "linux" style tools that are command line based and require numerous dependencies be met are extremely tricky to get working in Windows. I have set up drupalvm and will try getting DC working there.

**Comment by twerthmueller** [comment]
Maybe this is also related to the following tasks:

https://github.com/geerlingguy/drupal-vm/issues/1011
https://github.com/hechoendrupal/DrupalConsole/issues/2785

**Comment by jmolivas** [comment]
@liquidcms Starting on RC releases DC must be installed per site.

You can still install the global executable now named Launcher to help you find the drupal installation and DC on that particular site.

Try `drupal list` instead to show the available commands.

**Comment by michaellenahan** [comment]
I got this error for a very basic reason: drupal was not installed yet - the settings.php and the database did not exist yet. Obvious I know, but adding the comment anyway for any other newbies out there.

**Comment by jmolivas** [comment]
@liquidcms @michaellenahan you can execute a `drupal list` to see the available list of commands.

Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by darkdim** [comment]
> you can execute a drupal list to see the available list of commands.
Hi!
I executed this command. This function is not in the list. How to fix it?

**Comment by JPustkuchen** [comment]
Perhaps drupal console was installed via composer and is executed from another directory than the Drupal directory? In which directory do you call the drupal console command?

**Comment by darkdim** [comment]
Thanks, understood.
Installed through the composer, the commands appeared

**Comment by henkRW** [comment]
If you are inside Drupal directory and still see that problem, try to use comand with "--uri" eg. `drupal generate-module --uri=your.domain`

**Comment by brookeheaton** [comment]
Interesting. This wasn't so painful with drush. Is there a way to implement autodetection based on a multi-site directory?

**Comment by weynhamz** [comment]
Downloaded Drupal Console launcher 1.8.0, not showing all generate commands, except gsa.

**Comment by weynhamz** [comment]
Looks like the lastest launcher only contains drupal-console-cole, not drupal-console, why is that, why not just put everything into one executable and distribute, isn't this the recommended way?

**Comment by mmwebaze** [comment]
@weynhamz have you tried the commands below?

Run composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
Run composer update drupal/console --with-dependencies

then depending on where your drupal folder is you could run 

../vendor/bin/drupal gm

**Comment by samaphp** [comment]
I got this error when I'm running Lando instance and executing this outside `lando ssh` and the `drupal console` and `drush` can't work properly if they can not connect to the database.

You can try to execute this `drupal site:status` to make sure that you are able to connect the database. If you got the same error `site:status is not a valid command name` That's mean you have to check the MySQL connection between your command line and the database.

**Comment by virajrajankar** [comment]
This is fixed as suggested here
https://github.com/hechoendrupal/drupal-console/issues/3815#issuecomment-370656209
