### ISSUE TITLE
YAML indentation

### ISSUE THREAD

**Issue by andrewbelcher** [hechoendrupal/DrupalConsole#2915]
`\Symfony\Component\Yaml\Dumper` uses a default indentation of 4, but Drupal standards are 2.

There is a `Dumper::setIndentation` method, which I propose we call whenever we create a dumper (this may only be needed in 2 places in `ExportTrait`).

**Comment by jmolivas** [comment]
We should use the Drupal Yaml dumper instead.

**Comment by jmolivas** [comment]
I send and merge a PR using `Drupal\Component\Serialization\Yaml;` at `ExportTrait `

https://github.com/hechoendrupal/DrupalConsole/pull/2960
