### ISSUE TITLE
DrupalConsole not usable in a project which is not installed by DrupalConsole

### ISSUE THREAD

**Issue by jepster** [hechoendrupal/DrupalConsole#2927]
Hi,

if I am installing Drupal 8, then I am downloading it via Drush and then installing it via "drupal site-install". It seems that by this approach, DrupalConsole is unusable. I have switched between PHP 5.6 and 7.0 in the CLI to check, but it behaves always the same:

> peter@computer ~/Websites/pbt-d8 $  drupal init --override
> Uncaught PHP Exception Drupal\Core\Database\InvalidQueryException: "Query condition 'ti.tid IN ()' cannot be empty." at /home/peter/Websites/pbt-d8/core/lib/Drupal/Core/Database/Query/Condition.php line 71
> 
>                                                           
>   [Symfony\Component\Console\Exception\RuntimeException]  
>   The "--shellexec_output" option does not exist.         
>                                                           
> 
> init [--override] [--local] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env [ENV]] [--root [ROOT]] [--no-debug] [--learning] [-c|--generate-chain] [-i|--generate-inline] [-d|--generate-doc] [-t|--target [TARGET]] [-l|--uri URI] [-y|--yes] [--] <command>
> 
> peter@computer ~/Websites/pbt-d8 $ 

Has anyone a clue?

**Comment by jepster** [comment]
I have downloaded a fresh copy of latest stable Drupal 8. Afterwards I am getting this output, in the root folder of the Drupal 8 project:

> peter@computer ~/Websites/pbt-d8 $ drupal list
> 
>                                                           
>   [Symfony\Component\Console\Exception\RuntimeException]  
>   The "--shellexec_output" option does not exist.         
>                                                           
> 
> list [--xml] [--raw] [--format FORMAT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env [ENV]] [--root [ROOT]] [--no-debug] [--learning] [-c|--generate-chain] [-i|--generate-inline] [-d|--generate-doc] [-t|--target [TARGET]] [-l|--uri URI] [-y|--yes] [--] <command> [<namespace>]
> 
> peter@computer ~/Websites/pbt-d8 $

**Comment by jmolivas** [comment]
@jepster try editing your `~/.console/config.yml` an removing the line containing `--shellexec_output`

**Comment by jepster** [comment]
Thanks, it seems that this setting has figured out my issue.
