### ISSUE TITLE
[generate:controller] (1.0.0-rc9) Command not working properly

### ISSUE THREAD

**Issue by ultimike** [hechoendrupal/DrupalConsole#2945]
When running the generate:controller command on a new module (immediately after running generate:module), and going through all the prompts, Drupal Console returns an exception:

[ReflectionException]                                                
  Class \Drupal\hello_world\Controller\HelloController does not exist

The controller and routing file are created, and are correct except that the controller file name is incorrect. For example, when I give the controller class a name of "HelloController", the filename ends up as HelloControllerController.php

-mike

**Comment by jmolivas** [comment]
@ultimike Nice catch. Fixed on this PR https://github.com/hechoendrupal/DrupalConsole/pull/2948
