### ISSUE TITLE
[ERROR] Command "site:new", is not a valid command name.

### ISSUE THREAD

**Issue by MatteoBorgognoni** [hechoendrupal/DrupalConsole#2947]
Hi,
I've installed drupal console 1.0.0-rc9 on a virtual machine using vagrant on an ubuntu virtualbox with php7
but I'm unable to run site:new or site:install and What I get is:
 [ERROR] Command "site:new", is not a valid command name.

I searched online but I haven't found any answer to this.
I'd appreciate any help.

**Comment by marcelovani** [comment]
See https://github.com/hechoendrupal/DrupalConsole/issues/2825
To use site:new you need to use drupal console 1.0.0-beta5
