### ISSUE TITLE
site:new should provide an option to choose the project template to use. Currently hard coded drupal-composer/drupal-project

### ISSUE THREAD

**Issue by marcelovani** [hechoendrupal/DrupalConsole#2949]
I would like to use my fork of drupal-composer/drupal-project
For that, we need a new option on site:new command
i.e. `drupal site:new /var/www/new --composer --template=dennisdigital/drupal-project`

**Comment by marcelovani** [comment]
#2950

**Comment by smalot** [comment]
+1
however, an PR is already opened to migrate this command to the drupal-console-launcher

**Comment by marcelovani** [comment]
Can you point me to the issue?
I can add this once the PR is accepted.

**Comment by marcelovani** [comment]
With this PR, site:new could be done as a chain
https://github.com/hechoendrupal/DrupalConsole/pull/2961

**Comment by jmolivas** [comment]
@marcelovani  Closing this because the `site:new` was mode to console-core as chain command.
