### ISSUE TITLE
generate:permissions (1.0.0-rc9) not working

### ISSUE THREAD

**Issue by ultimike** [hechoendrupal/DrupalConsole#2957]
Hmm - generate:permissions doesn't seem to be working, it prompts me for all the information correctly, but doesn't result in a modulename.permissions.yml file.

No errors are reported, and the resulting file is not displayed (as it is with generate:module, for example). I tried running it with -vvv, no additional information was provided.

I've tested this with some students, and none of us can get it to work.

thanks,  
-mike

**Comment by jmolivas** [comment]
@ultimike Nice catch. Fixed on this PR #2959 

This can be applied as patch using 
https://patch-diff.githubusercontent.com/raw/hechoendrupal/DrupalConsole/pull/2959.patch

**Comment by ultimike** [comment]
Sweet. Thanks!
 
-mike
