### ISSUE TITLE
[generate:entity:*] Permissions for new generated entity don´t appers in existing permissions.yml file.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#297]
Moved from URL at d.o. https://www.drupal.org/node/2393097 created by malotor 
Permissions for new generated entity don´t appears in existing permissions.yml file.
```
default_entity.list:
path: '/admin/default_entity'
defaults:
_entity_list: 'default_entity'
_title: 'DefaultEntity List'
requirements:
_permission: 'view DefaultEntity entity'
```
But I can´t find "view DefaultEntity entity" permission i my example.permissions.yml

**Comment by omero** [comment]
The #688 PR solves this issue, but i think the config and content entity generators needs a full refactor, based in the new Drupal updates :worried:

**Comment by jmolivas** [comment]
I tested the PR #688 and yes fixed the issue. 

Totally agree with you @omero about a needed refactor to content & config entity generators.
