### ISSUE TITLE
Undefined index: commands

### ISSUE THREAD

**Issue by alexey-kuznetsov** [hechoendrupal/DrupalConsole#2973]
Just installed Drupal Console. It ssems to be working, but when I run any command I see the following warnings in terminal:
`PHP Notice:  Undefined index: commands in phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/ConfigurationManager.php on line 273
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Bootstrap\DrupalConsoleCore->boot() phar:///usr/local/bin/drupal/bin/drupal.php:27
PHP   5. Drupal\Console\Utils\ConfigurationManager->loadConfiguration() phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php:47
PHP   6. Drupal\Console\Utils\ConfigurationManager->appendCommandAliases() phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/ConfigurationManager.php:83
`
But everything works properly. My system is Ubuntu 16.04, php 7.0.9 and Drupal Console 1.0.0-rc9

**Comment by Cyborg572** [comment]
I started seeing this after an update. I didn't have anything custom in my `~/.console` folder, so on a hunch I deleted it and re-ran `drupal init`, and now the error's gone.
(EL Capitan, php 5.5.30, Drupal Console 1.0.0-rc9)

**Comment by jmolivas** [comment]
This will be fixed on RC-10. But yes as mentioned by @Cyborg572 executing `drupal init` is a way to have this fixed.

**Comment by jmolivas** [comment]
@Cyborg572 can you try updating to latest RC-10 version. This should be fixed now.

**Comment by alexey-kuznetsov** [comment]
Thanks, it's fixed now.
