### ISSUE TITLE
[ERROR] Command "site:install", is not a valid command name.

### ISSUE THREAD

**Issue by gsalgadotoledo** [hechoendrupal/DrupalConsole#2978]
I'm just downloaded and installed drupal console and everithing was ok in the installation proccess but when I try to create my first project to generate bolearpleates, this errors is comming up:

[ERROR] Command "site:install", is not a valid command name.

![captura de pantalla 2016-11-22 a las 11 26 58 p m](https://cloud.githubusercontent.com/assets/1288502/20551205/7634b776-b10b-11e6-98a8-a4e6f1572a0c.png)

I've already run before to this
drupal init --override

drupal check is saing ok and but
drupal chain --file=~/.console/chain/quick-start.yml
[ERROR] Command "chain", is not a valid command name.

![captura de pantalla 2016-11-22 a las 11 35 14 p m](https://cloud.githubusercontent.com/assets/1288502/20551299/b64aacca-b10c-11e6-9317-4dceabf0c13a.png)

I traied installing a new drupal copy through drush and use drupal console into that new drupal copy installed is throwing:

 [ERROR] Drupal Console is not installed at:

I'm using MAC OS Capitan Version

Thanks for build and support this kind of tools

**Comment by jmolivas** [comment]
@gsalgadotoledo you need to be inside a drupal site in order to run the `site:install` command. 

Try cd `path/to/drupal-site` and then execute the command 

Make sure you install DrupalConsole on the site you can find instructions at 
https://github.com/hechoendrupal/DrupalConsole/#download-as-new-dependency

**Comment by gsalgadotoledo** [comment]
Great! I had composer installed and I just run into of path/to/my/mynewdrupalproyect:

composer create-project \
drupal-composer/drupal-project:8.x-dev \
drupal8.dev \
--prefer-dist \
--no-progress \
--no-interaction
