### ISSUE TITLE
[generate:entity:content] add bundles support

### ISSUE THREAD

**Issue by christianwiedemann** [hechoendrupal/DrupalConsole#299]
Hi,
it would be nice to add a bundle option to the generate:entity:content command, which generates also the ConfigEntityType Entity (e.g. NodeType for Nodes) to have bundle support. 

Thanks 
Christian

**Comment by socketwench** [comment]
Bundle generation would be a great addition since it's not obvious. Instead of making an option under one of the generate commands, it would make more sense to me for another top-level command: generate:entity:bundle?

**Comment by jmolivas** [comment]
Like the idea of separating the command. I will look for the docs and paste it here to have a better idea of what is needed.

**Comment by cosmicdreams** [comment]
I talked with @jmolivas about this issue.

Sounds like we have plan for implementing it.  The plan:

1. Create a content type and export it's config
2. Create a command to import the config while placeholdering / replacing the bundle name 
3. Assign the command to generate:content:type
4. Document it and SHIP IT

**Comment by cosmicdreams** [comment]
I was able to complete step 1, but in looking at what I will need to do for step 2 I was wondering...  Where should I put the config I exported?  Is there another command I can look at for guidance on the kind of work I'll need to do in order to finish this?

**Comment by cosmicdreams** [comment]
I have worked up the basics of what I mentioned above.  I don't seem to have the ability to push these changes to you because of permission issues.
