### ISSUE TITLE
`setRevisionAuthorID()` etc. are deprecated, don't include them when generating entity code

### ISSUE THREAD

**Issue by pfrenssen** [hechoendrupal/DrupalConsole#2996]
The best practice for revisionable entities is to extend `RevisionLogInterface` and use `RevisionLogEntityTrait` to provide the logic for working with revisions.

When a new entity is generated with the current version of DrupalConsole it includes methods such as `setRevisionAuthorId()` which are now deprecated (ref. [Issue #2718583: Remove deprecated usages of Node::setRevisionAuthorId() and Node::getRevisionAuthor()](https://www.drupal.org/node/2718583)).

**Comment by GDrupal** [comment]
Investigating this I think that we also need to update entity and entity interface creation templates with RevisionLogInterface:
https://www.drupal.org/node/2705433
I will be workign on this I hope I can submit a Pr soon.

**Comment by jmolivas** [comment]
PR merged https://github.com/hechoendrupal/DrupalConsole/pull/3030

**Comment by pfrenssen** [comment]
Great, thanks @GDrupal!

**Comment by GDrupal** [comment]
You are welcome! :)
