### ISSUE TITLE
generate:controller requires missing trait

### ISSUE THREAD

**Issue by twhiston** [hechoendrupal/DrupalConsole#3003]
Current master branch command generate:controller includes `use Drupal\Console\Command\Shared\InputTrait;` but this trait doesn't exist in the repo at the moment

**Comment by jmolivas** [comment]
@twhiston this is an issue with master since got relocated to drupal-console-core this will be fixed on the upcoming release.

**Comment by jmolivas** [comment]
@twhiston this should be fixed try updating your project dependencies.

**Comment by jmolivas** [comment]
This will be fixed one you update to latest drupal-console-core
