### ISSUE TITLE
[database:dump] Don't duplicate .gz file extension 

### ISSUE THREAD

**Issue by rpsu** [hechoendrupal/DrupalConsole#3013]
Currently passing both `--file=[FILE]` and `--gz` -options work fine. However, when using a [FILE] name ending in .gz extension the end result file name gets the `.gz` extension duplicated. 

Would it make sense  to not duplicate the file extension? I'm not sure if it breaks some automated workflows. 
Currently
`drupal database:dump --file=/vagrant/db_dumps/myfile.sql.gz --gz`
results to 
`/vagrant/db_dumps/myfile.sql.gz.gz`

I'm proposing it should result to
`/vagrant/db_dumps/myfile.sql.gz`

**Comment by rpsu** [comment]
#3014

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/DrupalConsole/pull/3014 merged
