### ISSUE TITLE
console rc11 should depend on console-core rc11.

### ISSUE THREAD

**Issue by cburschka-pwc** [hechoendrupal/DrupalConsole#3015]
A lot of stuff seems to have been refactored out from this repository and into drupal/console-core. That means the latest of this package requires the latest version of that package.

Unfortunately, console still only depends on console-core ~1.0. If the upgrade of console-core is denied for any reason (in this case it was the dependency on dflydev/dot-access-configuration at dev-master), composer will simply hold back drupal/console-core at rc10 while upgrading drupal/console to rc11. That seems to break a lot of the commands.

**Comment by cburschka-pwc** [comment]
It's actually even worse than that, because even removing and reinstalling doesn't seem to work correctly right now.

    $ composer require drupal/console:^1

results in drupal/console:1.0.0rc11, drupal/console-core:1.0.0rc10 and drupal/console-en:1.0.0rc9.

**Comment by jmolivas** [comment]
try  
```
composer require drupal/console:~1.0 --with-dependencies
```


```
composer require drupal/console
# then 
composer update
```

**Comment by jmolivas** [comment]
@cburschka-pwc  I will make this change starting on RC-12 make dependencies forced to current version.

**Comment by jmolivas** [comment]
@cburschka-pwc  RC-12 was tagged and now are forcing dependencies to latest version.
https://github.com/hechoendrupal/DrupalConsole/blob/1.0.0-rc12/composer.json#L40

**Comment by jmolivas** [comment]
@cburschka-pwc can you confirm this issue continue to happening you after updating to RC12 ?

**Comment by cburschka-pwc** [comment]
That fixed it! 👍 

Updating drupal/console on its own via `composer update drupal/console` is blocked now, since you need to either add `--with-dependencies` (which also makes non-required updates, like updating the symfony packages to 3.*) or explicitly specify `drupal/console-en` and `drupal/console-core` to update too. But that is much better than installing incompatible versions and then having to diagnose the PHP error. :) )
