### ISSUE TITLE
Warning "should install drupal first" even though drupal installed

### ISSUE THREAD

**Issue by mohankumargupta** [hechoendrupal/DrupalConsole#3020]
NOOB obstacle with Drupal Console.
Drupal Console version 1.0.0-rc11

I'm trying to follow this:
https://www.drupal.org/node/2718229

So I wrote a script called installdrupal8.sh as follows:

```bash
#!/usr/bin/env bash

if [ -z "$1" ];
then
  echo "Must enter a project name"
exit 1
fi

if [ -d "$1" ];
then
  rm -rf "$1" 
fi

export COMPOSER_PROCESS_TIMEOUT=6000
composer clear-cache
composer create-project drupal-composer/drupal-project:8.x-dev "$1" --stability dev --no-interaction
cd "$1"
composer config repositories.drupal composer
```
All went well, I was even able to do 

```bash
composer require drupal/flag
```

However, when I try, any of the following 
```shell
mohan@MOHAN-HP:/mnt/c/Users/mohan/Sites/drupal-8.2.4$ vendor/bin/drupal --root=./web list
mohan@MOHAN-HP:/mnt/c/Users/mohan/Sites/drupal-8.2.4/web$ ../vendor/bin/drupal list 
```
I get the famous **"[WARNING] In order to list all of the available commands you should install               drupal first"**. 
The same is true if I install Drupal Console Launcher globally as well. Not sure what I am doing wrong. I am running this on Windows 10 using the new "Bash on Ubuntu". Using Acquia Dev Desktop.

The following works fine: 
```shell
mohan@MOHAN-HP:/mnt/c/Users/mohan/Sites/drupal-8.2.4/web$ ../vendor/bin/drush status
```

Thanks
Mohan

**Comment by jmolivas** [comment]
Is your site installed? 

The following message is just telling you Drupal is not yet installed.

> [WARNING] In order to list all of the available commands you should install drupal first

**Comment by jmolivas** [comment]
If using the Launcher try

Download a new Drupal project
```
drupal site:new
```
Download, install and serve a new Drupal project
```
drupal quick:start
```

**Comment by raspberrypisig** [comment]
Yes I installed Drupal, but not through Drupal Console, instead using Acquia Dev Desktop to serve and create db, because that is normally how I install drupal. I will do what you recommended.

**Comment by jmolivas** [comment]
@raspberrypisig if you prefer installing using the UI is fine you can use the CLI to for speed reasons and click less using the `site:install` command.

**Comment by mohankumargupta** [comment]
Thanks for your help. I was able to get my opinionated Drupal 8 install script working for my environment.

```bash
#!/usr/bin/env bash
#apt-get -y install php5-cli php5-gd php5-curl php5-mysql git
#set -x
disown >/dev/null 2>/dev/null
ps aux|head -n -2|grep php|cut -f5 -d' '| xargs -I {} kill {}

if [ -z "$1" ];
then
  echo "Must enter a project name"
exit 1
fi

if [ -d "$1" ];
then
  echo "The directory name already exists. Overwrite? (y/n) default n:"
  read response
  if [ -z $response ] || [ $response != "y" ];
  then
    exit 0
  else
    cd "$1"
    drupal help serve --quiet 1>/dev/null 2>&1
    previousinstall=$?
    if [ $previousinstall -eq 0 ];
    then
      echo "Dropping tables from db"
      #sudo service mysql start
      drupal database:drop --no-interaction
      #sudo service mysql stop
    fi
    cd ..
    echo "Removing directory: $1"
    rm -rf "$1"
  fi
fi

export COMPOSER_PROCESS_TIMEOUT=6000
#composer clear-cache
composer create-project drupal-composer/drupal-project:8.x-dev "$1" --stability dev --no-interaction
cd "$1"
drupal init --override --no-interaction
sudo service mysql restart
sleep 10
drupal site:install  \
     --langcode="en" \
     --db-type="mysql" --db-host="127.0.0.1" --db-name="drupal824"  \
     --db-user="root" --db-pass="password" --db-port="3306"  \
     --site-name="drupal824" --site-mail="a@b.com"  \
     --account-name="admin" --account-mail="a@b.com" --account-pass="password" \
     --force --no-interaction \
       standard

(drupal server & 2>&1) 1>/dev/null
sleep 20
echo -e "\n"
echo -e "0\n" | drupal config:override system.performance js.preprocess 0
echo -e "0\n" | drupal config:override system.performance css.preprocess 0
drupal module:install hal
```
Needed to disable aggregating css and js, otherwise admin theme and website theme would break.
Goodbye drush and drush make!

**Comment by jmolivas** [comment]
@mohankumargupta  Awesome, you can probable make that script using chain files, you can find examples at https://github.com/hechoendrupal/drupal-console-core/tree/master/config/dist/chain all those examples should be at your `~/.console/chain` after running `init` command.
