### ISSUE TITLE
[generate:module] Validate modules with drupal.org

### ISSUE THREAD

**Issue by lucasmingarro** [hechoendrupal/DrupalConsole#386]
This come from issue #296. There is a function that should be implemented to verify if the modules dependencies that the user type and are not available locally. 

```
check GeneratorModuleCommand.checkDependencies()
```

**Comment by enzolutions** [comment]
I did  a PR to resolve this problem  https://github.com/hechoendrupal/DrupalConsole/pull/716

This change don't stop the generation only warning, because could be resolved later

**Comment by enzolutions** [comment]
This solution will be implemented in release 0.7.15
