### ISSUE TITLE
[standard] Define standards for Issues, PRs and local builds

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#392]
We talk about the need of define standards for naming issues, PRs and run local builds during DrupalCon Bogota:
* Naming convention for issues and possibly branches.
* Adding git hooks to automate:
 * Run phpunit
 * Validate code using tools like:
    * http://cs.sensiolabs.org/
    * https://insight.sensiolabs.com/
* Investigate about running travis locally maybe using https://github.com/jolicode/JoliCi

**Comment by danielnv18** [comment]
@jmolivas I saw that you rename all the issues. You should add something on the README.md or in the documentation about it
Also I can help you to make sure the current code follow the psr-1/2 code standards and from time to time I run the https://insight.sensiolabs.com/ test

**Comment by jmolivas** [comment]
@danielnv18 I added this issue to discuss about this and get recommendations like this that you mentioned about adding to the README. I was thinking to make that instructions part of the how to contribute section on the gitbook.

**Comment by danielnv18** [comment]
The correct place should be the documentation page but you could add link to that specific part of the documentation

**Comment by esod** [comment]
Does TravisCi do more than run phpunit tests? If it does not, won't running the tests locally be enough?

I'm planning on writing a blog post on running xdebug, phpunit, and phpstorm together on yosemite os. Since I know the tests have run successfully on my local system, I don't need to be concerned when TravisCI takes such a long time to run.

**Comment by danielnv18** [comment]
TravisCi is more like automated testing plataform for unit-testing. You can set the several OS and php version like HHVM, 5.4 etc

**Comment by danielnv18** [comment]
and in this case is a Open source project but you use the pay version you can add Concurrent Jobs and private repos

**Comment by esod** [comment]
I see. Thanks for the clarification. I'll have to give joliCi a try.

**Comment by jmolivas** [comment]
Closing this one since we have a page related to how to contribute:
http://hechoendrupal.gitbooks.io/drupal-console/content/contribute_to_drupal_console/create-an-issue.html
