### ISSUE TITLE
[standard] Add docblock line notice, code generated by project 

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#394]
Twig template to be updated `src/Resources/skeleton/base/class.php.twig`
```
{% block file_docblock %}
/**
 * @file
 * Contains {% block file_path %}{% endblock %}
 *
 * Class generated by drupal console project.
 */
{% endblock %}
```

Class generated will look like this:
```
/**
 * @file
 * Contains Drupal\demo\Controller\MyController.
 *
 * Class generated by drupal console project.
 */
```

**Comment by danielnv18** [comment]
related #57

**Comment by omero** [comment]
:+1: absolutely agree with that @jmolivas

**Comment by davereid** [comment]
What benefit would this have? I would probably be removing those lines from my generated code if they were there.

**Comment by jmolivas** [comment]
@davereid make sense, people would probably be removing those lines from the generated code, discarding this and closing it.
