### ISSUE TITLE
[config:export:content:type] --remove-uuid --remove-config-hash options work half the time

### ISSUE THREAD

**Issue by gitressa** [hechoendrupal/DrupalConsole#3965]
When I issue this command, half the files still have uuid and hash-code inside them:
`vendor/bin/drupal config:export:content:type product --module="demo" --remove-uuid --remove-config-hash --optional-config` 

The files without `x` still has UUID and default_config_hash inside:

```
x core.entity_form_display.node.product.default.yml
x core.entity_view_display.node.product.default.yml
x core.entity_view_display.node.product.teaser.yml
  core.entity_view_mode.node.teaser.yml
x field.field.node.product.body.yml
x field.field.node.product.field_category.yml
x field.field.node.product.field_text.yml
  field.storage.node.body.yml
  field.storage.node.field_category.yml
  field.storage.node.field_text.yml
x node.type.product.yml
  taxonomy.vocabulary.tags.yml
```
Also, I am prompted `Export content type in module as an optional configuration (yes/no) [yes]:`, which shouldn't be necessary, according to the [documentation](https://docs.drupalconsole.com/en/commands/config-export-content-type.html).

If I add `=yes` like this, I am not prompted:
`vendor/bin/drupal config:export:content:type product --module="demo" --remove-uuid --remove-config-hash --optional-config=yes`

- Drupal 8.6.2, from https://github.com/drupal-composer/drupal-project
- drupal/console 1.8.0

**Comment by ceonizm** [comment]
I can confirm I had encountered the same behavior 
drupal 8.6.3 drupal/console 1.8.0

**Comment by LOBsTerr** [comment]
@gitressa Thank you for the report. I will check it.

**Comment by LOBsTerr** [comment]
PR https://github.com/hechoendrupal/drupal-console/pull/3989

Fixed.
I found and fixed also another bug. When we run the command in non-interaction mode optional-config option is not applied.
Also I refactored a little bit the code
