### ISSUE TITLE
[generate:module] Problem getting local module list

### ISSUE THREAD

**Issue by lucasmingarro** [hechoendrupal/DrupalConsole#397]
The checkDependencies function should check the list of local modules available in the following way:
```
$local_modules = $this->getModules(true);
```
This works fine when you run `console` under the D8 directory but when you run the unit test it fails because the `getModules()` method needs `Drupal\Core\Extension\ExtensionDiscovery`. You can check this at `ContainerAwareCommand.php` 

Currently the `$local_modules = null;` just to pass the test but should be fixed.

see: issues #296 and #386

**Comment by enzolutions** [comment]
Duplicate with https://github.com/hechoendrupal/DrupalConsole/issues/386
