### ISSUE TITLE
[generate:plugin] Generate a basic plugin

### ISSUE THREAD

**Issue by socketwench** [hechoendrupal/DrupalConsole#411]
Providing a basic plugin requires a lot of boilerplate code. Adding generator would encourage use of custom plugins within modules. There's a patch in progress at https://www.drupal.org/node/1668362 to add a basic plugin and plugin manager to Examples.

**Comment by jmolivas** [comment]
This make total sense, if I am not wrong @dmouse was working in this or similar generator.

**Comment by dmouse** [comment]
Yes, I have a branch with the base code to generate a new plugin type but I not have a necessary time to terminate the questions and validations.

https://github.com/dmouse/DrupalAppConsole/compare/plugin-manager

**Comment by Sutharsan** [comment]
See https://github.com/hechoendrupal/DrupalConsole/pull/752 for an annotation (discovered) type plugin generator.
Next thing would be a generator for yaml (discovered) type plugins.

**Comment by Sutharsan** [comment]
I've created a PR for a plugin type with Yaml discovery. See https://github.com/hechoendrupal/DrupalConsole/pull/757.

**Comment by enzolutions** [comment]
@dmouse PR https://github.com/hechoendrupal/DrupalConsole/pull/499 resolve this problem or is a WIP work?

**Comment by jmolivas** [comment]
Seems like completed, feel free to add comments or re-open.
