### ISSUE TITLE
[translation] Sync all translations files

### ISSUE THREAD

**Issue by lucasmingarro** [hechoendrupal/DrupalConsole#417]
There are many diff between the translations files. I think the better way to do is with some tool just coded or try to code something

**Comment by jmolivas** [comment]
:+1: On this one, we need to fix this before turnos into a problem.

* We maybe can do something like this: load en (default) + es/fr/pt
https://github.com/hechoendrupal/DrupalAppConsole/blob/master/src/Command/Helper/TranslatorHelper.php#L34

* And then dump using this class 
https://github.com/hechoendrupal/DrupalAppConsole/blob/master/src/YamlFileDumper.php

**Comment by kgaut** [comment]
I've just made a manual diff in order to sync french file.

**Comment by enzolutions** [comment]
I just sync translation files in PR https://github.com/hechoendrupal/DrupalConsole/pull/720

Now is each new release all translation will be sync using the new command **$ drupal merge:yaml** as you can see below.

```
$ drupal yaml:merge console.pt-new.yml console.en.yml console.pt.yml
$ mv console.pt-new.yml console.pt.yml
```
