### ISSUE TITLE
[console] Remove all defaults console options

### ISSUE THREAD

**Issue by lucasmingarro** [hechoendrupal/DrupalConsole#420]
When you run a `--help` the console shows a a lots of default options that in fact we are no using.
For example
```
console.dev site:status --help                                                                                                                                             1 ↵
Usage:
 site:status [--all] [field-group]

Arguments:
 field-group           Show a set of fields groupping by type All available groups are: version, database, theme, directories

Options:
 --all                 Show all available groups data in the report, even if there are a lot.
 --help (-h)           Display this help message
===============  synfony defaults ===============
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question
 --bootstrap-file (-b) Path to Drupal bootstrap file (core/includes/boostrap.inc).
 --shell (-s)          Launch the shell.
 --env (-e)            The Environment name. (default: "prod")
 --no-debug            Switches off debug mode.
===============  End synfony defaults ============
```

**Comment by jmolivas** [comment]
Totally agree, if we are not taking advantage and using those, them must be removed.

I like to have the more opinions we can have into this cc: @dmouse @omero @enzolutions

**Comment by dmouse** [comment]
I use many of the options for development or for everyday use console.

--shell I love this mode is fast and cool =P

--verbose is helpful for debugging and future versions we plan to add extra functionality to the commands.

--version is necessary

--env By default Drupal uses only one env but  at least he used dev and prod.

--bootstrap this option was removed at #421 but add the option to define the Drupal root

--quiet, thinking in the cron jobs this option would be very useful

I think we should at least focus on these options work in good way.

**Comment by jmolivas** [comment]
`--shell` I never use this one but no hurt keeping it 

`--verbose` we have not implemented anything yet, we discuss to use this for educational purpose as render code with extended documented docblocks

`--version` we use it to display version & self-update 

`--env` I don't see a reason to keep if Drupal only runs on prod

`--bootstrap` was removed as @dmouse mentioned

`--quiet` Not used yet

We may try to disable or remove the default options we are not using it and then enable when required.

**Comment by mikeyp** [comment]
I would love to see the bootstrap option restored, as it is, it's very difficult to bundle a specific version of the console with a project repo, since I can't bin stub it by specifying the path to the drupal bootstrap file.

**Comment by jmolivas** [comment]
hey @mikeyp thanks for commenting, we are planning to support site aliases as drush does, will that may solve you issue ?

**Comment by jmolivas** [comment]
Also feel free to mention some ideas @mikeyp

**Comment by jmolivas** [comment]
Instead of `--bootstrap` you can use `--drupal` @mikeyp 

We wiIl keep those
```
Options:
 --xml                 To output help as XML
 --format              To output help in other formats (default: "txt")
 --raw                 To output raw command help
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question
 --drupal (-d)         Path to Drupal root.
 --shell (-s)          Launch the shell.
 --env (-e)            The Environment name. (default: "prod")
 --no-debug            Switches off debug mode.
 --learning            Generate a verbose code output.
```

**Comment by jmolivas** [comment]
I am closing this one. We leave the defaults even if we are not using all of them, we can re-open or open a new issue once we are close to a 1.x release.
