### ISSUE TITLE
[generate:plugin:field-type] Generate a new field type

### ISSUE THREAD

**Issue by damienmckenna** [hechoendrupal/DrupalConsole#446]
Create a new field type, which could then work with a generated field widget (#248) to speed up creation of custom fields.

**Comment by Jaesin** [comment]
I second the notion. There are three plugins that need to be implemented to create a new field. The field type ([@FieldType](https://www.drupal.org/node/2064123) [plugin](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Field!Plugin!Field!FieldType!StringItem.php/class/StringItem/8)) , the widget ([@FieldWidget plugin](https://api.drupal.org/api/drupal/core!modules!file!src!Plugin!Field!FieldWidget!FileWidget.php/class/FileWidget/8) ) and the field formatter ([@FieldFormatter plugin] (https://api.drupal.org/api/drupal/core!modules!link!src!Plugin!Field!FieldFormatter!LinkFormatter.php/class/LinkFormatter/8)).

**Comment by Sutharsan** [comment]
Working on this...

**Comment by Sutharsan** [comment]
Code in PR https://github.com/hechoendrupal/DrupalConsole/pull/753

**Comment by Sutharsan** [comment]
PR has been merged. Lets close this issue.
