### ISSUE TITLE
[console] Implement and document mechanism to allow contrib commands

### ISSUE THREAD

**Issue by fluxsauce** [hechoendrupal/DrupalConsole#458]
I'd like to add https://github.com/fluxsauce/site_audit/tree/8.x-2.x integration.

**Comment by jmolivas** [comment]
:+1:

**Comment by fluxsauce** [comment]
To clarify the scope; allow contrib commands to be added that aren't part of a Drupal installation.

**Comment by Jaesin** [comment]
So you are saying console should search in `~/.drupal_console/modules-enabled` (Or something like that) for drupal modules with console commands.

**Comment by fluxsauce** [comment]
@Jaesin I was thinking something similar to Drush commands, which can be installed in places like `~/.drush/commands`.

Ideas:

* `~/.drupal_console/contrib`
* `~/.drupal_console/commands`
* `~/.drupal_console/vendor`

Thoughts?

**Comment by jmolivas** [comment]
The command discovery mechanism search for command classes at DrupalConsole + DrupalCore + Custom modules.

We can update the code to search for commands classes at common place like you mentioned I was thinking to use  `~/.console/src/Command/`.

**Comment by jmolivas** [comment]
For commands inside a contrib module command classes must be created at `MODULE_NAME/src/Command` if the command is a generator then the generator class must be created at `MODULE_NAME/src/Generator`

https://github.com/lussoluca/webprofiler/tree/8.x-1.x/src/Command

**Comment by jmolivas** [comment]
@Jaesin & @fluxsauce I will close and add a new issue on the documentation project repository.

Related issue:
https://github.com/hechoendrupal/drupal-console-book/issues/57
