### ISSUE TITLE
[server:run] Is it possible to implement server:run?

### ISSUE THREAD

**Issue by czettnersandor** [hechoendrupal/DrupalConsole#471]
One very handy feature in the Symfony Console is the server:run command, which by default starts the application server in development environment using PHP's built-in web server. In this way, I don't have to set up apache to develop a Symfony application.

Would be possible to implement this for the Drupal Console?

Does Drupal requires Apache to run and .htaccess to be utilised?

Does Drupal 8 implements anything which is preventing server:run to implement?

**Comment by czettnersandor** [comment]
After a quick research, I realised it's a bit stupid question. Simply this works:

```
php -S localhost:8000
```

However, I would see template hints are turned on, Twig cache is turned off so I don't have to do it manually. The other problem is that Console is relying on the settings.php and returns with this when I try to run it before I install Drupal:

```
  [RuntimeException]                               
  Missing $settings['hash_salt'] in settings.php
```

But it should be possible to provide a limited functionality when settings.php is not present which could allow server:run command to run.

I think this would be a killer feature. Let's discuss.

**Comment by jmolivas** [comment]
We did talk about adding this feature few weeks ago, and agree this could be a really nice feature have it.

We event talk to taking a look at this project and evaluate if provide any advantage vs built in PHP server.

https://github.com/yosymfony/HttpServer

**Comment by jmolivas** [comment]
Related to the error is a know issue #463 and I am currently working on have it fixed.

**Comment by jmolivas** [comment]
I send a PR https://github.com/hechoendrupal/DrupalAppConsole/pull/482 fixing the RuntimeException:
```
  [RuntimeException]                               
  Missing $settings['hash_salt'] in settings.php
```

**Comment by jmolivas** [comment]
@czettnersandor I really like to have the `server:run`command available

We have discussed before, having commands running outside of a drupal installation or not depending on drupal to be previously installed as:
* `site:install`
* `site:download`
* `server:run`

Also take advantage of site alias, we take this PR https://github.com/hechoendrupal/DrupalAppConsole/pull/482 as an starting point to make that happen.

**Comment by mikeyp** [comment]
I would love to help build a robust development server using the built-in PHP web server or possible with the HttpServer component. I've already spent time working on a Drupal module that provides better developer experience at https://www.drupal.org/project/console_logger and if possible, I would love to see those features built in to the server and not as a module.

**Comment by jmolivas** [comment]
:+1:  I love the idea  @mikeyp 

I just tried [spress](https://github.com/spress/Spress/) a statics site generator, this projects implement the [HttpServer](https://github.com/yosymfony/HttpServer) component.

`$ spress site:build --server --watch`

This how it looks like:

![spress-builtin-server](https://cloud.githubusercontent.com/assets/366275/6629114/b2fc6d5c-c8c8-11e4-8177-f503a08fe5fb.gif)

You can take a look how it was implemented to have an idea how to make it available for DrupalConsole.

**Comment by jmolivas** [comment]
Talking about logging, we can probably also take advantage of [webprofiler](https://github.com/lussoluca/webprofiler) 

This how this module works:

![console-webprofiler](https://cloud.githubusercontent.com/assets/366275/6629326/5b2622ec-c8ca-11e4-8875-b01aa120216d.gif)

**Comment by mikeyp** [comment]
Very cool, although the logging from HttpServer looks like the normal output from the PHP built in web server, which can only be overridden if you pipe stderr to dev/null (I checked the PHP sources on this, and sadly it's not configurable).

**Comment by enzolutions** [comment]
@mikeyp do you have any progress for this feature maybe somethign WIP the rest of the Drupal Console  team could complete?

**Comment by jmolivas** [comment]
Command `server` was added.

Usage:
```
$ drupal server
```
This is how it looks:
![drupal-server](https://cloud.githubusercontent.com/assets/366275/11832508/b9e61110-a36d-11e5-9fc5-cea3a0e77c01.png)

More info at: https://hechoendrupal.gitbooks.io/drupal-console/content/en/commands/server.html
