### ISSUE TITLE
[generate:plugin:block] Allow the definition of the form structure via inline

### ISSUE THREAD

**Issue by dmouse** [hechoendrupal/DrupalConsole#477]
If you want to use the inline way,  there is no way of defining the form structure via arguments.

Proposed:
pass the definition using the "inputs" argument

--fields="name:Field Name, machine:field_name, ..." --fields="name:Second Field, nachine:second_field, ..."

**Comment by hugronaphor** [comment]
I like the idea!
You specified [generate:plugin:block], is the same implemented already for other component?

**Comment by hugronaphor** [comment]
As I see in console documentation, this is not supported by default.
Should we write our own helper parser for proposed structure?
Also, I think it's better to have a structure like:
--field_1="name:Field Name, machine:field_name, ..."  --field_2="name:Field Name, machine:field_name, ..."

**Comment by jmolivas** [comment]
+1 for --fields="..." and have multiple times

I may take a look to other project to see what are they doing on this case

**Comment by hugronaphor** [comment]
An example would be: https://github.com/laracasts/Laravel-5-Generators-Extended/blob/master/src/Migrations/SchemaParser.php used for Laravel

**Comment by enzolutions** [comment]
This could be to complicated, maybe is easier generate interactive using the new option available in 0.7.15 --generate-chain and use the yaml returned to be executed with a chain, IMHO in that way will be more practical and re-usable.

**Comment by jmolivas** [comment]
I like to have this feature. I will try to spend some time investigating if doable. 

As @enzolutions adding the values via a chain YAML is already supported.

**Comment by jmolivas** [comment]
@dmouse @hugronaphor @enzolutions This is done few releases back, closing issue

How to do example:
```
drupal generate:form:config  --module="example" --class="DefaultForm" 
--form-id="default_form" 
--inputs="name:my_text type:textfield label:My Text options: description: maxlength:64 size:64 default_value: weight:0 fieldset:" 
--inputs="name:my_number type:number label:My Number options: description: maxlength: size: default_value: weight:0 fieldset:" 
--inputs="name:my_textarea type:textarea label:My textarea options: description: maxlength: size: default_value: weight:0 fieldset:" 
--routing --menu_link_gen --menu_link_title="DefaultForm" 
--menu_parent="system.admin_config_system" 
--menu_link_desc="A description for the menu entry" --no-interaction
```
