### ISSUE TITLE
[console] Use annotations in Commands

### ISSUE THREAD

**Issue by dmouse** [hechoendrupal/DrupalConsole#478]
The Drupal commands interact with more stuffs that the commands in Symfony, in Drupal, one command can be have many dependencies with other modules or themes or any other scope in your installation.

This approach is to use Annotations to provide metadata on each command to specify dependencies or check another variables in Drupal or any other stuff that interacts with the console.

For example:
```php
/**
 * @DrupalCommand (
 *      dependencies = {
 *          "simpletest"
 *      },
 * )
 */
class TestDebugCommand extends ContainerAwareCommand { ... }
```

**Comment by enzolutions** [comment]
+1

**Comment by jmolivas** [comment]
Are we still trying to add this @dmouse ? any advantage vs the current command discovery method ?

**Comment by darol100** [comment]
@dmouse , Can you explain why you added the tag "core-issue"? I'm just curios.

**Comment by darol100** [comment]
@dmouse , @jmolivas Shall we close this issue ? This is done.
