### ISSUE TITLE
[console] Add the symfony/expression-language component

### ISSUE THREAD

**Issue by lussoluca** [hechoendrupal/DrupalConsole#480]
This component is useful for extracting data from complex structures. I need this to write a command that extract data from a profile generated by the Webprofiler module. With this new command (webprofiler:query) a user can do some automatic performance analysis, i.e. do something like this (maybe in Jenkins):

* run webprofiler:benchmark on an Url
* apply a patch
* run webprofiler:benchmark on an Url
* run webprofiler:query to extract the number of executed queries to see if the patch introduce some performance regressions

**Comment by jmolivas** [comment]
@lussoluca Not sure if Console can take advantage of `symfony/expression-language` at this point.

Did you try adding to your module  instead ?

**Comment by enzolutions** [comment]
@lussoluca do you have any second though about this request?

**Comment by lussoluca** [comment]
At this point I don't know if worth to implement more data analysis directly into webprofiler/console. So at the moment I don't need expression-language anymore.

**Comment by enzolutions** [comment]
OK I am goint to close this ticket, thanks for your feedback
