### ISSUE TITLE
[generate:command] How to build a custom generator for my module?

### ISSUE THREAD

**Issue by damienmckenna** [hechoendrupal/DrupalConsole#510]
In Drush there's an API for adding custom commands to a module. How would someone do this for DrupalConsole, e.g. if they wanted to add a generator for a custom plugin?

**Comment by jmolivas** [comment]
You can try using the command generator
```
$ drupal generate:command
```
![generate-command](https://cloud.githubusercontent.com/assets/366275/6652589/e39eddb4-ca30-11e4-87e1-037f05d8d4ef.gif)

**Comment by damienmckenna** [comment]
Ok, thanks for mentioning generate:command.

I did that but the new command doesn't show up when I run "drupal", was there an API change recently that would prevent generated commands from showing?

**Comment by jmolivas** [comment]
Did you enable de module where the new command was generated ?

**Comment by damienmckenna** [comment]
The module was already enabled, and I rebuilt the cache.

The code is here:

* http://bitbucket.org/DamienMcKenna/metatag_d8

:)

**Comment by jmolivas** [comment]
@damienmckenna Your command class must end with `Command` just rename it as `GenerateTagCommand`

```
01:25 metatag (master) ✗ tree src/Command/
src/Command/
└── GenerateTagCommand.php

0 directories, 1 file
```

```
<?php

/**
 * @file
 * Contains Drupal\metatag\Command\GenerateTagCommand.
 */

namespace Drupal\metatag\Command;

use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Drupal\AppConsole\Command\ContainerAwareCommand;

/**
 * Class GenerateTag.
 *
 * @package Drupal\metatag
 */
class GenerateTagCommand extends ContainerAwareCommand {
  /**
   * {@inheritdoc}
   */
  protected function configure() {
    $this
      ->setName('metatag:generate:tag')
      ->setDescription($this->trans('command.metatag.generate.tag.description'))
      ->addArgument('name', InputArgument::OPTIONAL, $this->trans('command.metatag.generate.tag.arguments.name'))
      ->addOption('yell', NULL, InputOption::VALUE_NONE, $this->trans('command.metatag.generate.tag.options.yell'));
  }

  /**
   * {@inheritdoc}
   */
  protected function execute(InputInterface $input, OutputInterface $output) {
    $name = $input->getArgument('name');
    if ($name) {
      $text = 'Hello ' . $name;
    }
    else {
      $text = 'Hello';
    }

    $text = sprintf(
      '%s, %s: %s',
      $text,
      'I am a new generated command for the module',
      $this->getModule()
    );

    if ($input->getOption('yell')) {
      $text = strtoupper($text);
    }

    $output->writeln($text);
  }

}
```

![screen shot 2015-04-10 at 1 23 17 pm](https://cloud.githubusercontent.com/assets/366275/7096725/e5028912-df84-11e4-909b-4770ca0630c2.png)

**Comment by damienmckenna** [comment]
AHHHH! Thank you!

I added a PR for a small comment to the documentation: https://github.com/hechoendrupal/drupal-console-book/pull/38

**Comment by damienmckenna** [comment]
I've ran into a small problem with this - how do I tell the generator to load the file from my custom module instead of DrupalConsole? When my generator is trying to output the file it results in the following:

> [Twig_Error_Loader]
> Unable to find template "templates/tag.php.twig" (looked into: phar:///usr/local/bin/drupal/src/Command/../../templates).

**Comment by damienmckenna** [comment]
Basically, what should the first argument be in my custom Generator plugin's renderFile() method and where would be the best location in the module's directory to store the file?

**Comment by jmolivas** [comment]
This is happening because of this https://github.com/hechoendrupal/DrupalAppConsole/blob/master/src/Command/GeneratorCommand.php#L41

I am currently working to add the module path as discoverable path for templates.

**Comment by damienmckenna** [comment]
@jmolivas,
Thanks for the response, I'll put this part of the project on hold until you're able to iron it out.

**Comment by jmolivas** [comment]
@damienmckenna PR #580 sent and merged is at master and tagged a new release https://github.com/hechoendrupal/DrupalAppConsole/releases/tag/0.7.8. 

In order to implement on your contrib command you should:

* Add `use Drupal\AppConsole\Command\GeneratorCommand;` on you command-class.
* Make your command-class extend from `GeneratorCommand`.
* Add `use Drupal\example\Generator\MyGenerator;` where `MyGenerator` is your Generator class-name. 
* Implement `createGenerator` method this method should look like:
```
  protected function createGenerator()
  {
    return new MyGenerator();
  }
```
* Create a new `Generator` class within `Generators` namespace this class should look like this:

```
<?php

namespace Drupal\example\Generator;

use Drupal\AppConsole\Generator\Generator;

class MyGenerator extends Generator 
{
    public function generate($module, ...)
    {
        $parameters = [
          'module_name' => $module 
         ...
        ];

        $this->renderFile(
          'module/src/Directory/class-file.php.twig',
          $this->getModulePath($module) . '/src/Directory/MyCustomClass.php',
          $parameters
        );
    }
}
```

**Comment by damienmckenna** [comment]
Thanks, I'll give it a spin in the morning - the twig file was the last part!

**Comment by jmolivas** [comment]
Great, ping me if anything else is not working as expected or any doubts.

**Comment by jmolivas** [comment]
I will close this, since looks like is fixed. @damienmckenna feel free to re-open if something is missing.
