### ISSUE TITLE
[generate:entity:bundle] Add new command 

### ISSUE THREAD

**Issue by socketwench** [hechoendrupal/DrupalConsole#517]
Currently, console support generation of config and content entities, but not a bundle in the Drupal sense. You can take a config and content entity and trivially make them a bundle afterward, providing a generate command for bundles would be very useful. 

This could possibly be implemented as a question in the content entity generator, or a completely separate command that heavily leverages the config and content generators.

**Comment by Sutharsan** [comment]
Duplicate of https://github.com/hechoendrupal/DrupalConsole/issues/299
