### ISSUE TITLE
[console] Rename the github project to "DrupalConsole"

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#571]
Rename project form `DrupalAppConsole ` to `DrupalConsole`

Based on github documentation https://help.github.com/articles/renaming-a-repository/ 
> When you rename a repository, all existing information is automatically redirected to the new name.

NOTE: We also need to update the packagist definition https://packagist.org/packages/drupal/console

**Comment by damienmckenna** [comment]
Might it also be possible to set it up as its own top-level project, ala Drush? You might need to set up a team or something in order to do that.
