### ISSUE TITLE
[console] Replace DialogHelper usage with Question Helper

### ISSUE THREAD

**Issue by damienmckenna** [hechoendrupal/DrupalConsole#575]
Per the [Dialog Helper API docs](http://symfony.com/doc/current/components/console/helpers/dialoghelper.html):

> The Dialog Helper was deprecated in Symfony 2.5 and will be removed in Symfony 3.0. You should now use the [Question Helper](http://symfony.com/doc/current/components/console/helpers/questionhelper.html) instead, which is simpler to use.

i.e. ask(), askAndValidate() etc should be replaced with the equivalent Question Helper API instead.

**Comment by jmolivas** [comment]
Glad you bring this issue. I will review and create a list of what is needed to change.
