### ISSUE TITLE
[standard] Documentation > How to set up a dev environement

### ISSUE THREAD

**Issue by kgaut** [hechoendrupal/DrupalConsole#607]
In order to allow more people to work on this project, It would be great to add documentation about how to set up a dev environment for Drupal Console.
 * Forking the project
 * How to use the fork locally.
 * and so on... 

There's a page on the book, empty : http://hechoendrupal.gitbooks.io/drupal-console/content/how-to-contribute/create-a-new-command.html

**Comment by jmolivas** [comment]
##### Setup dev environment links are at:
* http://hechoendrupal.gitbooks.io/drupal-console/content/how-to-contribute/project-requirements.html
* http://hechoendrupal.gitbooks.io/drupal-console/content/how-to-contribute/getting-the-project.html
* http://hechoendrupal.gitbooks.io/drupal-console/content/how-to-contribute/running-the-project.html
* I just merged a PR related to `Create a new Command` page  
http://hechoendrupal.gitbooks.io/drupal-console/content/how-to-contribute/create-a-new-command.html

##### I will try to draft the doc pages taking ideas from links:
* Symfony docs  
http://symfony.com/doc/current/components/console/index.html
* Cookbook  
http://symfony.com/doc/current/cookbook/console/index.html
* Symfony2 Console component, by example  
http://gnugat.github.io/2014/04/09/sf2-console-component-by-example.html

**Comment by jmolivas** [comment]
@kgaut  Since documentation is already on the book. I will close this issue, feel free to re-open not something still missing.
