### ISSUE TITLE
[console] Use SSL for site and install docs

### ISSUE THREAD

**Issue by kostajh** [hechoendrupal/DrupalConsole#613]
Hello,

I'm interested to use this project. But the install instructions make me hesitate:

` curl -LSs http://drupalconsole.com/installer | php`

How do you feel about serving `drupalconsole.com` over SSL and updating the install docs to use SSL exclusively?

**Comment by jmolivas** [comment]
@kostajh We are working on a new version for the site, and move the hosting to Pantheon then serve the site over SSL, our goal is have it ready for DrupalConLA. 

In the meantime you can download the `console.phar` from the releases page:
`https://github.com/hechoendrupal/DrupalConsole/releases`
Once downloaded you may move to a global accesible path using:
`mv console.phar /usr/local/bin/drupal`

**Comment by kostajh** [comment]
thanks @jmolivas!

**Comment by jmolivas** [comment]
@kostajh: We finally have the draft version of the website and we are currently using a PaaS. We have what we need to setup this and we will take of this task very soon.

**Comment by jmolivas** [comment]
@kostajh: Fixed 

You can now use `https`:
https://github.com/hechoendrupal/DrupalConsole#installing-drupal-console

Documentation updated as well.

**Comment by jmolivas** [comment]
Closing this since already fixed.
