### ISSUE TITLE
[rest:enable] doesn't work

### ISSUE THREAD

**Issue by enzolutions** [hechoendrupal/DrupalConsole#616]
Right now is not possible to enable a rest resource using command *rest:enable* the following error interrupt the operation.

```
PHP Fatal error:  Call to protected method Drupal\Core\Authentication\AuthenticationManager::getSortedProviders() from context 'Drupal\AppConsole\Command\ContainerAwareCommand' in /Users/enzo/www/DrupalConsole/src/Command/ContainerAwareCommand.php on line 244
```

A comment in issue https://www.drupal.org/node/2456303#comment-9928318 where provided to request support. Maybe this command must be disable until that problem is resolved.

**Comment by martinfrances107** [comment]
I am having the same issue...

just wanted to add, the work around.

The UI still works, so visit admin/config/services/rest

**Comment by enzolutions** [comment]
Hi @martinfrances107 correct Rest UI is working

**Comment by omero** [comment]
the issue mentioned by @enzolutions has been moved to https://www.drupal.org/node/2490228 wait and see what happens :/

**Comment by enzolutions** [comment]
Fixed for beta 14 with commit https://github.com/hechoendrupal/DrupalConsole/pull/775/files#diff-9148758e43f02f0813116d214384ccaeR252 this will be release in 0.8.1 release

**Comment by jmolivas** [comment]
Do we have a PR or need to add a new one to fix this @enzolutions ?

**Comment by jmolivas** [comment]
My bad I did not see the link was the related PR https://github.com/hechoendrupal/DrupalConsole/pull/775
