### ISSUE TITLE
[docs] Fix code-affecting typos

### ISSUE THREAD

**Issue by LowellMontgomery** [hechoendrupal/DrupalConsole#625]
While editing the documentation, I came upon an option that had a typo/misspelling. (autorization => authorization). I've corrected this in my latest documentation cleanup branch and in a new branch I've created in my new fork of this. In this new branch, I will also do a quick cleanup of any English grammar/typos, etc, in more trivial locations (.md files, etc)

**Comment by jmolivas** [comment]
Awesome thanks, I am currently reviewing your PR https://github.com/hechoendrupal/DrupalConsole/pull/626
