### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by sajalsoni** [hechoendrupal/DrupalConsole#632]
While running simple drupal command, it gives the FATAL Error.
$ drupal 
PHP Fatal error:  Call to protected method Drupal\Core\DrupalKernel::preHandle() from context 'Drupal\AppConsole\Command\Helper\KernelHelper' in phar:///usr/local/bin/drupal/src/Command/Helper/KernelHelper.php on line 72
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/console:3
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/drupal/bin/console.php:69
PHP   5. Drupal\AppConsole\Console\Application->doRun() phar:///usr/local/bin/drupal/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Drupal\AppConsole\Console\Application->bootstrap() phar:///usr/local/bin/drupal/src/Console/Application.php:114
PHP   7. Drupal\AppConsole\Command\Helper\KernelHelper->bootKernel() phar:///usr/local/bin/drupal/src/Console/Application.php:241

**Comment by jmolivas** [comment]
Which version of `drupal 8` and `console` are you using @sajalsoni ?

**Comment by sajalsoni** [comment]
Drupal => 8
Drupal Console => Drupal Console version 0.7.12

**Comment by jmolivas** [comment]
I just cloned D8 latest dev and execute console 0.7.12 and it works fine as you can see it here:
![drupal-dev-console-0-7-12-site-status](https://cloud.githubusercontent.com/assets/366275/7871167/0aa5e3a6-0543-11e5-8655-11bfd647030f.png)

**Comment by sajalsoni** [comment]
@jmolivas 

Ok working fine now with "drupal-8.0.0-beta11" version. So it was an issue with "dev" version. Anyways, thanks for the insight.

**Comment by jmolivas** [comment]
Glad to know it works, we are currently only supporting Beta releases.

**Comment by sajalsoni** [comment]
@jmolivas 

Hi, although this issue is closed. I've a query. Can you please clear the different between "generate:entity:config Vs generate:entity:content" as they both generate almost similar files.

When I should create "Config Entity" and same with "Content Entity"? Thanks in advance.

**Comment by jmolivas** [comment]
@sajalsoni:

Some differences:
* Configurable entities can be exported using the new CMI system.
* Configurable entities don't have fields due to the way they are stored in the DB

Drupal 8 introduces the concept of configuration entities (or configurables) that leverage the entity system's CRUD and pluggable storage functionality. The main difference between configuration entities and Drupal 7-style content entities is that configuration entities use the configuration system for storage, rather than the database. They differ from plain configuration in that they are typically user-created, and often need to fire and respond to hooks. Examples of potential configuration entities include:

Content types
Views
Taxonomy vocabularies
Contact forms
Image styles
etc.
more info: https://www.drupal.org/node/1818734

Configuration entities
https://www.drupal.org/node/2143501

Content entities
https://www.drupal.org/node/2143503

**Comment by sajalsoni** [comment]
@jmolivas Thanks for the detailed information. I appreciate it.

**Comment by sajalsoni** [comment]
Hi @jmolivas 

I created a module using "drupal generate:authentication:provider". But when I try to enable it from the admin side, it gives me the following error.

Drupal\Component\Serialization\Exception\InvalidDataTypeException: Unable to parse at line 1 (near " authentication.autocustomauthprovider:"). in Drupal\Component\Serialization\Yaml::decode() (line 44 of core/lib/Drupal/Component/Serialization/Yaml.php).

Drupal\Component\Serialization\Yaml::decode('  authentication.autocustomauthprovider:
    class: Drupal\autocustomauthprovider\Authentication\Provider\DefaultAuthenticationProvider
    arguments: ["@config.factory", "@entity.manager"]
    tags:
      - { name: authentication_provider, priority: 100 }

')
Drupal\Core\DependencyInjection\YamlFileLoader->loadFile('modules/custom/autocustomauthprovider/autocustomauthprovider.services.yml')
Drupal\Core\DependencyInjection\YamlFileLoader->load('modules/custom/autocustomauthprovider/autocustomauthprovider.services.yml')
Drupal\Core\DrupalKernel->compileContainer()
Drupal\Core\DrupalKernel->initializeContainer(1)
Drupal\Core\DrupalKernel->updateModules(Array, Array)
Drupal\Core\Extension\ModuleInstaller->updateKernel(Array)
Drupal\Core\Extension\ModuleInstaller->install(Array, 1)
Drupal\Core\DependencyInjection\Container\prod\Drupal_Core_Extension_ModuleInstaller_Proxy->install(Array)
Drupal\system\Form\ModulesListForm->submitForm(Array, Object)
call_user_func_array(Array, Array)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object)
Drupal\Core\Form\FormBuilder->processForm('system_modules', Array, Object)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1)
Drupal\Core\DependencyInjection\Container\prod\Symfony_Component_HttpKernel_HttpKernel_Proxy->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1)
Drupal\Core\DependencyInjection\Container\prod\Drupal_Core_StackMiddleware_Session_Proxy->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1)
Drupal\Core\DependencyInjection\Container\prod\Drupal_Core_StackMiddleware_KernelPreHandle_Proxy->handle(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1)
Stack\StackedHttpKernel->handle(Object, 1, 1)
Drupal\Core\DrupalKernel->handle(Object)

Thanks in advance.

**Comment by jmolivas** [comment]
May you share used versions, You may now this by running

`drupal --version `

`drupal site:status`

**Comment by sajalsoni** [comment]
Hi @jmolivas 

[sajal@aum219 drupal8-latest]$ drupal --version
Drupal Console version 0.7.12
[sajal@aum219 drupal8-latest]$ drupal site:status
 System Info                                                                                    
 Drupal                       8.0.0-beta11                                                      
 Access to update.php         Protected                                                         
 Configuration files          Protected                                                         
 Cron maintenance tasks       Last run 5 min 6 sec ago                                          
 Database system              MySQL, MariaDB, Percona Server, or equivalent                     
 Database system version      5.5.42-MariaDB                                                    
 Database updates             Up to date                                                        
 File system                  Writable (<em>public</em> download method)                        
 GD library                   2.1.1                                                             
 GD library PNG support       2.1.1                                                             
 Image toolkit                gd                                                                
 Node Access Permissions      Disabled                                                          
 PHP                          5.5.25 (<a href="/admin/reports/status/php">more information</a>) 
 PHP DOMDocument class        Enabled                                                           
 PHP extensions               Enabled                                                           
 PHP memory limit             128M                                                              
 PHP open_basedir restriction Disabled                                                          
 Search index progress        100% (0 remaining)                                                
 Trusted Host Settings        Not enabled                                                       
 Twig C extension             Not available                                                     
 Unicode library              PHP Mbstring Extension                                            
 Update notifications         Not enabled                                                       
 Upload progress              Not enabled                                                       
 Web server                                                                                     
 cURL                         Enabled                                                           
 Database connection                                                                            
 Driver                       mysql                                                             
 Host                         192.168.100.216                                                   
 Database connection          cms_drupal8_latest                                                
 Port                         3306                                                              
 Username                     cms                                                               
 Password                     cms                                                               
 Connection                   mysql//cms:cms@192.168.100.216:3306/cms_drupal8_latest            
 Themes                                                                                         
 theme_default                bartik                                                            
 theme_admin                  seven                                                             
 Directories                                                                                    
 Site root directory          /home/sajal/web/drupal8-latest/                                   
 Site temporary directory     /tmp                                                              
 Default theme directory      /core/themes/bartik                                               
 Admin theme directory        /core/themes/seven                                                

 The command was executed succesfully! 

[sajal@aum219 drupal8-latest]$

**Comment by sajalsoni** [comment]
Hi @jmolivas 

I was able to solve that finally. I found that I need to provide the "provider_id" in the services.yml.

services:
  autocustomauthprovider.authentication.defaultauth:
    class: Drupal\autocustomauthprovider\Authentication\Provider\DefaultAuthenticationProvider
    arguments: ["@config.factory", "@entity.manager"]
    tags:
      - { name: authentication_provider, provider_id: 'autocustomauthprovider', priority: 100 }
