### ISSUE TITLE
[chain] Is not validating empty file option 

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#636]
![screen shot 2015-05-28 at 8 35 11 pm](https://cloud.githubusercontent.com/assets/366275/7876014/8e5749ca-0579-11e5-9abb-8309d9f70242.png)

When no option `--file=path/to/your-file.yml` entered the error message

> You must provide a valid file path and name.

Must be shown

**Comment by jmolivas** [comment]
This is how the fix looks like when no option entered `--file=path/to/your-file.yml`
![screen shot 2015-05-29 at 1 39 11 pm](https://cloud.githubusercontent.com/assets/366275/7892292/1bc3ee42-0608-11e5-9688-224725569508.png)

**Comment by Jaesin** [comment]
I've tested  with `php bin/console.php chain` and received the "You must provide a valid file path and name." error message.
