### ISSUE TITLE
[chain] Generate chain command structure.

### ISSUE THREAD

**Issue by Jaesin** [hechoendrupal/DrupalConsole#640]
The idea here is to be able to use interactive mode to generate a chain command entry. 

Maybe something like `console generate:plugin:block --generate-chain-entry` that would print out the chain command entry. 

This is useful when using a chain file to document the structure of your module. You can add the `my_module.chain.yml`file to your drupal module.

**Comment by jmolivas** [comment]
Love the idea @Jaesin, how about `generate:chain generate:plugin:block`make more sense to me have a single chain generator and pass the module(s) as argument.

**Comment by Jaesin** [comment]
The idea behind using a flag is that the command would also execute at the same time unless you type "no" on the confirmation step. You may already have custom code in your module but still want to generate the chain command.

That may just be semantics though.

**Comment by enzolutions** [comment]
I had the same idea as @Jaesin long time ago I have the same feeling about that extra parameter would be great

**Comment by enzolutions** [comment]
That option was included in PR https://github.com/hechoendrupal/DrupalConsole/pull/729 and will be next release 0.7.15
