### ISSUE TITLE
[generate:plugin:rulesaction] Needs changes

### ISSUE THREAD

**Issue by sajalsoni** [hechoendrupal/DrupalConsole#649]
@jmolivas 

This command generates the custom Action based on RuleActionBase namespace. But I think in the latest version of Drupal, it doesn't exist anymore?

Instead of "RuleActionBase", we could use "ActionBase".  Also we need to create *.action.*.yml file to make sure our custom action is listed in the back-end.

Modified Code:

===modules/custom/autocustomrulesection/src/Plugin/Action/CustomAction.php===
```
<?php
namespace Drupal\autocustomrulesection\Plugin\Action;
use Drupal\Core\Action\ActionBase;
use Drupal\Core\Session\AccountInterface;

class CustomAction extends ActionBase {
  public function execute($account = NULL) {
    // Insert code here.
  }
  
  public function access($object, AccountInterface $account = NULL, $return_as_object = FALSE) {
    /** @var \Drupal\user\UserInterface $object */
    $access = $object->status->access('edit', $account, TRUE)
      ->andIf($object->access('update', $account, TRUE));

    return $return_as_object ? $access : $access->isAllowed();
  }
}
```

===modules/custom/autocustomrulesection/config/install/system.action.autocustomrulesection_custom_action_action.yml===
```
id: autocustomrulesection_custom_action_action
label: 'Custom Block the selected user(s)'
status: true
langcode: en
type: user
plugin: autocustomrulesection_custom_action_action
dependencies:
  module:
    - user
```
Please have your thoughts!

**Comment by jmolivas** [comment]
@sajalsoni Thanks for the info, let me know if you want to take care of sending a PR I can help you to make that happen.

**Comment by sajalsoni** [comment]
@jmolivas Yes sure, I would like to work on this. How should I proceed?

**Comment by jmolivas** [comment]
@sajalsoni You will need to: 

* Have this [Project requirements](http://hechoendrupal.gitbooks.io/drupal-console/content/contribute_to_drupal_console/project-requirements.html)
* [Get the project](http://hechoendrupal.gitbooks.io/drupal-console/content/contribute_to_drupal_console/getting-the-project.html) on your local machine
* Make sure you have it [running the project](http://hechoendrupal.gitbooks.io/drupal-console/content/contribute_to_drupal_console/running-the-project.html) on your local machine.

Fee free to ping me at the [Gitter chat room](https://gitter.im/hechoendrupal/DrupalConsole)

And I can help you with the changes and tell you how to test them.
