### ISSUE TITLE
[generate:entity:*] Generated entity links should point to paths, not routes

### ISSUE THREAD

**Issue by Crell** [hechoendrupal/DrupalConsole#663]
A recent core change requires that the links array in the Entity annotation be paths, NOT route names.  The current code is still generating an annotation with route names, which causes mysterious failures in some other code, such as devel. :smile: 

Very soon the routes themselves will not need to be generated as they will be automatic based on the annotation.  For right now, the path just needs to be double-listed.

**Comment by jmolivas** [comment]
Thanks for the notice @Crell, do you have a link to see what we need to change?

**Comment by Crell** [comment]
Here's the relevant change record: https://www.drupal.org/node/2382937

**Comment by heilop** [comment]
I want to work in this issue.

**Comment by jmolivas** [comment]
Awesome thanks @heilop please take your time to read this documentation 
http://hechoendrupal.gitbooks.io/drupal-console/content/contributing/new-features.html

And then try to complete the setup, and fork/clone and remote upstream and fee free to ping me at 
https://gitter.im/hechoendrupal/DrupalConsole

**Comment by Sutharsan** [comment]
It looks like this is already fixed in e03a5240.

**Comment by jmolivas** [comment]
This was fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/702
