### ISSUE TITLE
Ask for how many fields in generate:form:config ?

### ISSUE THREAD

**Issue by darol100** [hechoendrupal/DrupalConsole#664]
### Problem/Motivation
If you are trying to generate some fields, by default `generate:form:config` would allow you to created 3 field, but what if I want more or less?

### Solution
I think we should ask after `Do you want to generate a form structure [yes]? `  we should ask **How many fields do you want to generate [1]?**

What you guys think about this feature?

**Comment by jmolivas** [comment]
@darol100 There is no limit on the fields you can add, I did an example adding 4 fields
![add-form-field](https://cloud.githubusercontent.com/assets/366275/8100987/83308f0e-0fc7-11e5-9c46-05b2b3526bc3.png)

**Comment by jmolivas** [comment]
This is another example adding just one field
![add-form-one-field](https://cloud.githubusercontent.com/assets/366275/8101219/e0099e6c-0fc9-11e5-9b1f-e718ce3d1216.png)

**Comment by darol100** [comment]
OK, Closing this issues then. Thank you for your support.
