### ISSUE TITLE
Provide composer instructions instead/along side of phar instructions

### ISSUE THREAD

**Issue by joshuataylor** [hechoendrupal/DrupalConsole#665]
It's what drush does, and allows easier updating.

**Comment by jmolivas** [comment]
We recommend using the installer and have console as executable but you can review other installing instructions from gitbook:
* Composer http://hechoendrupal.gitbooks.io/drupal-console/content/installing_drupal_console/using-composer.html 
* Downloading the phar file http://hechoendrupal.gitbooks.io/drupal-console/content/installing_drupal_console/download-phar-file.html

Do you recommend to add those to the readme file @joshuataylor?

**Comment by joshuataylor** [comment]
Hi @jmolivas - didn't see that it was in the docs, yes I believe adding it to the README could be great for people like me who don't RTFM (it's really easy to add something to composer, but some people don't know the "composer global require" dance).

**Comment by jmolivas** [comment]
We had the composer instructions at the beginning, but we decided to remove since wanted to promote the installer, at this point I believe we can add composer + download phar instructions.
