### ISSUE TITLE
[generate:controller] Error while generating the routing information

### ISSUE THREAD

**Issue by edutrul** [hechoendrupal/DrupalConsole#669]
I had already a module working with:
anexus_custom.modal:
  path: '/anexus/modal'
  defaults: 
    _controller: '\Drupal\anexus_custom\Controller\AnexusCustomController::modal'
    _title: Modal
  requirements: 
    _permission: 'access content'

That's it!

then execute $ drupal generate:controller  (module: anexus_custom)
next next 
![screenshot at jun 11 10-35-49](https://cloud.githubusercontent.com/assets/1582129/8111146/b3e7778a-1025-11e5-84cd-f04f78bc53e8.png)

and got the error: 

![screenshot at jun 11 10-28-49](https://cloud.githubusercontent.com/assets/1582129/8111150/c1dc0162-1025-11e5-8a0e-07f7305564e1.png)

and that's what happenned:
![screenshot at jun 11 10-37-06](https://cloud.githubusercontent.com/assets/1582129/8111158/d9c1d9aa-1025-11e5-9c9f-668fd03d03b8.png)

So what I did, was to fix it manually

as you can see it just needed to create a new space, tried in version Drupal Console version 0.7.12 in drupal-8.0.0-beta11$

**Comment by jmolivas** [comment]
Seems like a new line must be added on the first line at the following twig files:
- [ ] templates/module/routing-controller.yml.twig
- [ ] templates/module/routing-entity-content.yml.twig
- [ ] templates/module/routing-entity.yml
- [ ] templates/module/routing-form.yml

**Comment by jmolivas** [comment]
@edutrul let me know if you want to take care of this issue.

**Comment by edutrul** [comment]
Yes please I'd love to! thanks for considering me!

**Comment by jmolivas** [comment]
Feel free to ping me if any help is needed @edutrul

**Comment by jmolivas** [comment]
I tested this and it works properly. Thanks @edutrul
