### ISSUE TITLE
[docs] Improve documentation and translations.

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#675]

**Comment by danielrose28** [comment]
Is this a duplicate issue? I see that there is also issue #789, which seems to be similar. Or maybe that one is the duplicate?

**Comment by jmolivas** [comment]
Not a duplicated, but I do not see the need to have this issue open because: 
- We maintain the docs in a separated project https://github.com/hechoendrupal/drupal-console-book  
- Improving translations have it's own issue https://github.com/hechoendrupal/DrupalConsole/issues/942

**Comment by danielrose28** [comment]
Makes sense to me. :+1:

**Comment by jmolivas** [comment]
closing this ;), thanks for reporting and commenting @danielrose28
