### ISSUE TITLE
[console] Dummy content generator

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#677]
Investigate best alternative to generate content 

Similar projects ands links for inspiration 
https://github.com/fzaninotto/Faker 
https://github.com/nelmio/alice 
https://github.com/larowlan/default_content 
http://laravel.com/docs/5.0/migrations#database-seeding

**Comment by jmolivas** [comment]
Related PR https://github.com/hechoendrupal/DrupalConsole/pull/1395

This WIP PR contains a new `generate:content` command.

**Comment by darol100** [comment]
This issue is already been solve at  #1395
