### ISSUE TITLE
[console] Autocomplete commands

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#679]
Provides automatic (tab) completion:

Project to provide, auto-complete for Symfony Console applications:
https://github.com/stecman/symfony-console-completion

**Comment by darol100** [comment]
I think this will be an great feature.

**Comment by jmolivas** [comment]
And solving this will benefit both projects DrupalConsole & Terra-App

**Comment by darol100** [comment]
@jmolivas , Do we still have some work done in order to finished this issue or should we close it ?

**Comment by jmolivas** [comment]
@omero did you know the status of this issue?. Is autocomplete fully functional?

**Comment by jmolivas** [comment]
Closing this since no reply by @omero, feel free to re-open if any pending work.
