### ISSUE TITLE
[console] Setting guidelines for contributing

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#680]
I like how d.o. provides a template to create an issue.

Github provides similar functionality by adding a new file, named `CONTRIBUTING` or `CONTRIBUTING.md` to the root directory of your repository, more info:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

Taking as example the issues @darol100 added, I took the template from d.o. and wrote this draft

### Problem/Motivation
A brief statement describing why the issue was filed.

**Details to include:**
- Why are we doing this? Above all, a summary should explain why a change is needed, in a few short sentences.

### How to reproduce
Include steps related how to reproduce. 

**Details to include:**
- Drupal version. 
- Console version.
- Steps to reproduce
- Include screenshots when needed.

### Solution
A brief description of the proposed fix.

**Details to include:**
- A short summary of the approach proposed or used in the PR.
- Approaches that have been tried and ruled out.
- Links to relevant API documentation or other resources.
- Known workarounds.

**Comment by jmolivas** [comment]
A new link `Please review the guidelines for contributing to this repository.` appear now when adding a new issue pointing to `CONTRIBUTING.md` file:
https://github.com/hechoendrupal/DrupalConsole/blob/master/CONTRIBUTING.md

This is how it looks like:
![screen shot 2015-06-11 at 11 41 56 pm](https://cloud.githubusercontent.com/assets/366275/8124796/0f7ec2e2-1094-11e5-84d4-6c6b78336406.png)

**Comment by jmolivas** [comment]
We have a page on the book related to [Create an issue](http://hechoendrupal.gitbooks.io/drupal-console/content/contribute_to_drupal_console/create-an-issue.html)

I am planning to add the tittle section on the `CONTRIBUTING.md` file

### Issue title standards

The issue title should comply with the following structure:

[ *ISSUE-GROUP* ] - Short description

The *ISSUE-GROUP* should be one of:

* `command:name`
* `helper`
* `standard`
* `template`
* `translation`
* `RFC`

**Comment by darol100** [comment]
@jmolivas , Maybe allowing any user to set labels, but I do not think this is possible in Github. https://help.github.com/articles/permission-levels-for-an-organization-repository/. 

I have a few suggestion/things to consider for the warning message.

Do you want user to use the issue queue for support as well, or just only issues and new features ? Some projects like bootstrap, only use the issue queue for features/bugs.  If this the route that you want to go we can have a disclaimer in there that said.

"**Do not open issue for support question, only features and bugs.** Please visit the [Module development] (https://www.drupal.org/forum/4) support forum or [Drupal StackExchange] (https://www.drupal.org/node/add/project-issue/bootstrap). These are amazing resources for asking questions, learning new techniques and overall general support."


Another thing, that I like from the [bootstrap issue warning message](https://www.drupal.org/node/add/project-issue/bootstrap) is that they provide you places where you can get some documentation. I think we can link the Git Book in that warning message. We can said something that said

### Documentation

There's been some amazing Drupal Community work done around DrupalConsole. Many of your questions can be answered in our [DrupalConsole Book](https://www.gitbook.com/book/hechoendrupal/drupal-console/details).

If you find documentation in this DrupalConsole Book inaccurate or missing, you can created a new issue at [DrupalConsole Book] (https://github.com/hechoendrupal/drupal-console-book) repository.


Assuming we want to add all these changes this is going to be the final results.

> ### Guidelines
> Please review the [guidelines for contributing] (https://github.com/hechoendrupal/DrupalConsole/blob/master/CONTRIBUTING.md) to this repository.
>
> ### Support
>"**Do not open issue for support question, only features and bugs.** Please visit the [Module development] (https://www.drupal.org/forum/4) support forum or [Drupal StackExchange] (https://www.drupal.org/node/add/project-issue/bootstrap). These are amazing resources for asking questions, learning new techniques and overall general support."
>
>### Documentation

>There's been some amazing Drupal Community work done around DrupalConsole. Many of your questions can be answered in our [DrupalConsole Book](https://www.gitbook.com/book/hechoendrupal/drupal-console/details).

>If you find documentation in this DrupalConsole Book inaccurate or missing, you can created a new issue at [DrupalConsole Book] (https://github.com/hechoendrupal/drupal-console-book) repository.

**Comment by jmolivas** [comment]
Great idea about Support and Documentation

We can direct support to gitter chat room
https://gitter.im/hechoendrupal/DrupalConsole 

I like the bootstrap warning message about the **Minimum Requirements**

Related to the labels, need to confirm but what I recall is github does not allow users to create labels.

**Comment by LowellMontgomery** [comment]
> Re: The ISSUE-GROUP should be one of:
* command:name
* helper
* standard
* template
* translation
* RFC

I think we should have some kind of explanation of the "ISSUE-GROUP" types. And, if I even understand the intended meaning of them all, myself, I think we should have at least another category+ (?)

Just wanted to point out that the notes for new issue creation will certainly be ignored by those who know the system, but for those who do not, a bit more explanation could be useful if we want to see the same kind of group-assignment from everyone.

**Comment by jmolivas** [comment]
@darol100  I did some re-work based on your ideas:

### Minimum Requirements
This project requires Drupal 8 Beta11.

### Support
"**Do not open issue for support question, only features and bugs.** For question please visit our [ DrupalConsole Gitter room] (https://gitter.im/hechoendrupal/DrupalConsole).

### Documentation
There's been some amazing Drupal Community work done around DrupalConsole. Many of your questions can be answered in our [DrupalConsole Book](https://www.gitbook.com/book/hechoendrupal/drupal-console/details).

If you find documentation in this DrupalConsole Book inaccurate or missing, you can created a new issue at [DrupalConsole Book] (https://github.com/hechoendrupal/drupal-console-book) repository.

**Comment by jmolivas** [comment]
@LowellMontgomery I totally agree with adding more categories any recommendations. I already added `docs` and `test` I did when adding the [CONTRIBUTING.md](https://github.com/hechoendrupal/DrupalConsole/blob/master/CONTRIBUTING.md) file.

Adding a clear meaning for the groups sounds like a great idea. Also we can change the name from `group` to `category` or other if that make more sense.

**Comment by jmolivas** [comment]
@darol100 Related to Drupal StackExchange maybe promote people to ask question there and tagging as console could be a good idea.

**Comment by jmolivas** [comment]
Closing this, 
Thanks:
- @darol100 for the comments and improvements.
- @LowellMontgomery feel free to add a new issue to propose a new set of **ISSUE-GROUPS**
- @enzolutions for adding the TOC and rearrange the content on the template.
