### ISSUE TITLE
[standard] Source code should not contain TODO comments

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#693]
### Problem/Motivation

**[in src/Generator/Generator.php, line 99](https://github.com/hechoendrupal/DrupalConsole/blob/cec95e2505ecf5055c3c5c09a2f352c4caf17734/src/Generator/Generator.php#L99)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```php

    public function getModulePath($module_name)
    {
        if (!$this->module_path) {
          /**
           * @todo Remove DrupalExtensionDiscovery subclass once
           * https://www.drupal.org/node/2503927 is fixed.
           */
          $discovery = new DrupalExtensionDiscovery(\Drupal::root());
          $discovery->reset();
          $result = $discovery->scan('module');
```

### How to reproduce
Review analysis result URL:
https://insight.sensiolabs.com/projects/d0f089ff-a6e9-4ba4-b353-cb68173c7d90/analyses/62

### Solution
Complete implementation once this core issue is fixed:
- https://www.drupal.org/node/2503927

Related to https://github.com/hechoendrupal/DrupalConsole/issues/691

**Comment by darol100** [comment]
I'm closing this issue since this does not longer applies.
