### ISSUE TITLE
Provide scaffolding files for Views' handler plugins.

### ISSUE THREAD

**Issue by mikeker** [hechoendrupal/DrupalConsole#695]
Would love to have scaffolding for building Views' plugins. This would be useful to contrib developers that define new entities and want to enable Views integration.

**Comment by jmolivas** [comment]
Sounds really useful @mikeker, can you please provide links to the documentation in order to take a look at the code to implement on the generators.

**Comment by mikeker** [comment]
@jmolivas; Will do... Just as soon as I figure it out myself!  :)

As a starting point, the Views plugin base class is located here: core/modules/views/src/Plugin/views/PluginBase.php. The handler base class is here: core/modules/views/src/Plugin/views/HandlerBase.php. And the field plugin base class, for example, is here: core/modules/views/src/Plugin/views/field/FieldPluginBase.php.

I'm going through the process of building one right now so I'll try to track what's needed for a minimum viable plugin. There will need to be somewhat different code generated for field, filter, sort, etc. plugins.

More to come...

**Comment by jmolivas** [comment]
Sound @mikeker  awesome fee free to keep commenting on this issue and ask any question at our support gitter room: https://gitter.im/hechoendrupal/DrupalConsole

**Comment by jmolivas** [comment]
Also make sure you take your time to read the documentation:
http://hechoendrupal.gitbooks.io/drupal-console/content/contributing/new-features.html

**Comment by enzolutions** [comment]
@mikeker Do you think we resolve this request with command generate:plugin:views:field ?

**Comment by enzolutions** [comment]
@mikeker could you confirm if command generate:plugin:views:field resolve your request?

**Comment by mikeker** [comment]
@enzolutions, Sorry, I didn't see the notification of your earlier comment. `generate:plugin:views:field` gets us part of the way there. That might be a good starting point. I'll try to look into this in the next week.

**Comment by enzolutions** [comment]
@mikeker perfect, check and let me know if maybe the command require an enhancement or a siblling command.

**Comment by darol100** [comment]
@mikeker Any new update on this issue ?

**Comment by enzolutions** [comment]
@mikeker sorry disturbing could you confirm is we can close this issue?

**Comment by mikeker** [comment]
I'm sorry, I haven't had the time to look into this. The field plugin will get us most of the way there. Closing this issue for now and will reopen if I have more information.

Sorry about the delays!
