### ISSUE TITLE
[generate:form:config] url field type not allowed

### ISSUE THREAD

**Issue by cweagans** [hechoendrupal/DrupalConsole#697]
When generating a form, I should be able to specify the `url` field type. It's supported by core (added by https://www.drupal.org/node/1174630).

**Comment by jmolivas** [comment]
Yes @cweagans liked the idea, I decided to working on generate field types based on the Drupal installation installed modules core+contrib to generated only valid field types, this is the code so far:

```
$fieldTypePluginManager = $this->getContainer()->get('plugin.manager.field.field_type');
$input_types = [];
foreach ($fieldTypePluginManager->getGroupedDefinitions($fieldTypePluginManager->getUiDefinitions()) as $category => $field_types) {
    foreach ($field_types as $name => $field_type) {
        $input_types[] = $name;
    }
}
``` 

I still need to work on the properties per field type.

**Comment by omero** [comment]
awesome idea @jmolivas, just remember update the `module.info.yml`, if you decide use fields from others contrib modules, when you do that automatically your custom module is dependent of the contrib module.

**Comment by enzolutions** [comment]
Hi @jmolivas 

What you mentioned is more related with content/config entity, form generation must to use FAPI elements listed at https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/8

**Comment by jmolivas** [comment]
Yes @enzolutions you totally right.

**Comment by enzolutions** [comment]
So we can close this ticket, or you are thinking in a different approach

**Comment by jmolivas** [comment]
I leave this open until I take care of adding the url field.

**Comment by enzolutions** [comment]
Hi folks

in **\Drupal\comment\CommentForm** I found a URL field implementation.

```
$form['author']['homepage'] = array(
      '#type' => 'url',
      '#title' => $this->t('Homepage'),
      '#default_value' => $comment->getHomepage(),
      '#maxlength' => 255,
      '#size' => 30,
      '#access' => $is_admin || ($this->currentUser->isAnonymous() && $anonymous_contact != COMMENT_ANONYMOUS_MAYNOT_CONTACT),
    );
```

But is not a valid [FAPI](https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/8)  field yet.it's easy to include but I don't feel comfortable adding something not official, or maybe the documentation is behind?

**Comment by jmolivas** [comment]
@cweagans 'url' field type is now supported
