### ISSUE TITLE
[generate:entity:config] Default menu path doesn't match up

### ISSUE THREAD

**Issue by Crell** [hechoendrupal/DrupalConsole#722]
When generating a config entity, the path of the admin forms is placed under /admin/config/system/{entity}.  The menu LINK, however, is parented to /admin/structure.

While that technically doesn't break anything, it's highly confusing. The generator should standardize on one or the other.  I nominally think it makes more sense under structure than config/system, but as long as it's consistent I can deal.

**Comment by Sutharsan** [comment]
PR at https://github.com/hechoendrupal/DrupalConsole/pull/756
