### ISSUE TITLE
[config:import:single] Add a new command to import single configuration.

### ISSUE THREAD

**Issue by Jaesin** [hechoendrupal/DrupalConsole#723]
I need to import just one single config item all of the time. This new command does the config import of just one config entity. 

https://github.com/Jaesin/DrupalAppConsole/commit/dc25a6cb16509b8fe4d98f753a756088edd65ecc

I wanted to be able to pipe data to the command and that works. The remaining issue is that if you don't supply a file name and there is no pipe, you are prompted for stdin. That's probably not what we want. If there is no input we should probably prompt to import the config from `$config_directories['staging']`.

**Comment by jmolivas** [comment]
Nice @Jaesin I remember @enzolutions was working on a `config:import` command on this PR https://github.com/hechoendrupal/DrupalConsole/pull/441 this may this helps. 

I need to review both commands to have a better idea of how they work.

**Comment by jmolivas** [comment]
@Jaesin do you mind to send a PR ?
