### ISSUE TITLE
[generate:controller] Do not require to implements ContainerInjectionInterface

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#725]
### Problem/Motivation
The Controller generation render a controller class that extends form `ControllerBase ` and implements `ContainerInjectionInterface`

But his is not necessary since since `ControllerBase ` already implements `ContainerInjectionInterface`  [Abstract class ControllerBase documentation](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Controller%21ControllerBase.php/class/ControllerBase/8)

### How to reproduce
Generate a controller: 
```
$ console.dev generate:controller 
```
And answer yes to 
```
Do you want to load services from the container [no]? y
```
![screen shot 2015-07-01 at 10 55 20 am](https://cloud.githubusercontent.com/assets/366275/8461196/b16ea25c-1fdf-11e5-97f8-d2860de1d21c.png)

### Solution
Update twig template `templates/module/src/Controller/controller.php.twig`
```
# Remove this line
use Drupal\Core\DependencyInjection\ContainerInjectionInterface;

# make this line
class DefaultController extends ControllerBase implements ContainerInjectionInterface {
# render as 
class DefaultController extends ControllerBase {
```

**Comment by danielrose28** [comment]
@jmolivas thanks for giving me an issue to try out. I'll work on it and ask questions as needed.

**Comment by jmolivas** [comment]
@danielrose28: Thank you, for showing interest in contribute to the project

**Comment by danielrose28** [comment]
@jmolivas how does this look? I wasn't sure if I needed to use the actual "render method" or to just format this added line to read this way. 

![screen shot 2015-07-02 at 12 38 08 am](https://cloud.githubusercontent.com/assets/12372245/8470031/de3a21e4-2052-11e5-8a49-4ff978e5fd99.png)

**Comment by jmolivas** [comment]
@danielrose28 

Line 14 
```
use Drupal\Core\DependencyInjection\ContainerInjectionInterface;
```
Must me removed 

Line 25 
```
class {{ class_name }} extends ControllerBase {% if services is not empty %}implements ContainerInjectionInterface {% endif %}
```
Must look like this
```
class {{ class_name }} extends ControllerBase 
```
