### ISSUE TITLE
[generate:entity:config] Separate class name and human name in wizard

### ISSUE THREAD

**Issue by Crell** [hechoendrupal/DrupalConsole#743]
When generating a config entity (or probably content entity, but I've not tried) that logically is multiple words, the generated code uses the class name as if it were the human-readable name.  That's not the case, however.  Eg, if I'm creating a ModerationState config entity, I end up with strings and labels and page titles like "Edit ModerationState", "Add new ModerationState", etc.  So the very first thing I have to do is go through and change all of those labels to add a space... which is exactly what a generator is for. :smile: 

Instead, the wizard should ask for a class name and, separately, a human-friendly name (defaulting to the class name), and use the latter in all user-facing strings.

**Comment by jmolivas** [comment]
Like the idea.

**Comment by Sutharsan** [comment]
Working on this...

**Comment by Sutharsan** [comment]
Done. See #759

**Comment by jmolivas** [comment]
Fixed
