### ISSUE TITLE
[console] Add multi-site support

### ISSUE THREAD

**Issue by ansorg** [hechoendrupal/DrupalConsole#755]
As of version 0.7.15 console does not recognize a drupal folder as such if sites/default/settings.php is not used but a different sites/xqz/settings.php instead. 
An implementation would need to parse sites/sites.php for the multi-site setup and accept some parameter to specify the site, i. e. like ``drush --uri=``

**Comment by kylebrowning** [comment]
Verified, this causes Drupal Console to not work with Acquia Dev Desktop

**Comment by jmolivas** [comment]
@kylebrowning Thanks for testing it.

**Comment by kylebrowning** [comment]
@jmolivas  And any multi site setup for that matter

**Comment by nerdstein** [comment]
This is crucial for adoption. Many large scale Drupal builds leverage multisite and this will no doubt hinder efforts
