### ISSUE TITLE
Console don't running at beta 13

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalConsole#767]
This error appear.. 

drupal generate:module
PHP Fatal error:  Cannot redeclare GuzzleHttp\Psr7\str() (previously declared in phar:///usr/local/bin/drupal/vendor/guzzlehttp/psr7/src/functions.php:17) in /var/www/html/devbeta13/core/vendor/guzzlehttp/psr7/src/functions.php on line 39

**Comment by alexander-bogomolov** [comment]
Issue from Drupal.org: https://www.drupal.org/node/2538484

**Comment by jmolivas** [comment]
@vacho / @alexander-bogomolov 
We just tagged a new release 0.8.0 please update the project, for more information about updating please read:   
- http://hechoendrupal.gitbooks.io/drupal-console/content/using/update.html  
- http://hechoendrupal.gitbooks.io/drupal-console/content/contributing/keeping-your-fork-up-to-date.html

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/771 merged on this release https://github.com/hechoendrupal/DrupalConsole/releases/tag/0.8.0

**Comment by alexander-bogomolov** [comment]
Thank you!
