### ISSUE TITLE
Chasing HEAD: generate:plugin:field no longer functions

### ISSUE THREAD

**Issue by heddn** [hechoendrupal/DrupalConsole#781]
- [x] There are some obvious syntax errors in the result of `drupal generate:plugin:field` i.e. semi-colons in the wrong place, missing parenthesis.
- [x] The directories for the generated classes does not include Field for all classes created
  ex. src/Plugin/FieldFormatter (correct is src/Plugin/Field/FieldFormatter
-  [x] Lastly, the field formatter references an used import: `use Drupal\Core\Field\FieldDefinitionInterface;`

**Comment by heddn** [comment]
The above PR doesn't fix all the issues. I don't know how to solve the second bullet item. But it gets us closer.

**Comment by jmolivas** [comment]
@heddn: Thanks this PR https://github.com/hechoendrupal/DrupalConsole/pull/780 fix the point number 2

**Comment by heddn** [comment]
The second bullet from above is still not fixed in HEAD. I just built a new PHAR and tested. I'll see if I can figure out why.

The directories for the generated classes does not include Field for all classes created ex. src/Plugin/FieldFormatter (correct is src/Plugin/Field/FieldFormatter

**Comment by jmolivas** [comment]
According to the merged PR looks like should be fixed https://github.com/hechoendrupal/DrupalConsole/pull/780/files
But looking at the code not fixed yet, feel free to send a PR to have it fix.

**Comment by jmolivas** [comment]
@heddn: You can see what is required to have it fix by looking at the code of the mentioned PR
https://github.com/hechoendrupal/DrupalConsole/pull/780/files

**Comment by enzolutions** [comment]
@heddn could yo confirm if generate:plugin:field is now working for you?

**Comment by heddn** [comment]
It was a few weeks ago.
