### ISSUE TITLE
[generate:entity:content] After generate the entity, the permission are not properly set.

### ISSUE THREAD

**Issue by jjcarrion** [hechoendrupal/DrupalConsole#797]
Once you create a content entity, the permissions are not set properly as it's shown in the screenshot:
![selection_144](https://cloud.githubusercontent.com/assets/1206328/9292959/5b4456ec-4415-11e5-8b9e-2745258fd8a3.png)
As you can see, the Edit (Redigera) tab is shown for anonymous users.

After the PR should work like this:
![selection_145](https://cloud.githubusercontent.com/assets/1206328/9292963/75fecb70-4415-11e5-80ca-e267bfdc57fc.png)

I'll submit the PR during the day (hopefully :P)

**Comment by jjcarrion** [comment]
Here is the PR:
https://github.com/hechoendrupal/DrupalConsole/pull/798

**Comment by jmolivas** [comment]
Fixed with PR #798
