### ISSUE TITLE
[generate:module] Error create new module (SplFileIfo::getMTime() ...)

### ISSUE THREAD

**Issue by kegilkoo** [hechoendrupal/DrupalConsole#800]
When I try to generate a module I got the following error :

> [RuntimeException]
> SplFileInfo::getMTime(): stat failed for core/modules/action/action.info.yml

Drupal console version : 0.8.2
Drupal beta version : beta14
(you can see this informations in my screenshot)

![error and versions](http://img15.hostingpics.net/pics/566779Untitled.png)

no one had this bug?

**Comment by jmolivas** [comment]
@kegilkoo: At this point you must run Drupal Console within the D8 site root.

**Comment by edutrul** [comment]
By the way also when running your own commands with ($ drupal generate:command)

$ drupal custom_module:mycommand 
I get: 
  There are no commands defined in the "custom_migrate" namespace.
to fix that is what @jmolivas mentioned:
"At this point you must run Drupal Console within the D8 site root."

**Comment by kegilkoo** [comment]
Roooo Im very stupid x) 
Thank you guys =)
