### ISSUE TITLE
[generate:entity:config] doesn't create "collection" property under links section of links

### ISSUE THREAD

**Issue by tedbow** [hechoendrupal/DrupalConsole#807]
I just used "generate:entity:config".

It doesn't generate:entity:config doesn't create "collection" property under links section of links of the annotations.

Generated code:
```
 *   links = {
 *     "canonical" = "/admin/structure/visibility_group/{visibility_group}",
 *     "edit-form" = "/admin/structure/visibility_group/{visibility_group}/edit",
 *     "delete-form" = "/admin/structure/visibility_group/{visibility_group}/delete",
 *   }
```
When I add a new entity or save an existing 1 I get the error
><em class="placeholder">Drupal\Core\Entity\Exception\UndefinedLinkTemplateException</em>: No link template &#039;collection&#039; found for the &#039;visibility_group&#039; entity type in <em class="placeholder">Drupal\Core\Entity\Entity-&gt;urlInfo()</em> (line <em class="placeholder">198</em> of <em class="placeholder">/Applications/MAMP/htdocs/do_modules/d8_page_manager/core/lib/Drupal/Core/Entity/Entity.php</em>).

If add another line it fixes it

```
 *   links = {
 *     "canonical" = "/admin/structure/visibility_group/{visibility_group}",
 *     "edit-form" = "/admin/structure/visibility_group/{visibility_group}/edit",
 *     "delete-form" = "/admin/structure/visibility_group/{visibility_group}/delete",
 *     "collection" = "/admin/structure/visibility_group"
 *   }
```

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/809
