### ISSUE TITLE
[generate:entity:content] Ask if you want to include the CT in the list of existing content types

### ISSUE THREAD

**Issue by cosmicdreams** [hechoendrupal/DrupalConsole#810]
Hi all

Is it possible programmatically create a content type so that it can be listed in the list of content types that are created by the UI?

If it is it would be nice to ask the developer if they would like to add their CT into that list and perhaps make that the default option.  

I just went through the process of creating a CT through the generator for the first time and found that this was the first thing I wanted to do.  

My use case is that if I'm on project that needs multiple content type I would like to approach the building of all of the structures from a Code-only perspective but keep the UI for all the structures under control.

**Comment by cosmicdreams** [comment]
I think what I'm looking for is https://github.com/hechoendrupal/DrupalConsole/issues/299

**Comment by enzolutions** [comment]
@jmolivas I guess @cosmicdreams was right we could close this ticket. What do you think

**Comment by jmolivas** [comment]
yes @enzolutions, @cosmicdreams sent a PR related to this issue and is already merged.
