### ISSUE TITLE
[listbuilder-entity-content.php.twig] Should make use of the LinkGeneratorTrait

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/DrupalConsole#834]
I have been using 

console generate:entity:content

command alot recently and it generates really good code fragments..

I have noticed a minor issue with the template ..and want to make a small improvement.

I want to refactor the use of \Drupal::l() - to achieve better isolation between frameworks.

The problem with \\Drupal::l()  is that it introduces an implicit dependency on Drupal.php which places a function in the global state namespace .... if you want to work with another framework which defines  a global state function call l() then there is a problem!! 

The solution is conventional - make use of the LinkGeneratorTrait and call $this->l() instead.

I am working on a patch now...

**Comment by martinfrances107** [comment]
I no longer think this is a good thing .... 

To work the list builder would have to become a container aware....

maybe in the future.... sorry for the noise.

**Comment by jmolivas** [comment]
@martinfrances107: The generated `ListBuilder` class is already extending [EntityListBuilder](https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Entity!EntityListBuilder.php/class/EntityListBuilder/8)

And as you can see the code is using a factory method `createInstance` to extract services form the container and inject via de  `__construct` method.
```
  /**
   * {@inheritdoc}
   */
  public static function createInstance(ContainerInterface $container, EntityTypeInterface $entity_type) {
    return new static(
    $entity_type, 
    $container->get('entity.manager')->getStorage($entity_type->id())
    );
  }

  /**
   * Constructs a new EntityListBuilder object.
   *
   * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
   *   The entity type definition.
   * @param \Drupal\Core\Entity\EntityStorageInterface $storage
   *   The entity storage class.
   */
  public function __construct(EntityTypeInterface $entity_type, EntityStorageInterface $storage) {
    $this->entityTypeId = $entity_type->id();
    $this->storage = $storage;
    $this->entityType = $entity_type;
  }

```
