### ISSUE TITLE
Unable to install modules downloaded from git?

### ISSUE THREAD

**Issue by damienmckenna** [hechoendrupal/DrupalConsole#839]
I keep a local testbed install of Drupal for working on contrib modules. I've just reloaded my D8 install with the latest beta15 and updated console to 0.8.3, and now I can't enable modules checked out via git using console. For example:

```
$ drupal module:install redirect
[+] Unable to install modules redirect due to missing modules redirect

 The command was executed successfully! 
```

**Comment by jmolivas** [comment]
@damienmckenna: do you mind to share the gitbub repo, I tried this https://github.com/md-systems/redirect and it works fine 
```
➜  drupal8.dev drupal module:install redirect
[+] The following module(s) were installed successfully: redirect

 The command was executed successfully!
```

I ran `module:debug` and shown as enabled
```
redirect            Redirect                  Enabled  Other
```
I also ran `container:debug` and saw the following registered services:
``` 
 redirect.repository                     Drupal\redirect\RedirectRepository
 redirect.checker                        Drupal\redirect\RedirectChecker
 redirect.request_subscriber      Drupal\redirect\EventSubscriber\RedirectRequestSubscriber
 redirect.settings_cache_tag      Drupal\redirect\EventSubscriber\RedirectSettingsCacheTag
```

**Comment by damienmckenna** [comment]
I was using the following:

* git@github.com:md-systems/redirect.git
* damienmckenna@git.drupal.org:project/metatag.git (i.e. my maintainer a/c)

FYI I'm using PHP 5.6.6 from MAMP Pro 5.1.

Incidentally, when I run "drupal module:debug" I get the following:

```
$ drupal module:debug

 The command was executed successfully! 



                                                                                
  [RuntimeException]                                                            
  SplFileInfo::getMTime(): stat failed for core/modules/action/action.info.yml  
                                                                                


module:debug [--status [STATUS]] [--type [TYPE]]
```

Maybe something is broken locally?

**Comment by jmolivas** [comment]
@damienmckenna: I have seen that error while running `DrupalConsole` outside of the drupal-8-root directory example inside `modules` or `modules/custom`, may you try this again running at the drupal-8-root directory.

**Comment by damienmckenna** [comment]
Yes, ok, the module:status command works when I'm at the site root. module:install is still failing, though.

**Comment by damienmckenna** [comment]
FYI "drupal -vvv module:install metatag" doesn't make any difference, the output is still the same as above.

**Comment by jmolivas** [comment]
I tried downloaded and installed `metatag` and it works. I attached a screenshot:
![metatag-download-install](https://cloud.githubusercontent.com/assets/366275/9722494/162f747e-5563-11e5-93dd-d79d8e79b1a1.png)

**Comment by damienmckenna** [comment]
Well phooey. Guess I'll poke it with a stick and see what I can work out. Thanks for your help.

**Comment by jmolivas** [comment]
I tried with `drush` `dl` and `en` and it works too 
![metatag-drush-dl-en](https://cloud.githubusercontent.com/assets/366275/9722850/b3f0b492-5569-11e5-8c6f-44c1a185eab5.png)

**Comment by damienmckenna** [comment]
So yeah, something's wrong with my local install, *none* of the projects downloaded to /modules/contrib are showing on the admin/modules page. Gah.

**Comment by jmolivas** [comment]
Kinda strange, does `console.dev module:debug` return any output ?

**Comment by damienmckenna** [comment]
I decided to just delete it and start over ;)

**Comment by damienmckenna** [comment]
Ok, after reinstalling it now says:

```
[InvalidArgumentException]
There are no commands defined in the "module" namespace.
```

**Comment by damienmckenna** [comment]
FYI I'm still running PHP 5.6.6 on MAMP 3.1, I'll try to update to 3.4 this weekend which includes a newer PHP.

**Comment by damienmckenna** [comment]
I solved the problem - my local install was borken. After I sorted that out the modules are visible again.

**Comment by damienmckenna** [comment]
Thanks for the help.

**Comment by jmolivas** [comment]
Yay awesome, I am glad to hear that
