### ISSUE TITLE
[generate:contenttype] Update command name to generate:entity:bundle

### ISSUE THREAD

**Issue by cosmicdreams** [hechoendrupal/DrupalConsole#848]
We should rename the generator for creating new classic content types (an Entity Bundle) to generate:entity:bundle

Perhaps we could use the opportunity to explore how the command could accept as a parameter any kind of entity (node or custom content entity) and create a new bundle based on the config.  That's the best ending for this command I think.

In the meantime. Let's just rename the command.

**Comment by jmolivas** [comment]
:+1: like the idea

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/941
