### ISSUE TITLE
[generate:module] should escape user-entered input (e.g. quotes)

### ISSUE THREAD

**Issue by anavarre** [hechoendrupal/DrupalConsole#879]
If you type the below description:

```
$ console generate:module

 Welcome to the Drupal module generator 

Enter the new module name: The module I'd like to build
```
You'll get this in code:

```php
/**
 * Implements hook_help().
 */
function config_backup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test module.
    case 'help.page.test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The module I'd like to build.') . '</p>';
      return $output;

    default:
  }
}
```

Problem is the quote is not escaped, causing a PHP parse error when the module is enabled. It would be preferable to either escape the quotes or wrap strings in double quotes to prevent this.

**Comment by jmolivas** [comment]
@anavarre: Nice catch, thanks for reporting, we will take care.

**Comment by VasquezPonte** [comment]
https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/t/7

**Comment by jmolivas** [comment]
Fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/940
