### ISSUE TITLE
[about] Improve default command output

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalConsole#894]
A new feature on the [v0.9.0](https://github.com/hechoendrupal/DrupalConsole/releases/tag/0.9.0) is the new default output when no command is given.

This is how the new output looks like:

![drupal-console-about](https://cloud.githubusercontent.com/assets/366275/10003705/b90b98d0-6062-11e5-874c-e473d157d453.png)

#### We are planning to improve this feature and this is what we have in mind:
- [x] Display Installed Drupal Console version.
- [x] Display Drupal Console landing page.
- [ ] Display Installed Drupal version if running on a drupal 8 site root.
- [ ] Display Installed PHP version and show a warning if not supported.  
- [ ] Provide a configuration key to override this feature, readable from `~/.console/config.yml`, this you allow you to configure list command back o any other as default command.

#### We want to hear your ideas, like it or hate it please let us now.

**Comment by jmolivas** [comment]
Reply via twiter

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr"><a href="https://twitter.com/drupalconsole">@drupalconsole</a> Add the Drupal Console version?</p>&mdash; Luckhardt Labs (@LuckhardtLabs) <a href="https://twitter.com/LuckhardtLabs/status/646052584608919552">September 21, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by jmolivas** [comment]
I sent a PR https://github.com/hechoendrupal/DrupalConsole/pull/908 including 
- Display Installed Drupal Console version.
- Display Drupal Console landing page.

This is how the new output looks like:

![drupal-console-about](https://cloud.githubusercontent.com/assets/366275/10040447/a53feb4c-6190-11e5-8858-c5f5b7c30a68.png)

**Comment by yosymfony** [comment]
Setting up a custom domain for Bitly links (it's free)

**Comment by favrik** [comment]
I think the default console output should be something more helpful like `symfony`'s output:
```shell
 Symfony Installer (1.1.7)
 =========================

 This is the official installer to start new projects based on the
 Symfony full-stack framework.

 To create a new project called blog in the current directory using
 the latest stable version of Symfony, execute the following command:

   symfony new blog

 Create a project based on the Symfony Long Term Support version (LTS):

   symfony new blog lts

 Create a project based on a specific Symfony branch:

   symfony new blog 2.3

 Create a project based on a specific Symfony version:

   symfony new blog 2.5.6

 Create a demo application to learn how a Symfony application works:

   symfony demo

 Updating the Symfony Installer
 ------------------------------

 New versions of the Symfony Installer are released regularly. To update your
 installer version, execute the following command:

   symfony self-update

```

`composer` displays version information and all the available commands when no argument/option is passed.

Perhaps the proposed output is more suited to `drupal about`.  Anyway, personally, I always keep going back to just typing the name of an utility, to get the list of options/commands.

**Comment by jmolivas** [comment]
@favrik Like de idea of adding useful information. We decide not to list the commands since was really long list.

We will add a configuration option at `~/.console/config.yml,` to override this feature,  this you allow you to configure list command back o any other as default command.

**Comment by favrik** [comment]
@jmolivas I know I know, this is just one of my use cases. XD  But I always do something like `console | grep ...` for long lists of commands.  Anyway, the config option is/would be great. :)

**Comment by jmolivas** [comment]
Updated output when executing  `drupal` 

```
Drupal Console version (0.9.8)
===========================================

The Drupal Console is a suite of tools that you run on the CLI to:
 * Learn Drupal 8.
 * Generate boilerplate code.
 * Interact with a Drupal 8 installation.

Accessing console from anywhere on your system

  mv console.phar /usr/local/bin/drupal

Copy configuration files to user home directory.

  drupal init [--override]

Download, install and serve Drupal 8

  drupal chain --file=~/.console/chain/quick-start.yml

Create a new Drupal project

  drupal site:new drupal8.dev 8.0.0

Update the console to latest version.

  drupal self-update

Lists all available commands

  drupal list

Project links
 * Landing page - http://drupalconsole.com
 * Change log at - http://bit.ly/console-releases
 * Documentation at - http://bit.ly/console-book
 * Support chat room - http://bit.ly/console-support

Supporting organizations
 * FFW - http://ffwagency.com
 * Anexus - http://anexusit.com
 * Indava - http://indava.com
```

**Comment by darol100** [comment]
I personally think that these info is overkill:

`````
Accessing console from anywhere on your system

  mv console.phar /usr/local/bin/drupal

Copy configuration files to user home directory.

  drupal init [--override]

Create a new Drupal project

  drupal site:new drupal8.dev 8.0.0

``````

### Why ?

Because these are things that your rarely use (IMO). `  drupal site:new drupal8.dev 8.0.0` might be something that the developer use often but I think we should encourager the developer to use  ` drupal chain --file=~/.console/chain/quick-start.yml` instead.


`````
Update the project to latest version.

  drupal self-update

``````

To me this make me think that is going to update my drupal installation not my drupalconsole.


I think it will be better like this....

````
Drupal Console version (0.9.8)
==============================

The Drupal Console is a suite of tools that you run on the CLI to:
 * Learn Drupal 8.
 * Generate boilerplate code.
 * Interact with a Drupal 8 installation.

Download, install and serve Drupal 8

  drupal chain --file=~/.console/chain/quick-start.yml

Lists all available commands

  drupal list

````

What you guys think?

**Comment by jmolivas** [comment]
We make some changes on latest release, the output is like this:
```

Drupal Console (0.9.10) | Supports Drupal 8.0.1
===============================================

Copy configuration files to user home directory.

   drupal init [--override]

Download, install and serve Drupal 8

   drupal chain --file=~/.console/chain/quick-start.yml

Create a new Drupal project

   drupal site:new drupal8.dev 8.0.1

Install a Drupal project

   drupal site:install

Lists all available commands

   drupal list

Update project to the latest version.
-------------------------------------

   drupal self-update
```

**Comment by jmolivas** [comment]
I like to keep this, since is a good way to override DC behaviour
```
Copy configuration files to user home directory.

   drupal init [--override]
```

Related to this, I like to keep at least for now for people to know how to do it, we can remove once the project features are well known
```
Create a new Drupal project

   drupal site:new drupal8.dev 8.0.1

Install a Drupal project

   drupal site:install
```

**Comment by darol100** [comment]
This issue have been solve already.
