### ISSUE TITLE
No support for Acquia Dev Desktop

### ISSUE THREAD

**Issue by mmenavas** [hechoendrupal/DrupalConsole#919]
When a new Drupal 8 site is created with Acquia Dev Desktop (ADD), ADD does not store the database credentials in settings.php. We'll need to find a way to read this credentials in the same way drush does it.

**Comment by mmenavas** [comment]
Where is the recommended place to add the code below?

```
// Add support for Acquia Dev Desktop sites on Mac OS X
if (files_exists($_SERVER['HOME'] . "/.acquia/DevDesktop/DrupalSettings")) {
  $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] = $_SERVER['HOME'] . "/.acquia/DevDesktop/DrupalSettings";
}
// @TODO: Add support for Acquia Dev Desktop sites on Windows
```
I currently have it on bin/console and it works with Acquia Dev Desktop sites.

**Comment by mmenavas** [comment]
FYI: I had to add `date_default_timezone_set('europe/madrid');` to avoid getting the exception below
```
[Exception] DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your time zone.
```

**Comment by mmenavas** [comment]
Disregard my last comment as the PHP bundled with my OS did not configure a default timezone.

**Comment by dmouse** [comment]
I think that is better use set/getenv that $_SERVER variable

**Comment by jmolivas** [comment]
@dmouse Wast this closed with PR https://github.com/hechoendrupal/DrupalConsole/pull/920 ?
